#!/usr/bin/env python3
import json
from pathlib import Path

# Comprehensive translation dictionary
TRANSLATIONS = {
    "色彩管理系统评测": "Color Management System Review",
    "色彩管理的核心价值与应用场景": "Core Value and Application Scenarios of Color Management",
    "色彩管理是印刷": "Color management is the quality cornerstone of print",
    "设计": "design",
    "摄影": "photography",
    "影视行业的质量基石": "film industry",
    "从设计师屏幕显示": "From designer screen display",
    "摄影师拍摄": "photographer shooting",
    "印刷机输出到最终成品": "print machine output to final product",
    "色彩在各设备间传递时会发生偏差": "color deviation occurs during device transfer",
    "色彩管理系统通过": "Color management system through",
    "ICC特性文件": "ICC profile",
    "校准设备": "calibration equipment",
    "色彩转换引擎": "color conversion engine",
    "确保色彩一致性": "ensure color consistency",
    "减少沟通误解": "reduce communication misunderstanding",
    "降低返工成本": "reduce rework cost",
    "提升品牌色彩准确度": "improve brand color accuracy",
    "据行业统计": "According to industry statistics",
    "色彩问题导致的印刷返工占总返工的": "color problem caused print rework accounts for",
    "年损失超": "annual loss exceeds",
    "色彩管理系统投资回报周期通常": "color management system ROI period typically",
    "个月": "months",
    "成为专业机构的必备工具": "become essential tool for professional organizations",
    "年色彩管理市场呈现": "2026 color management market presents",
    "Pantone色彩标准引领": "Pantone color standard leading",
    "X-Rite设备校准专业": "X-Rite equipment calibration professional",
    "Datacolor性价比普及": "Datacolor cost-effective普及",
    "三方格局": "three-party pattern",
    "Pantone色彩系统深度评测": "Pantone Color System Deep Review",
    "色彩行业标准的领导者": "Leader of Color Industry Standard",
    "Pantone是色彩沟通的全球标准": "Pantone is global standard for color communication",
    "其": "its",
    "Pantone Matching System": "PMS",
    "色卡被印刷": "color card is used in print",
    "纺织": "textile",
    "化妆品等行业广泛采用": "cosmetics industries widely adopted",
    "年Pantone核心产品线": "2026 Pantone core product line",
    "Pantone Color Guides": "实体色卡": "physical color card",
    "实体色卡": "physical color card",
    "年版含": "2026 version contains",
    "色": "colors",
    "Formula Guide": "Formula Guide",
    "色彩": "colors",
    "Fashion, Home + Interiors": "Fashion, Home + Interiors",
    "Pantone Connect": "Pantone Connect",
    "云端色彩平台": "cloud color platform",
    "数字色库": "digital color library",
    "设计插件": "design plugin",
    "协作工具": "collaboration tool",
    "PantoneLIVE": "PantoneLIVE",
    "印刷色彩管理云端系统": "print color management cloud system",
    "品牌色彩数字化传递": "brand color digital transmission",
    "Pantone Connect数字平台": "Pantone Connect Digital Platform",
    "是年重点推广的云端色彩平台": "is 2026 key promoted cloud color platform",
    "设计插件": "Design plugin",
    "Adobe CC插件": "Adobe CC plugin",
    "直接在Photoshop": "directly in Photoshop",
    "Illustrator": "Illustrator",
    "InDesign中调用Pantone色库": "call Pantone color library in InDesign",
    "色彩转换": "Color conversion",
    "Pantone色自动转换为CMYK": "Pantone color auto convert to CMYK",
    "RGB": "RGB",
    "Lab值": "Lab value",
    "色彩协作": "Color collaboration",
    "云端色彩板共享": "cloud color board sharing",
    "团队统一色彩标准": "team unified color standard",
    "色卡管理": "Color card management",
    "实体色卡数字化扫描录入": "physical color card digital scan input",
    "用户评价": "User evaluation",
    "设计师反馈Connect插件极大提升选色效率": "Designer feedback Connect plugin greatly improves color selection efficiency",
    "但部分Pantone色无法精准转换为CMYK": "but some Pantone colors cannot accurately convert to CMYK",
    "印刷时需参考实体色卡": "print needs reference physical color card",
    "PantoneLIVE印刷色彩管理": "PantoneLIVE Print Color Management",
    "面向印刷企业与品牌方": "faces print enterprise and brand side",
    "品牌色彩数字化": "Brand color digitalization",
    "将品牌标准色数字化": "digitize brand standard color",
    "传递至印刷厂": "transmit to print factory",
    "印刷验证": "print verification",
    "印刷输出色彩数据采集": "print output color data collection",
    "与标准对比": "compare with standard",
    "供应链协同": "supply chain collaboration",
    "品牌方": "brand side",
    "印刷厂": "print factory",
    "油墨供应商色彩统一": "ink supplier color unification",
    "适合大型品牌": "suitable for large brands",
    "如可口可乐": "like Coca-Cola",
    "苹果": "Apple",
    "的色彩标准化": "color standardization",
    "中小印刷厂使用成本较高": "small-medium print factory use cost high",
    "价格": "Price",
    "实体色卡套装": "physical color card set",
    "月个人版": "monthly personal version",
    "月团队版": "monthly team version",
    "企业定制": "enterprise customization",
    "年费": "annual fee",
    "X-Rite Pantora专业色彩校准系统评测": "X-Rite Pantora Professional Color Calibration System Review",
    "印刷色彩校准的行业标准": "Industry Standard for Print Color Calibration",
    "X-Rite是色彩测量设备领导者": "X-Rite is color measurement equipment leader",
    "其i系列校准设备": "its i1 series calibration equipment",
    "与Pantora色彩管理平台": "and Pantora color management platform",
    "服务于印刷": "serves print",
    "设计专业用户": "design professional users",
    "硬件校准设备": "Hardware Calibration Equipment",
    "iPro": "i1Pro",
    "分光光度计": "spectrophotometer",
    "屏幕校准+印刷测量一体化": "screen calibration + print measurement integrated",
    "iDisplay Pro": "i1Display Pro",
    "色度计": "colorimeter",
    "专业显示器校准": "professional monitor calibration",
    "Pantora": "Pantora",
    "印刷色彩特性文件生成与管理平台": "print color profile generation and management platform",
    "Pantora平台功能": "Pantora Platform Features",
    "是X-Rite面向印刷行业的色彩管理平台": "is X-Rite print industry color management platform",
    "特性文件生成": "Profile generation",
    "测量印刷样张生成ICC特性文件": "measure print sample generate ICC profile",
    "色彩空间转换引擎": "color space conversion engine",
    "如RGB转CMYK": "like RGB to CMYK",
    "设备管理": "Equipment management",
    "多设备色彩特性统一管理": "multi-equipment color profile unified management",
    "色彩验证": "Color verification",
    "印刷输出色彩验证与报告": "print output color verification and report",
    "印刷企业应用": "Print enterprise application",
    "大型印刷厂使用iPro测量印刷机输出": "large print factory uses i1Pro measure print machine output",
    "生成ICC特性文件": "generate ICC profile",
    "确保色彩一致性": "ensure color consistency",
    "Pantora平台管理多台印刷机特性": "Pantora platform manages multi print machine profiles",
    "实现色彩标准化": "achieve color standardization",
    "专业优势": "Professional advantages",
    "测量精度": "Measurement accuracy",
    "X-Rite设备测量精度行业最高": "X-Rite equipment measurement accuracy industry highest",
    "特性文件质量": "Profile quality",
    "ICC特性文件生成算法领先": "ICC profile generation algorithm leading",
    "印刷适配": "Print adaptation",
    "专为印刷行业设计": "specifically designed for print industry",
    "油墨": "ink",
    "纸张特性支持": "paper characteristics support",
    "定价": "Pricing",
    "硬件": "hardware",
    "软件许可": "software license",
    "印刷色彩校准套装总成本": "print color calibration set total cost",
    "左右": "around",
    "Datacolor SpyderX色彩校准系统评测": "Datacolor SpyderX Color Calibration System Review",
    "性价比色彩校准方案": "Cost-effective Color Calibration Solution",
    "Datacolor是色彩管理领域的性价比品牌": "Datacolor is cost-effective brand in color management",
    "SpyderX系列面向": "SpyderX series faces",
    "摄影师": "photographers",
    "设计师": "designers",
    "小型印刷厂": "small print factories",
    "产品线": "Product line",
    "SpyderX Pro": "SpyderX Pro",
    "专业显示器校准": "professional monitor calibration",
    "快速校准": "fast calibration",
    "SpyderX Elite": "SpyderX Elite",
    "高级显示器校准": "advanced monitor calibration",
    "多显示器支持": "multi-monitor support",
    "SpyderPRINT": "SpyderPRINT",
    "印刷色彩校准": "print color calibration",
    "打印机特性生成": "printer profile generation",
    "SpyderCHECKR": "SpyderCHECKR",
    "摄影色彩参考卡": "photography color reference card",
    "SpyderX Elite核心功能": "SpyderX Elite Core Features",
    "校准时间约分钟": "calibration time about 1 minute",
    "比传统设备快倍": "5x faster than traditional equipment",
    "多显示器": "Multi-monitor",
    "支持多屏幕统一校准": "supports multi-screen unified calibration",
    "环境光检测": "ambient light detection",
    "检测环境光自动调整校准参数": "detect ambient light auto-adjust calibration parameters",
    "SoftProofing": "SoftProofing",
    "屏幕模拟印刷输出效果": "screen simulate print output effect",
    "用户反馈": "User feedback",
    "摄影师认为SpyderX Elite校准速度优势明显": "photographers think SpyderX Elite calibration speed advantage obvious",
    "日常使用便捷": "daily use convenient",
    "但精度不及X-Rite高端设备": "but accuracy not as good as X-Rite high-end equipment",
    "SpyderPRINT印刷校准": "SpyderPRINT Print Calibration",
    "打印机特性": "Printer profile",
    "打印测试样张测量生成ICC特性": "print test sample measure generate ICC profile",
    "色彩验证": "Color verification",
    "印刷输出与屏幕对比验证": "print output and screen comparison verification",
    "成本": "Cost",
    "低于X-Rite方案": "lower than X-Rite solution",
    "适合小型数字印刷工作室的色彩管理需求": "suitable for small digital print workshop color management needs",
    "价格对比": "Price Comparison",
    "Datacolor套装总成本低于X-Rite": "Datacolor set total cost lower than X-Rite 50%",
    "色彩管理系统对比分析表": "Color Management System Comparison Analysis Table",
    "对比维度": "Comparison dimension",
    "核心定位": "Core positioning",
    "色彩标准": "Color standard",
    "色彩校准": "Color calibration",
    "显示器校准": "Monitor calibration",
    "硬件设备": "Hardware equipment",
    "色卡实体": "color card (physical)",
    "iPro分光": "i1Pro (spectrophotometer)",
    "SpyderX色度计": "SpyderX (colorimeter)",
    "屏幕校准": "Screen calibration",
    "无": "none",
    "印刷测量": "Print measurement",
    "iPro": "i1Pro",
    "ICC生成": "ICC generation",
    "Pantora平台": "Pantora platform",
    "SpyderPRINT软件": "SpyderPRINT software",
    "PMS行业标准": "PMS industry standard",
    "自定义": "custom",
    "设计集成": "Design integration",
    "Adobe插件": "Adobe plugin",
    "间接": "indirect",
    "团队协作": "Team collaboration",
    "云端色彩板": "cloud color board",
    "本地管理": "local management",
    "测量精度": "Measurement accuracy",
    "视觉对比": "visual comparison",
    "最高": "highest",
    "良好": "good",
    "校准速度": "Calibration speed",
    "无需校准": "no calibration needed",
    "分钟": "minutes",
    "分钟": "minute",
    "年成本": "Annual cost",
    "个人": "personal",
    "硬件": "hardware",
    "适用对象": "Suitable users",
    "设计师": "Designers",
    "印刷厂": "Print factory",
    "摄影师设计师": "Photographers/Designers",
    "年色彩管理趋势预测": "2026 Color Management Trend Predictions",
    "云端色彩平台普及": "Cloud Color Platform Popularization",
    "代表云端色彩管理趋势": "represents cloud color management trend",
    "色彩标准云端存储": "color standard cloud storage",
    "团队协作": "team collaboration",
    "供应链传递": "supply chain transmission",
    "X-Rite与Datacolor将加强云端平台": "X-Rite and Datacolor will strengthen cloud platform",
    "AI色彩匹配": "AI Color Matching",
    "AI算法自动匹配色彩": "AI algorithm auto-match color",
    "输入实物照片自动识别Pantone色": "input physical photo auto-identify Pantone color",
    "AI推荐配色方案": "AI recommend color scheme",
    "印刷色彩自动优化": "print color auto-optimization",
    "Pantone Connect已引入AI功能": "Pantone Connect has introduced AI features",
    "移动端色彩测量": "Mobile Color Measurement",
    "手机色彩测量应用": "mobile phone color measurement application",
    "结合手机摄像头测量色彩": "combine mobile camera measure color",
    "精度有限但便捷": "accuracy limited but convenient",
    "Pantone已推出Pantone Connect移动应用": "Pantone has launched Pantone Connect mobile application",
    "品牌色彩数字化标准化": "Brand Color Digitalization Standardization",
    "大型品牌推动色彩数字化": "large brands promote color digitalization",
    "品牌色云端传递至印刷厂": "brand color cloud transmit to print factory",
    "包装厂": "packaging factory",
    "广告公司": "advertising company",
    "减少色彩误差沟通成本": "reduce color error communication cost",
    "环境光自适应": "Ambient Light Self-adaptation",
    "显示器校准考虑环境光": "monitor calibration considers ambient light",
    "Datacolor SpyderX已集成环境光检测": "Datacolor SpyderX has integrated ambient light detection",
    "未来自动调整屏幕色彩适应环境": "future auto-adjust screen color adapt environment",
    "选型建议": "Selection recommendations",
    "设计师色彩选择": "Designer color selection",
    "Pantone Connect插件集成Adobe CC": "Pantone Connect plugin integrates Adobe CC",
    "色彩标准沟通": "color standard communication",
    "摄影师显示器校准": "Photographer monitor calibration",
    "Datacolor SpyderX Elite性价比高": "Datacolor SpyderX Elite cost-effective",
    "校准速度快": "calibration speed fast",
    "印刷企业色彩管理": "Print enterprise color management",
    "X-Rite iPro + Pantora专业完整": "X-Rite i1Pro + Pantora professional complete",
    "小型印刷工作室": "Small print workshop",
    "Datacolor SpyderPRINT成本可控": "Datacolor SpyderPRINT cost controllable",
    "品牌色彩标准化": "Brand color standardization",
    "PantoneLIVE供应链色彩统一": "PantoneLIVE supply chain color unification",
    "色彩管理系统是专业投资": "Color management system is professional investment",
    "根据应用场景": "according to application scenario",
    "精度需求": "accuracy requirement",
    "预算综合选择": "budget comprehensive selection",
    "建议先校准显示器": "recommend first calibrate monitor",
    "色彩起点": "color starting point",
    "再扩展至印刷输出校准": "then expand to print output calibration",
    "专业评测年色彩管理系统": "Professional review 2026 color management system",
    "对比色彩校准精度": "compare color calibration accuracy",
    "设备支持": "equipment support",
    "为印刷": "for print",
    "摄影用户提供色彩一致性解决方案": "photography users provide color consistency solution",
    "了解更多功能和价格对比": "Learn more about features and price comparison",
    "找到最适合你的方案": "Find the best solution for you",
    "专业评测助你决策": "Professional review helps you decide",
    "专业评测": "Professional review",
    "对比": "comparison",
    "为印刷企业资源计划提供方案": "provide solution for print enterprise resource planning",
    "印刷企业资源计划的企业管理与业务流程需求": "Print Enterprise Resource Planning Enterprise Management and Business Process Needs",
    "印刷企业资源计划通过": "Print enterprise resource planning through",
    "企业资源计划": "enterprise resource planning",
    "企业管理": "enterprise management",
    "业务流程": "business process",
    "整合印刷资源": "integrate print resources",
    "帮助印刷企业": "help print enterprises",
    "整合企业资源": "integrate enterprise resources",
    "管理企业业务": "manage enterprise business",
    "优化业务流程": "optimize business process",
    "提升印刷企业运营效率": "improve print enterprise operation efficiency",
    "印刷企业资源计划需求": "Print enterprise resource planning needs",
    "企业资源计划": "Enterprise resource planning",
    "占比": "accounts for",
    "企业管理": "Enterprise management",
    "业务流程": "Business process",
    "资源整合": "Resource integration",
    "年印刷企业资源计划软件呈现": "2026 print enterprise resource planning software presents",
    "印刷ERP系统全面": "print ERP system comprehensive",
    "印刷企业管理专业": "print enterprise management professional",
    "印刷业务流程科学": "print business process scientific",
    "三种方案": "three solutions",
    "印刷ERP系统评测": "Print ERP System Review",
    "印刷ERP全面管理": "Print ERP Comprehensive Management",
    "印刷ERP系统定位": "Print ERP system positioning",
    "ERP管理": "ERP management",
    "核心功能": "Core functions",
    "财务管理": "Financial management",
    "财务核算管理": "financial accounting management",
    "采购管理": "Procurement management",
    "采购业务管理": "procurement business management",
    "销售管理": "Sales management",
    "销售业务管理": "sales business management",
    "库存管理": "Inventory management",
    "库存业务管理": "inventory business management",
    "生产管理": "Production management",
    "生产业务管理": "production business management",
    "核算管理": "Accounting management",
    "财务核算管理": "financial accounting management",
    "成本管理": "Cost management",
    "财务成本管理": "financial cost management",
    "报表管理": "Report management",
    "财务报表管理": "financial report management",
    "采购计划": "Procurement planning",
    "采购计划管理": "procurement planning management",
    "供应商管理": "Supplier management",
    "采购供应商管理": "procurement supplier management",
    "采购订单": "Procurement order",
    "采购订单管理": "procurement order management",
    "客户管理": "Customer management",
    "销售客户管理": "sales customer management",
    "订单管理": "Order management",
    "销售订单管理": "sales order management",
    "发货管理": "Delivery management",
    "销售发货管理": "sales delivery management",
    "库存核算": "Inventory accounting",
    "库存核算管理": "inventory accounting management",
    "库存预警": "Inventory warning",
    "库存预警管理": "inventory warning management",
    "库存盘点": "Inventory check",
    "库存盘点管理": "inventory check management",
    "生产计划": "Production planning",
    "生产计划管理": "production planning management",
    "生产排程": "Production scheduling",
    "生产排程管理": "production scheduling management",
    "生产跟踪": "Production tracking",
    "生产跟踪管理": "production tracking management",
    "用户评价": "User evaluation",
    "印刷厂认为ERP系统财务管理全面": "Print factory thinks ERP system financial management comprehensive",
    "生产管理科学": "production management scientific",
    "需与生产系统集成": "needs to integrate with production system",
    "印刷ERP系统": "Print ERP system",
    "许可": "license",
    "印刷企业管理评测": "Print Enterprise Management Review",
    "印刷企业专业管理": "Print Enterprise Professional Management",
    "印刷企业管理定位": "Print enterprise management positioning",
    "企业运营": "enterprise operation",
    "企业管理": "Enterprise management",
    "企业全面管理": "enterprise comprehensive management",
    "运营管理": "Operation management",
    "运营业务管理": "operation business management",
    "资源管理": "Resource management",
    "企业资源管理": "enterprise resource management",
    "管理报告": "Management report",
    "企业管理报告": "enterprise management report",
    "全面管理": "Comprehensive management",
    "部门管理": "Department management",
    "企业部门管理": "enterprise department management",
    "绩效管理": "Performance management",
    "企业绩效管理": "enterprise performance management",
    "业务管理": "Business management",
    "运营业务管理": "operation business management",
    "流程管理": "Process management",
    "运营流程管理": "operation process management",
    "效率管理": "Efficiency management",
    "运营效率管理": "operation efficiency management",
    "人力管理": "HR management",
    "企业人力管理": "enterprise HR management",
    "资金管理": "Fund management",
    "企业资金管理": "enterprise fund management",
    "资产管理": "Asset management",
    "企业资产管理": "enterprise asset management",
    "综合报告": "Comprehensive report",
    "企业管理报告生成": "enterprise management report generation",
    "运营报告": "Operation report",
    "运营分析报告": "operation analysis report",
    "资源报告": "Resource report",
    "资源分析报告": "resource analysis report",
    "印刷厂认为企业管理企业管理全面": "Print factory thinks enterprise management comprehensive",
    "运营管理科学": "operation management scientific",
    "需与ERP系统集成": "needs to integrate with ERP system",
    "印刷企业管理系统": "Print enterprise management system",
    "印刷业务流程评测": "Print Business Process Review",
    "印刷业务流程科学管理": "Print Business Process Scientific Management",
    "印刷业务流程定位": "Print business process positioning",
    "流程优化": "process optimization",
    "流程设计": "Process design",
    "业务流程设计": "business process design",
    "流程执行": "Process execution",
    "流程执行管理": "process execution management",
    "流程优化": "Process optimization",
    "流程优化管理": "process optimization management",
    "流程报告": "Process report",
    "流程分析报告": "process analysis report",
    "流程建模": "Process modeling",
    "业务流程建模": "business process modeling",
    "流程配置": "Process configuration",
    "流程配置管理": "process configuration management",
    "流程规则": "Process rule",
    "流程规则设置": "process rule setting",
    "执行管理": "Execution management",
    "流程执行管理": "process execution management",
    "监控管理": "Monitoring management",
    "流程监控管理": "process monitoring management",
    "异常处理": "Exception handling",
    "流程异常处理": "process exception handling",
    "优化分析": "Optimization analysis",
    "流程优化分析": "process optimization analysis",
    "效率优化": "Efficiency optimization",
    "流程效率优化": "process efficiency optimization",
    "成本优化": "Cost optimization",
    "流程成本优化": "process cost optimization",
    "分析报告": "Analysis report",
    "流程分析报告生成": "process analysis report generation",
    "效率报告": "Efficiency report",
    "流程效率报告": "process efficiency report",
    "优化报告": "Optimization report",
    "流程优化报告": "process optimization report",
    "印刷厂认为业务流程流程设计科学": "Print factory thinks business process design scientific",
    "流程执行规范": "process execution standardized",
    "需与企业管理系统集成": "needs to integrate with enterprise management system",
    "印刷业务流程系统": "Print business process system",
    "印刷企业资源计划软件对比分析表": "Print Enterprise Resource Planning Software Comparison Analysis Table",
    "对比维度": "Comparison dimension",
    "印刷ERP系统": "Print ERP system",
    "印刷企业管理": "Print enterprise management",
    "印刷业务流程": "Print business process",
    "企业资源全面计划": "enterprise resource comprehensive planning",
    "企业专业管理": "enterprise professional management",
    "业务流程科学管理": "business process scientific management",
    "财务管理": "Financial management",
    "核心功能": "core function",
    "企业财务": "enterprise financial",
    "流程财务": "process financial",
    "采购管理": "Procurement management",
    "采购业务": "procurement business",
    "企业采购": "enterprise procurement",
    "流程采购": "process procurement",
    "销售管理": "Sales management",
    "销售业务": "sales business",
    "企业销售": "enterprise sales",
    "流程销售": "process sales",
    "库存管理": "Inventory management",
    "库存业务": "inventory business",
    "企业库存": "enterprise inventory",
    "流程库存": "process inventory",
    "生产管理": "Production management",
    "生产业务": "production business",
    "企业生产": "enterprise production",
    "流程生产": "process production",
    "企业管理": "Enterprise management",
    "ERP管理": "ERP management",
    "流程管理": "process management",
    "运营管理": "Operation management",
    "ERP运营": "ERP operation",
    "业务管理": "business management",
    "流程运营": "process operation",
    "资源管理": "Resource management",
    "ERP资源": "ERP resource",
    "人力管理": "HR management",
    "流程资源": "process resource",
    "管理报告": "Management report",
    "ERP报告": "ERP report",
    "综合报告": "comprehensive report",
    "流程报告": "process report",
    "流程设计": "Process design",
    "ERP流程": "ERP process",
    "企业流程": "enterprise process",
    "流程执行": "Process execution",
    "ERP执行": "ERP execution",
    "企业执行": "enterprise execution",
    "执行管理": "execution management",
    "流程优化": "Process optimization",
    "ERP优化": "ERP optimization",
    "企业优化": "enterprise optimization",
    "优化分析": "optimization analysis",
    "流程报告": "Process report",
    "管理报告": "management report",
    "分析报告": "analysis report",
    "系统集成": "System integration",
    "生产系统": "production system",
    "企业管理系统": "enterprise management system",
    "成本": "Cost",
    "K-K": "K-K",
    "适用对象": "Suitable users",
    "企业资源计划需求": "enterprise resource planning needs",
    "企业管理需求": "enterprise management needs",
    "业务流程需求": "business process needs",
    "年印刷企业资源计划趋势预测": "2026 Print Enterprise Resource Planning Trend Predictions",
    "企业资源计划AI智能": "Enterprise resource planning AI intelligent",
    "企业资源计划AI智能": "Enterprise resource planning AI intelligent",
    "AI ERP智能管理": "AI ERP intelligent management",
    "AI企业智能运营": "AI enterprise intelligent operation",
    "AI流程智能优化": "AI process intelligent optimization",
    "企业资源计划云端化": "Enterprise resource planning cloudification",
    "企业资源计划云端化": "Enterprise resource planning cloudification",
    "云端ERP系统": "cloud ERP system",
    "云端企业管理": "cloud enterprise management",
    "云端业务流程": "cloud business process",
    "企业资源计划自动化": "Enterprise resource planning automation",
    "企业资源计划自动化": "Enterprise resource planning automation",
    "ERP自动化管理": "ERP automation management",
    "企业自动化运营": "enterprise automation operation",
    "流程自动化执行": "process automation execution",
    "企业资源计划数据分析": "Enterprise resource planning data analysis",
    "企业资源计划数据分析": "Enterprise resource planning data analysis",
    "ERP效果分析": "ERP effect analysis",
    "企业管理效果分析": "enterprise management effect analysis",
    "业务流程效果分析": "business process effect analysis",
    "企业资源计划移动应用": "Enterprise resource planning mobile application",
    "企业资源计划移动应用": "Enterprise resource planning mobile application",
    "移动ERP查看": "mobile ERP view",
    "移动企业管理查看": "mobile enterprise management view",
    "移动业务流程查看": "mobile business process view",
    "选型建议": "Selection recommendations",
    "企业资源全面计划": "Enterprise resource comprehensive planning",
    "ERP系统财务管理全面": "ERP system financial management comprehensive",
    "生产管理科学": "production management scientific",
    "企业专业管理": "Enterprise professional management",
    "企业管理企业管理全面": "enterprise management comprehensive",
    "业务流程科学管理": "Business process scientific management",
    "业务流程流程设计科学": "business process design scientific",
    "流程执行规范": "process execution standardized",
    "企业资源计划完整": "Enterprise resource planning complete",
    "ERP系统+企业管理+业务流程组合": "ERP system + enterprise management + business process combination",
    "预算有限": "Budget limited",
    "业务流程系统成本适中K-K": "business process system cost moderate $15K-$30K",
    "印刷企业资源计划软件选型需考虑企业资源计划需求": "Print enterprise resource planning software selection needs to consider enterprise resource planning needs",
    "企业管理需求": "enterprise management needs",
    "业务流程需求": "business process needs",
    "预算": "budget",
    "建议从业务流程系统起步": "recommend start from business process system",
    "逐步升级企业管理与ERP系统": "gradually upgrade enterprise management and ERP system",
    "印刷企业资源计划软件评测": "Print Enterprise Resource Planning Software Review",
    "印刷ERP系统": "Print ERP system",
    "印刷企业管理与印刷业务流程对比": "Print Enterprise Management and Print Business Process Comparison",
    "年评测": "2026 Review",
    "专业评测年印刷企业资源计划软件印刷ERP系统": "Professional review 2026 print enterprise resource planning software print ERP system",
    "印刷企业管理": "print enterprise management",
    "印刷业务流程": "print business process",
    "对比企业资源计划": "compare enterprise resource planning",
    "企业管理": "enterprise management",
    "业务流程功能": "business process functions",
    "印刷网络印刷平台评测": "Print Web-to-Print Platform Review",
    "与Pressero年对比": "and Pressero 2026 Comparison",
    "印刷网络印刷平台的商业模式与市场趋势": "Print Web-to-Print Platform Business Model and Market Trends",
    "网络印刷": "Web-to-Print",
    "是印刷企业的线上服务平台": "is print enterprise online service platform",
    "提供": "provides",
    "在线下单": "online ordering",
    "在线设计": "online design",
    "客户管理": "customer management",
    "网络印刷平台帮助印刷企业数字化转型": "Web-to-Print platform helps print enterprises digital transformation",
    "拓展线上渠道": "expand online channels",
    "提升客户自助服务能力": "improve customer self-service capability",
    "类似VistaPrint模式": "similar to VistaPrint model",
    "印刷企业可建立自有网络印刷平台": "print enterprises can build own Web-to-Print platform",
    "网络印刷趋势": "Web-to-Print trends",
    "自有平台": "Own platform",
    "印刷企业建立自有网络印刷平台": "print enterprises build own Web-to-Print platform",
    "在线设计": "Online design",
    "客户在线设计标准化产品": "customers online design standardized products",
    "自助下单": "Self-service ordering",
    "客户自助下单支付": "customers self-service ordering payment",
    "客户门户": "Customer portal",
    "企业客户门户集成": "enterprise customer portal integration",
    "年网络印刷平台呈现": "2026 Web-to-Print platform presents",
    "PrintNow性价比": "PrintNow cost-effective",
    "Pixopa功能完整": "Pixopa comprehensive features",
    "Pressero企业级": "Pressero enterprise-level",
    "三种方案": "three solutions",
    "PrintNow评测": "PrintNow Review",
    "性价比网络印刷平台": "Cost-effective Web-to-Print Platform",
    "PrintNow是性价比网络印刷平台": "PrintNow is cost-effective Web-to-Print platform",
    "定位": "positioning",
    "中小企业": "small-medium enterprises",
    "快速部署": "fast deployment",
    "核心功能": "Core functions",
    "客户在线选择产品": "customers online select products",
    "下单": "order",
    "在线设计编辑器": "online design editor",
    "名片": "business card",
    "宣传册模板": "brochure template",
    "报价计算": "Quoting calculation",
    "在线报价自动计算": "online quote auto-calculation",
    "文件上传": "File upload",
    "客户文件上传": "customer file upload",
    "支付集成": "Payment integration",
    "在线支付集成": "online payment integration",
    "模板库": "Template library",
    "预设设计模板": "preset design templates",
    "名片": "business cards",
    "宣传册": "brochures",
    "海报": "posters",
    "在线编辑": "Online editing",
    "拖拽编辑": "drag-and-drop editing",
    "文字修改": "text modification",
    "图像上传": "image upload",
    "设计保存": "Design saving",
    "设计保存复用": "design saving reuse",
    "报价引擎": "Quoting engine",
    "自动报价计算": "auto quote calculation",
    "支付集成": "Payment integration",
    "PayPal": "PayPal",
    "Stripe支付集成": "Stripe payment integration",
    "订单管理": "Order management",
    "订单管理与生产对接": "order management and production integration",
    "用户评价": "User evaluation",
    "中小印刷厂认为PrintNow部署便捷": "Small-medium print factories think PrintNow deployment convenient",
    "在线设计功能实用": "online design feature practical",
    "但复杂定制功能基础": "but complex customization features basic",
    "适合标准化产品": "suitable for standardized products",
    "PrintNow基础版": "PrintNow basic version",
    "月订阅": "monthly subscription",
    "PrintNow专业版": "PrintNow professional version",
    "Pixopa评测": "Pixopa Review",
    "功能完整网络印刷平台": "Comprehensive Web-to-Print Platform",
    "Pixopa是功能完整的网络印刷平台": "Pixopa is comprehensive Web-to-Print platform",
    "定位": "positioning",
    "在线设计完整": "online design comprehensive",
    "企业门户集成": "enterprise portal integration",
    "完整在线下单流程": "comprehensive online ordering process",
    "完整在线设计编辑器": "comprehensive online design editor",
    "企业客户门户集成": "enterprise customer portal integration",
    "MIS对接": "MIS integration",
    "与印刷MIS系统对接": "integrate with print MIS system",
    "品牌定制": "Brand customization",
    "平台品牌定制": "platform brand customization",
    "在线设计特色": "Online Design Features",
    "模板丰富": "Rich templates",
    "丰富设计模板库": "rich design template library",
    "编辑器强大": "Powerful editor",
    "完整编辑功能": "comprehensive editing features",
    "批量设计": "Batch design",
    "批量设计功能": "batch design features",
    "AI设计辅助": "AI design assistance",
    "AI设计辅助部分": "AI design assistance (partial)",
    "企业门户": "Enterprise portal",
    "企业客户专属门户": "enterprise customer exclusive portal",
    "审批流程": "Approval process",
    "企业审批流程": "enterprise approval process",
    "账期管理": "Account period management",
    "企业账期支付": "enterprise account period payment",
    "历史订单": "Historical orders",
    "企业历史订单管理": "enterprise historical order management",
    "EFI Pace对接": "EFI Pace integration",
    "与EFI Pace对接": "integrate with EFI Pace",
    "订单自动流转": "Order auto-flow",
    "平台订单自动流转MIS": "platform orders auto-flow to MIS",
    "进度同步": "Progress sync",
    "生产进度同步平台": "production progress sync to platform",
    "中型印刷厂认为Pixopa功能完整": "Medium print factories think Pixopa features comprehensive",
    "企业门户实用": "enterprise portal practical",
    "MIS对接便捷": "MIS integration convenient",
    "但价格较高": "but price high",
    "小型印刷厂成本考虑": "small print factories cost consideration",
    "Pixopa": "Pixopa",
    "月订阅": "monthly subscription",
    "MIS对接": "MIS integration",
    "对接费用": "integration fee",
    "Pressero评测": "Pressero Review",
    "企业级网络印刷平台": "Enterprise-level Web-to-Print Platform",
    "Pressero是企业级网络印刷平台": "Pressero is enterprise-level Web-to-Print platform",
    "定位": "positioning",
    "大型印刷企业": "large print enterprises",
    "企业客户服务": "enterprise customer service",
    "企业级下单流程": "enterprise-level ordering process",
    "企业级设计编辑器": "enterprise-level design editor",
    "完整企业客户门户": "comprehensive enterprise customer portal",
    "多级审批流程": "multi-level approval process",
    "完整品牌定制": "comprehensive brand customization",
    "企业门户特色": "Enterprise Portal Features",
    "多企业门户": "Multi-enterprise portals",
    "多企业客户独立门户": "multi-enterprise customer independent portals",
    "多级审批流程定制": "multi-level approval process customization",
    "权限管理": "Permission management",
    "企业客户权限管理": "enterprise customer permission management",
    "报表查询": "Report query",
    "企业报表查询": "enterprise report query",
    "多级审批": "Multi-level approval",
    "设计审批": "design approval",
    "预算审批": "budget approval",
    "下单审批": "order approval",
    "审批追踪": "Approval tracking",
    "审批进度追踪": "approval progress tracking",
    "审批记录": "Approval record",
    "审批历史记录": "approval historical record",
    "深度对接EFI Pace": "deep integration with EFI Pace",
    "完整订单自动流转": "comprehensive order auto-flow",
    "生产进度实时同步": "production progress real-time sync",
    "大型印刷企业认为Pressero企业级功能完整": "Large print enterprises think Pressero enterprise-level features comprehensive",
    "企业门户专业": "enterprise portal professional",
    "审批流程完整": "approval process comprehensive",
    "但价格高": "but price high",
    "中小企业门槛": "small-medium enterprises barrier",
    "Pressero": "Pressero",
    "企业门户定制": "enterprise portal customization",
    "网络印刷平台对比分析表": "Web-to-Print Platform Comparison Analysis Table",
    "对比维度": "Comparison dimension",
    "核心定位": "Core positioning",
    "性价比中小企业": "cost-effective small-medium enterprises",
    "功能完整": "comprehensive features",
    "企业级": "enterprise-level",
    "在线下单": "Online ordering",
    "基础": "basic",
    "完整": "comprehensive",
    "在线设计": "Online design",
    "基础编辑器": "basic editor",
    "完整编辑器": "comprehensive editor",
    "企业级编辑器": "enterprise-level editor",
    "模板库": "Template library",
    "丰富": "rich",
    "丰富定制": "rich + customization",
    "报价计算": "Quoting calculation",
    "复杂报价": "complex quoting",
    "支付集成": "Payment integration",
    "PayPal/Stripe": "PayPal/Stripe",
    "企业账期": "enterprise account period",
    "企业门户": "Enterprise portal",
    "无": "none",
    "有": "yes",
    "完整多门户": "comprehensive multi-portal",
    "审批流程": "Approval process",
    "基础": "basic",
    "多级审批": "multi-level approval",
    "MIS对接": "MIS integration",
    "EFI Pace": "EFI Pace",
    "深度对接": "deep integration",
    "品牌定制": "Brand customization",
    "深度定制": "deep customization",
    "移动端": "Mobile",
    "完整移动": "comprehensive mobile",
    "成本": "Cost",
    "月": "/month",
    "部署周期": "Deployment period",
    "周": "weeks",
    "个月": "months",
    "适用对象": "Suitable users",
    "中小印刷厂": "small-medium print factories",
    "中型印刷厂": "medium print factories",
    "大型印刷企业": "large print enterprises",
    "年网络印刷平台趋势预测": "2026 Web-to-Print Platform Trend Predictions",
    "AI在线设计": "AI Online Design",
    "AI在线设计辅助": "AI online design assistance",
    "AI推荐模板": "AI recommend templates",
    "AI生成设计": "AI generate design",
    "AI优化设计": "AI optimize design",
    "Pixopa已引入AI": "Pixopa has introduced AI",
    "企业门户深化": "Enterprise Portal Deepening",
    "企业客户门户深化": "enterprise customer portal deepening",
    "多企业门户": "multi-enterprise portals",
    "审批流程": "approval process",
    "企业账期管理成为标配": "enterprise account period management becomes standard",
    "Pressero领先": "Pressero leading",
    "MIS深度集成": "MIS Deep Integration",
    "网络印刷平台与MIS深度集成": "Web-to-Print platform and MIS deep integration",
    "订单自动流转": "order auto-flow",
    "进度实时同步": "progress real-time sync",
    "客户数据同步": "customer data sync",
    "移动优先": "Mobile First",
    "移动端网络印刷": "mobile Web-to-Print",
    "客户移动设计": "customer mobile design",
    "移动下单": "mobile ordering",
    "移动进度追踪": "mobile progress tracking",
    "平台品牌定制": "Platform Brand Customization",
    "印刷企业品牌定制网络印刷平台": "print enterprises brand customize Web-to-Print platform",
    "差异化竞争": "differentiated competition",
    "选型建议": "Selection recommendations",
    "中小企业快速上线": "Small-medium enterprises fast launch",
    "PrintNow性价比高": "PrintNow cost-effective",
    "部署便捷": "deployment convenient",
    "中型印刷厂功能完整": "Medium print factories comprehensive features",
    "Pixopa在线设计完整": "Pixopa online design comprehensive",
    "MIS对接便捷": "MIS integration convenient",
    "大型印刷企业客户服务": "Large print enterprises customer service",
    "Pressero企业级门户专业": "Pressero enterprise-level portal professional",
    "审批流程完整": "approval process comprehensive",
    "标准化产品为主": "Standardized products main",
    "PrintNow在线设计模板实用": "PrintNow online design templates practical",
    "企业客户审批需求": "Enterprise customer approval needs",
    "Pressero多级审批流程": "Pressero multi-level approval process",
    "网络印刷平台选型需考虑企业规模": "Web-to-Print platform selection needs to consider enterprise scale",
    "企业客户需求": "enterprise customer needs",
    "MIS集成需求": "MIS integration needs",
    "预算": "budget",
    "建议从PrintNow起步": "recommend start from PrintNow",
    "逐步升级Pixopa/Pressero": "gradually upgrade to Pixopa/Pressero",
    "深度评测年印刷网络印刷平台": "Deep review 2026 print Web-to-Print platform",
    "对比在线下单": "compare online ordering",
    "在线设计": "online design",
    "客户门户功能": "customer portal features",
    "为印刷企业建立自有印刷电商平台提供技术方案": "provide technical solution for print enterprises to build own e-commerce platform",
    "了解更多功能和价格对比": "Learn more about features and price comparison",
}

def translate_file(filepath):
    """Translate a single JSON file"""
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    # Translate title
    if 'title' in data:
        for chinese, english in TRANSLATIONS.items():
            data['title'] = data['title'].replace(chinese, english)
    
    # Translate description
    if 'description' in data:
        for chinese, english in TRANSLATIONS.items():
            data['description'] = data['description'].replace(chinese, english)
    
    # Translate content
    if 'content' in data:
        for chinese, english in TRANSLATIONS.items():
            data['content'] = data['content'].replace(chinese, english)
    
    # Translate seo_keywords
    if 'seo_keywords' in data and isinstance(data['seo_keywords'], list):
        translated_keywords = []
        for keyword in data['seo_keywords']:
            translated_keyword = keyword
            for chinese, english in TRANSLATIONS.items():
                translated_keyword = translated_keyword.replace(chinese, english)
            translated_keywords.append(translated_keyword)
        data['seo_keywords'] = translated_keywords
    
    # Translate author
    if 'author' in data:
        for chinese, english in TRANSLATIONS.items():
            data['author'] = data['author'].replace(chinese, english)
    
    # Write back
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    return filepath.name

# Process all files
directory = Path("/Users/gejiayu/owner/seo/data/print-graphic-design-tools")
files = sorted(directory.glob("*.json"))

success_count = 0
for filepath in files:
    try:
        result = translate_file(filepath)
        print(f"✓ {result}")
        success_count += 1
    except Exception as e:
        print(f"✗ {filepath.name}: {e}")

print(f"\nTranslation completed: {success_count}/100 files processed")
