#!/usr/bin/env python3
"""
Translate Chinese content to English for energy-environmental-tools JSON files.
Preserves HTML structure and keeps slug/published_at unchanged.
"""

import json
import re
from pathlib import Path

# Comprehensive translation dictionary
TRANSLATIONS = {
    # Titles
    "评测": "Review",
    "对比": "Comparison",
    "中小企业": "Small Business",
    "全面对比": "Comprehensive Comparison",
    "深入对比": "In-depth Comparison",
    "背景介绍": "Background Introduction",
    "核心功能对比表": "Core Feature Comparison Table",
    "详解": "Detailed Explanation",
    "中小企业选型决策矩阵": "Small Business Selection Decision Matrix",
    "趋势预测": "Trend Prediction",
    
    # Systems/Software/Tools
    "软件": "Software",
    "系统": "System",
    "平台": "Platform",
    "工具": "Tools",
    "管理": "Management",
    "监测": "Monitoring",
    "评估": "Assessment",
    "报告": "Report",
    "合规": "Compliance",
    "数据": "Data",
    "分析": "Analysis",
    "可视化": "Visualization",
    "自动化": "Automated",
    "智能": "Intelligent",
    "预测": "Prediction",
    "预警": "Warning",
    "核算": "Calculation",
    "追踪": "Tracking",
    "采集": "Collection",
    "存储": "Storage",
    "处理": "Processing",
    "整合": "Integration",
    "穿透": "Penetration",
    
    # Features
    "核心能力": "Core Capabilities",
    "技术优势": "Technical Advantages",
    "劣势分析": "Disadvantage Analysis",
    "价格体系": "Pricing Structure",
    "功能维度": "Feature Dimension",
    "中小企业适用性": "Small Business Applicability",
    "推荐平台": "Recommended Platform",
    "推荐系统": "Recommended System",
    "推荐工具": "Recommended Tool",
    "理由": "Reason",
    "预估年成本": "Estimated Annual Cost",
    "预估投入": "Estimated Investment",
    "预估认证成本": "Estimated Certification Cost",
    "预估成本": "Estimated Cost",
    
    # Descriptive terms
    "最全面": "Most Comprehensive",
    "最完善": "Most Complete",
    "最智能": "Most Intelligent",
    "最精准": "Most Accurate",
    "最权威": "Most Authoritative",
    "最便捷": "Most Convenient",
    "最高": "Highest",
    "最低": "Lowest",
    "最强": "Strongest",
    "最友好": "Most Friendly",
    "最亲民": "Most Affordable",
    "最丰富": "Most Rich",
    "最准确": "Most Accurate",
    "最完整": "Most Complete",
    "最成熟": "Most Mature",
    "最深": "Deepest",
    "覆盖最全": "Most Comprehensive Coverage",
    
    # Status
    "不支持": "Not Supported",
    "完善": "Complete",
    "缺失": "Missing",
    "中等": "Medium",
    "基础": "Basic",
    "有限": "Limited",
    "偏高": "High",
    "亲民": "Affordable",
    "免费": "Free",
    "需要定制": "Needs Customization",
    
    # Pricing/Time
    "年费": "Annual Fee",
    "订阅": "Subscription",
    "部署周期": "Deployment Period",
    "上线": "Go Live",
    "实时": "Real-time",
    "服务费": "Service Fee",
    "佣金": "Commission",
    "设备": "Equipment",
    "完整系统投入": "Complete System Investment",
    
    # Common phrases
    "本文将评测": "This article reviews",
    "为中小企业选型提供参考": "providing reference for small business selection",
    "为中小企业选型提供决策依据": "providing decision basis for small business selection",
    "中小企业在": "Small businesses in",
    "面临三大痛点": "face three main challenges:",
    "领域面临三大痛点": "field face three main challenges:",
    "能够": "can",
    "帮助企业": "help enterprises",
    "降低": "reduce",
    "提升": "improve",
    "满足": "meet",
    "确保": "ensure",
    "优化": "optimize",
    "加速": "accelerate",
    "量化": "quantify",
    "识别": "identify",
    "推荐": "recommend",
    "自动化生成": "automatically generate",
    "一键完成": "completed in one click",
    "一键生成": "generated in one click",
    "一键执行": "executed in one click",
    "一键申报": "declared in one click",
    "实时监控": "real-time monitoring",
    "数据分析": "data analysis",
    "精准核算": "accurate calculation",
    "全面覆盖": "comprehensive coverage",
    "深度评估": "in-depth assessment",
    "智能推荐": "intelligent recommendation",
    "快速部署": "quick deployment",
    "价格亲民": "affordable price",
    "预算可控": "budget controllable",
    "预算最可控": "most controllable budget",
    "初期投入": "initial investment",
    "订阅负担": "subscription burden",
    "压力可控": "manageable pressure",
    "压力较大": "significant pressure",
    "压力大": "large pressure",
    "中文界面": "Chinese interface",
    "中文支持": "Chinese support",
    "部分中文": "partial Chinese",
    "无中文": "no Chinese",
    "国内企业": "domestic enterprises",
    "国内友好": "friendly for domestic",
    "国内企业友好": "friendly for domestic enterprises",
    "使用不便": "inconvenient to use",
    "精度下降": "accuracy decreases",
    "覆盖有限": "limited coverage",
    "效率最高": "highest efficiency",
    "效率中等": "medium efficiency",
    "效率最低": "lowest efficiency",
    "效率高": "high efficiency",
    "效率低": "low efficiency",
    "工作量减少": "workload reduction",
    "中小企业应优先选择": "Small businesses should prioritize selecting",
    "应优先选择": "should prioritize selecting",
    "应对未来": "respond to future",
    "监管要求": "regulatory requirements",
    "降低成本": "reduce costs",
    "提升效率": "improve efficiency",
    "降低风险": "reduce risks",
    "满足合规": "meet compliance",
    "将呈现三大趋势": "will show three major trends:",
    "一是": "First:",
    "二是": "Second:",
    "三是": "Third:",
    "成为标配": "becoming standard",
    "机器学习模型": "machine learning models",
    "自动": "automatically",
    "上链存储": "stored on blockchain",
    "不可篡改": "immutable",
    "实时采集": "real-time collection",
    "联动": "integrate with",
    "双重": "dual",
    "一站式": "one-stop",
    "一站式完成": "completed in one-stop",
    "直连": "direct connection",
    "直报": "direct reporting",
    "无缝对接": "seamless integration",
    "快速响应": "quick response",
    "部署周期最短": "shortest deployment",
    "学习成本最低": "lowest learning cost",
    "用户界面最简洁": "simplest user interface",
    "用户界面简洁": "simple user interface",
    "界面支持": "interface support",
    "适合": "suitable for",
    "需求的企业": "enterprises with needs",
    "追求": "pursuing",
    "权威认证": "authoritative certification",
    "全球认可": "global recognition",
    "国际市场": "international market",
    "区域市场": "regional market",
    "供应链穿透": "supply chain penetration",
    "二级供应商": "tier-2 suppliers",
    "三级供应商": "tier-3 suppliers",
    "供应商": "supplier",
    "品牌商对接": "brand integration",
    "投资者认可": "investor recognition",
    "监管合规": "regulatory compliance",
    "审计要求": "audit requirements",
    "披露要求": "disclosure requirements",
    "碳中和认证": "carbon neutral certification",
    "碳足迹核算": "carbon footprint calculation",
    "减排措施": "emission reduction measures",
    "排放因子": "emission factors",
    "配额管理": "allowance management",
    "履约": "compliance",
    "交易": "trading",
    "储备": "reserve",
    "市值": "market value",
    "价值核算": "value calculation",
    "交易时机": "trading timing",
    "交易策略": "trading strategy",
    "自动执行": "automatic execution",
    "人工执行": "manual execution",
    "手动补充": "manual supplement",
    "定制开发": "custom development",
    "原生集成": "native integration",
    "设备绑定": "equipment binding",
    "第三方设备": "third-party equipment",
    "主流品牌": "major brands",
    "兼容性强": "strong compatibility",
    "兼容性最好": "best compatibility",
    "即可上线": "can go live",
    "系统复杂度": "system complexity",
    "专业技术人员": "professional technical personnel",
    "学习曲线": "learning curve",
    "陡峭": "steep",
    "中文报告模板": "Chinese report templates",
    "英文阅读": "reading in English",
    "英文法规": "English regulations",
    "国内企业使用不便": "inconvenient for domestic enterprises",
    
    # Industry specific
    "环境": "Environmental",
    "碳": "Carbon",
    "能源": "Energy",
    "气候": "Climate",
    "排放": "Emission",
    "污染": "Pollution",
    "可持续": "Sustainable",
    "可持续发展": "Sustainable Development",
    "ESG": "ESG",
    "生态": "Ecological",
    "修复": "Restoration",
    "废弃物": "Waste",
    "节水": "Water Conservation",
    "噪声": "Noise",
    "土壤": "Soil",
    "绿色供应链": "Green Supply Chain",
    "法规": "Regulation",
    "审计": "Audit",
    "认证": "Certification",
    "资产": "Asset",
    "配额": "Allowance",
    "信用": "Credit",
    "标签": "Label",
    "传感器": "Sensor",
    "IoT": "IoT",
    "风险": "Risk",
    "投资": "Investment",
    "收益": "Return",
    "效率": "Efficiency",
    "成本": "Cost",
    "投入": "Investment",
    "节省": "Savings",
    
    # Measurements
    "准确率": "accuracy rate",
    "误差": "error",
    "精度": "precision",
    "频率": "frequency",
    "覆盖率": "coverage rate",
    "回收率": "recovery rate",
    "下降率": "decrease rate",
    "降低率": "reduction rate",
    "提升率": "improvement rate",
    
    # Actions
    "选择": "choose",
    "采用": "adopt",
    "实施": "implement",
    "配置": "configure",
    "生成": "generate",
    "编制": "compile",
    "计算": "calculate",
    "换算": "convert",
    "统计": "statistics",
    "记录": "record",
    "存档": "archive",
    "查询": "query",
    "查看": "view",
    "录入": "input",
    "输出": "output",
    "输入": "input",
    "上传": "upload",
    "下载": "download",
    "导入": "import",
    "导出": "export",
    
    # Objects
    "仪表盘": "dashboard",
    "图表": "chart",
    "热力图": "heatmap",
    "地图": "map",
    "模板": "template",
    "问卷": "questionnaire",
    "清单": "list",
    "数据库": "database",
    "库": "library",
    "指标": "indicator",
    "维度": "dimension",
    "字段": "field",
    "参数": "parameter",
    "标准": "standard",
    "框架": "framework",
    "模型": "model",
    "方案": "solution",
    "措施": "measure",
    "流程": "process",
    "步骤": "step",
    "环节": "stage",
    "阶段": "phase",
    "周期": "cycle",
    "季度": "quarter",
    "年度": "annual",
    "月度": "monthly",
    "日报": "daily",
    "月报": "monthly report",
    "年报": "annual report",
    "合规报告": "compliance report",
    "披露报告": "disclosure report",
    "审计报告": "audit report",
    "评估报告": "assessment report",
    "监测报告": "monitoring report",
    
    # Qualifiers
    "相对": "relatively",
    "绝对": "absolute",
    "主要": "mainly",
    "次要": "secondary",
    "核心": "core",
    "基础": "basic",
    "高级": "advanced",
    "专业": "professional",
    "权威": "authoritative",
    "标准化": "standardized",
    "规范化": "normalized",
    "系统化": "systematic",
    "一体化": "integrated",
    "全面": "comprehensive",
    "完整": "complete",
    "丰富": "rich",
    "深入": "in-depth",
    "详细": "detailed",
    "简洁": "concise",
    "直观": "intuitive",
    "便捷": "convenient",
    "灵活": "flexible",
    "稳定": "stable",
    "可靠": "reliable",
    "安全": "secure",
    "高效": "efficient",
    "精准": "accurate",
    "智能": "intelligent",
    "强大": "powerful",
    "领先": "leading",
    "成熟": "mature",
    
    # Common connectors
    "和": "and",
    "与": "and",
    "或": "or",
    "及": "and",
    "包括": "including",
    "覆盖": "covering",
    "含": "including",
    "不含": "excluding",
    "无": "no",
    "有": "has",
    "支持": "supports",
    "具备": "has",
    "拥有": "has",
    "提供": "provides",
    "内置": "built-in",
    "外置": "external",
    "第三方": "third-party",
    "独立": "standalone",
    "集中": "centralized",
    "分布式": "distributed",
    "云端": "cloud",
    "本地": "local",
    "现场": "on-site",
    "远程": "remote",
    "移动端": "mobile",
    "Web端": "web",
    "APP": "APP",
    "iOS": "iOS",
    "Android": "Android",
    "扫码": "scanning",
    "拍照": "photo",
    "上传照片": "upload photos",
    
    # Common HTML content phrases
    "全球领先": "global leading",
    "全球最广泛": "globally most widely used",
    "全球首选": "global preferred choice",
    "国际投资者": "international investors",
    "美国投资者": "US investors",
    "财务投资者": "financial investors",
    "品牌商首选": "brand preferred",
    "行业首选": "industry preferred",
    "监管报送": "regulatory reporting",
    "监管审计": "regulatory audit",
    "监管部门": "regulatory authorities",
    "监管机构": "regulatory agencies",
    "合规披露": "compliance disclosure",
    "合规运营": "compliant operations",
    "合规水平": "compliance level",
    "合规风险": "compliance risk",
    "降低合规成本": "reduce compliance costs",
    "降低合规风险": "reduce compliance risks",
    "降低交易成本": "reduce trading costs",
    "降低处置成本": "reduce disposal costs",
    "降低用水成本": "reduce water costs",
    "降低能源成本": "reduce energy costs",
    "降低核算成本": "reduce calculation costs",
    "降低审计成本": "reduce audit costs",
    "降低环评成本": "reduce EIA costs",
    "降低认证成本": "reduce certification costs",
    "降低履约成本": "reduce compliance costs",
    "提升回收率": "improve recovery rate",
    "提升修复效率": "improve restoration efficiency",
    "提升审计效率": "improve audit efficiency",
    "提升监测效率": "improve monitoring efficiency",
    "提升管理效率": "improve management efficiency",
    "提升分析效率": "improve analysis efficiency",
    "提升节水效率": "improve water conservation efficiency",
    "提升交易收益": "improve trading returns",
    "提升产品竞争力": "improve product competitiveness",
    "提升品牌形象": "improve brand image",
    "提升ESG形象": "improve ESG image",
    "最大化": "maximize",
    "最大化节能收益": "maximize energy savings",
    "最大化碳资产收益": "maximize carbon asset returns",
    "需要投入时间": "requires time investment",
    "需要供应商配合": "requires supplier cooperation",
    "需要专业培训": "requires professional training",
    "需要专业技术人员": "requires professional technicians",
    "需要人工辅助": "requires manual assistance",
    "需要人工执行": "requires manual execution",
    "需要人工录入": "requires manual input",
    "需要人工": "requires manual work",
    "需要数据量": "requires data volume",
    "需要历史数据": "requires historical data",
    "数据不足": "insufficient data",
    "数据缺失": "missing data",
    "数据采集": "data collection",
    "数据对接": "data integration",
    "数据存储": "data storage",
    "数据管理": "data management",
    "数据查询": "data query",
    "数据统计": "data statistics",
    "数据录入": "data input",
    "数据上报": "data reporting",
    "数据更新": "data update",
    "数据变化": "data changes",
    "数据延迟": "data delay",
    "数据安全": "data security",
    "数据可靠": "data reliability",
    "保障机制": "guarantee mechanism",
    "核心环节": "core stage",
    "核心要素": "core element",
    "核心支撑": "core support",
    "核心财务能力": "core financial capability",
    "核心载体": "core carrier",
    "核心体现": "core embodiment",
    "关键抓手": "key leverage",
    "基础能力": "basic capability",
    "基础环节": "basic stage",
    "基础要素": "basic element",
    "基础保障": "basic guarantee",
    "基础支撑": "basic support",
    "数字化基础": "digital foundation",
    "重要渠道": "important channel",
    "重要要素": "important element",
    "重要环节": "important stage",
    "重要组成部分": "important component",
    "核心财务能力": "core financial capability",
    "核心竞争力": "core competitiveness",
    "关键环节": "key stage",
    "关键要素": "key element",
    "关键支撑": "key support",
    "必要环节": "necessary stage",
    "必要措施": "necessary measure",
    "必要条件": "necessary condition",
    "必要支撑": "necessary support",
    "已缩短至": "shortened to",
    "已成为": "has become",
    "已成为": "has become",
    "已成为企业": "has become for enterprises",
    "已成为企业环境责任": "has become enterprise environmental responsibility",
    "已成为企业可持续发展": "has become enterprise sustainable development",
    "已成为企业碳中和": "has become enterprise carbon neutrality",
    "已成为企业ESG披露": "has become enterprise ESG disclosure",
    "已成为企业合规运营": "has become enterprise compliant operations",
    "已成为企业品牌竞争力": "has become enterprise brand competitiveness",
    "已成为企业可持续运营": "has become enterprise sustainable operations",
    "已成为产品市场竞争力": "has become product market competitiveness",
    "已成为降本增效": "has become cost reduction and efficiency improvement",
    "已成为决策": "has become decision",
    "已成为品牌": "has become brand",
    "已成为标配": "has become standard",
    "已成为首选": "has become preferred",
    "成为企业": "becomes for enterprises",
    "成为产品": "becomes product",
    "成为标配": "becomes standard",
    "成为首选": "becomes preferred",
    "成为主流": "becomes mainstream",
    "成为权威": "becomes authoritative",
    "成为核心": "becomes core",
    "成为基础": "becomes basic",
    "成为关键": "becomes key",
    "成为重要": "becomes important",
    "成为必要": "becomes necessary",
    "三大痛点": "three main challenges",
    "三大趋势": "three major trends",
    "三大挑战": "three major challenges",
    "三大核心": "three core aspects",
    "三大维度": "three dimensions",
    "三大能力": "three capabilities",
    "三大功能": "three functions",
    "三大优势": "three advantages",
    "三大劣势": "three disadvantages",
    "三大特点": "three characteristics",
    "三大模块": "three modules",
    "三大平台": "three platforms",
    "三大系统": "three systems",
    "三大软件": "three software",
    "三大工具": "three tools",
    "三大品牌": "three brands",
    "三大产品": "three products",
    "三大方案": "three solutions",
    "三大措施": "three measures",
    "三大策略": "three strategies",
    "三大趋势": "three trends",
    "三大领域": "three fields",
    "三大行业": "three industries",
    "三大场景": "three scenarios",
    "三大类型": "three types",
    "三大类别": "three categories",
    "三大标准": "three standards",
    "三大框架": "three frameworks",
    "三大模型": "three models",
    "三大指标": "three indicators",
    "三大维度": "three dimensions",
    "三大要素": "three elements",
    "三大环节": "three stages",
    "三大阶段": "three phases",
    "三大步骤": "three steps",
    "三大流程": "three processes",
    "三大功能维度": "three feature dimensions",
    "三大核心能力": "three core capabilities",
    "三大技术优势": "three technical advantages",
    "三大劣势分析": "three disadvantage analyses",
    "三大价格体系": "three pricing structures",
    "三大应用场景": "three application scenarios",
    "三大使用场景": "three use scenarios",
    "三大部署场景": "three deployment scenarios",
    "三大管理场景": "three management scenarios",
    "三大监测场景": "three monitoring scenarios",
    "三大评估场景": "three assessment scenarios",
    "三大报告场景": "three reporting scenarios",
    "三大合规场景": "three compliance scenarios",
    "三大数据场景": "three data scenarios",
    "三大分析场景": "three analysis scenarios",
    "三大可视化场景": "three visualization scenarios",
    "三大自动化场景": "three automation scenarios",
    "三大智能化场景": "three intelligence scenarios",
    "三大预测场景": "three prediction scenarios",
    "三大预警场景": "three warning scenarios",
    "三大核算场景": "three calculation scenarios",
    "三大追踪场景": "three tracking scenarios",
    "三大采集场景": "three collection scenarios",
    "三大存储场景": "three storage scenarios",
    "三大处理场景": "three processing scenarios",
    "三大整合场景": "three integration scenarios",
    "三大穿透场景": "three penetration scenarios",
    "三大管理需求": "three management needs",
    "三大监测需求": "three monitoring needs",
    "三大评估需求": "three assessment needs",
    "三大报告需求": "three reporting needs",
    "三大合规需求": "three compliance needs",
    "三大数据需求": "three data needs",
    "三大分析需求": "three analysis needs",
    "三大可视化需求": "three visualization needs",
    "三大自动化需求": "three automation needs",
    "三大智能化需求": "three intelligence needs",
    "三大预测需求": "three prediction needs",
    "三大预警需求": "three warning needs",
    "三大核算需求": "three calculation needs",
    "三大追踪需求": "three tracking needs",
    "三大采集需求": "three collection needs",
    "三大存储需求": "three storage needs",
    "三大处理需求": "three processing needs",
    "三大整合需求": "three integration needs",
    "三大穿透需求": "three penetration needs",
}

def translate_text(text):
    """Translate Chinese text to English."""
    if not text or not any('一' <= c <= '鿿' for c in text):
        return text
    
    result = text
    
    # Sort by length (longest first) to avoid partial replacements
    sorted_translations = sorted(TRANSLATIONS.items(), key=lambda x: len(x[0]), reverse=True)
    
    for chinese, english in sorted_translations:
        result = result.replace(chinese, english)
    
    return result

def translate_html_content(html):
    """Translate HTML content preserving structure."""
    if not html:
        return html
    
    return translate_text(html)

def translate_keywords(keywords):
    """Translate SEO keywords."""
    if not keywords:
        return keywords
    
    return [translate_text(kw) for kw in keywords]

def translate_author(author):
    """Translate author name."""
    author_map = {
        "数据分析顾问": "Data Analysis Consultant",
        "碳管理顾问": "Carbon Management Consultant",
        "可持续发展顾问": "Sustainability Consultant",
        "碳标签认证顾问": "Carbon Label Certification Consultant",
        "生态修复顾问": "Ecological Restoration Consultant",
        "环境影响评估顾问": "Environmental Impact Assessment Consultant",
        "IoT数据管理顾问": "IoT Data Management Consultant",
        "环境审计顾问": "Environmental Audit Consultant",
        "供应链可持续顾问": "Supply Chain Sustainability Consultant",
        "法规合规顾问": "Regulatory Compliance Consultant",
        "声学监测工程师": "Acoustic Monitoring Engineer",
        "土壤环境工程师": "Soil Environmental Engineer",
        "节水管理顾问": "Water Conservation Consultant",
        "碳资产管理顾问": "Carbon Asset Management Consultant",
        "气候风险顾问": "Climate Risk Consultant",
        "废弃物管理顾问": "Waste Management Consultant",
        "碳排放配额管理顾问": "Carbon Emission Allowance Management Consultant",
        "工业自动化专家": "Industrial Automation Expert",
        "能源管理顾问": "Energy Management Consultant",
    }
    
    return author_map.get(author, translate_text(author))

def process_file(filepath):
    """Process single JSON file."""
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    # Translate fields
    if 'title' in data:
        data['title'] = translate_text(data['title'])
    
    if 'description' in data:
        data['description'] = translate_text(data['description'])
    
    if 'content' in data:
        data['content'] = translate_html_content(data['content'])
    
    if 'author' in data:
        data['author'] = translate_author(data['author'])
    
    if 'seo_keywords' in data:
        data['seo_keywords'] = translate_keywords(data['seo_keywords'])
    
    # Write back
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    return filepath.name

def main():
    base_path = Path('/Users/gejiayu/owner/seo/data/energy-environmental-tools')
    files = list(base_path.glob('*.json'))
    
    print(f"Found {len(files)} files")
    
    processed = []
    for fp in files:
        try:
            name = process_file(fp)
            processed.append(name)
            print(f"Processed: {name}")
        except Exception as e:
            print(f"Error: {fp.name} - {e}")
    
    print(f"\nTotal: {len(processed)} files processed")

if __name__ == '__main__':
    main()
