#!/usr/bin/env python3
"""
Script to translate Chinese JSON files in sports-recreation-management to natural English.
"""

import json
import os
import re

# Translation mappings for common terms
TRANSLATIONS = {
    # Common patterns in titles
    "全面评测": "Comprehensive Review",
    "深度评测": "Deep Review",
    "深度分析": "Deep Analysis",
    "最佳解决方案": "Best Solutions",
    "数字化解决方案": "Digital Solutions",
    "|": "|",
    "｜2026年评测": "| 2026 Review",
    "｜": "|",

    # Common phrases in descriptions
    "深入了解": "In-depth review of",
    "全面评测": "Comprehensive review of",
    "涵盖": "covering",
    "为": "for",
    "提供": "provides",
    "科学的": "scientific",
    "专业的": "professional",
    "选型指南": "selection guidance",
    "了解更多功能和价格对比": "Compare features and pricing",
    "找到最适合你的方案": "to find the best solution",
    "专业评测助你决策": "Expert reviews to guide your decision!",

    # Content sections
    "背景介绍": "Background Introduction",
    "深度评测": "In-depth Review",
    "深度分析": "Deep Analysis",
    "参数对比表": "Parameter Comparison Table",
    "核心功能分析": "Core Function Analysis",
    "未来发展趋势预测": "Future Development Trend Prediction",

    # Common content terms
    "是": "is",
    "核心": "core",
    "工具": "tool",
    "平台": "platform",
    "系统": "system",
    "软件": "software",
    "功能": "function",
    "模块": "module",
    "管理": "management",
    "运营": "operations",
    "效率": "efficiency",
    "体验": "experience",
    "能力": "capabilities",
    "设计": "design",
    "方案": "solution",
    "流程": "process",
    "数据": "data",
    "分析": "analysis",
    "报表": "reports",
    "统计": "statistics",
    "智能化": "intelligence",
    "自动化": "automation",
    "数字化": "digital",
    "专业化": "professional",
    "传统": "traditional",
    "现代": "modern",
    "大型": "large",
    "中型": "medium",
    "小型": "small",
    "完整": "complete",
    "基础": "basic",
    "标准": "standard",
    "高级": "advanced",
    "专业": "professional",
    "优秀": "excellent",
    "详细": "detailed",
    "深度": "deep",
    "全面": "comprehensive",
    "丰富": "rich",
    "灵活": "flexible",
    "简洁": "simple",
    "直观": "intuitive",
    "便捷": "convenient",
    "快速": "fast",
    "高效": "efficient",
    "精准": "precise",
    "精细": "refined",
    "实时": "real-time",
    "自动": "automatic",
    "智能": "intelligent",
    "预测": "predictive",
    "预防": "preventive",
    "科学": "scientific",
    "易用": "easy-to-use",
    "月度价格": "Monthly Price",
    "年度价格": "Annual Price",
    "订阅": "subscription",
    "购买": "purchase",
    "价格策略": "pricing strategy",
    "亲民": "affordable",
    "预算有限": "budget-constrained",
    "适合": "suitable for",
    "服务": "serves",
    "众多": "numerous",
    "广泛使用": "widely used",
    "行业": "industry",
    "领域": "field",
    "标杆产品": "benchmark product",
    "领先": "leading",
    "特色优势": "distinctive advantage",
    "核心优势": "core advantage",
    "优势": "advantage",
    "整合": "integrates",
    "支持": "supports",
    "提供": "provides",
    "包括": "including",
    "涵盖": "covering",
    "用户": "users",
    "管理者": "managers",
    "运营团队": "operations team",
    "管理层": "management",
    "员工": "employees",
    "帮助": "helping",
    "提升": "improving",
    "降低": "reducing",
    "增加": "increasing",
    "减少": "reducing",
    "扩大": "expanding",
    "优化": "optimizing",
    "增强": "enhancing",
    "直接影响": "directly impacts",
    "技术": "technology",
    "算法": "algorithm",
    "设备": "equipment",
    "设施": "facility",
    "器材": "equipment",
    "场地": "venue/field",
    "场馆": "venue",
    "俱乐部": "club",
    "联盟": "league",
    "协会": "association",
    "组织": "organization",
    "赛事": "event/tournament",
    "比赛": "competition/match",
    "活动": "activity",
    "培训": "training",
    "课程": "class/course",
    "会员": "member",
    "粉丝": "fan",
    "观众": "audience",
    "参与者": "participant",
    "运动员": "athlete",
    "教练": "coach",
    "裁判": "referee",
    "选手": "player",
    "报名": "registration",
    "预订": "booking",
    "预约": "reservation",
    "入场": "entry",
    "票务": "ticketing",
    "门票": "tickets",
    "座位": "seats",
    "收入": "revenue",
    "财务": "financial",
    "收益": "profitability",
    "盈利": "profitability",
    "成本": "cost",
    "资产": "assets",
    "库存": "inventory",
    "维护": "maintenance",
    "保养": "care/maintenance",
    "维修": "repair",
    "检测": "inspection",
    "预警": "warning/alert",
    "风险": "risk",
    "安全": "safety",
    "合规": "compliance",
    "质量": "quality",
    "状态": "status",
    "记录": "records",
    "档案": "archives",
    "历史": "history",
    "未来": "future",
    "发展": "development",
    "趋势": "trends",
    "预测": "prediction",
    "方向": "direction",
    "阶段": "stage",
    "水平": "level",
    "程度": "degree",
    "规模": "scale",
    "价值": "value",
    "影响": "impact",
    "挑战": "challenges",
    "需求": "needs",
    "问题": "issues",
    "解决方案": "solutions",
    "策略": "strategies",
    "计划": "plans",
    "目标": "goals",
    "应用": "applications",
    "移动应用": "mobile app",
    "网页": "web",
    "云端": "cloud",
    "物联网": "IoT",
    "人工智能": "AI",
    "机器学习": "machine learning",
    "区块链": "blockchain",
    "虚拟现实": "VR",
    "增强现实": "AR",
    "元宇宙": "metaverse",
    "传感器": "sensors",
    "硬件": "hardware",
    "设备对接": "device integration",
    "数据共享": "data sharing",
    "互联互通": "interconnectivity",
    "生态系统": "ecosystem",
    "生态": "ecosystem",
    "社交": "social",
    "互动": "interactive",
    "参与": "engagement",
    "忠诚度": "loyalty",
    "粘性": "stickiness",
    "画像": "profiling",
    "推荐": "recommendations",
    "个性化": "personalized",
    "定制": "customized",
    "品牌": "brand",
    "营销": "marketing",
    "推广": "promotion",
    "社交媒体": "social media",
    "内容": "content",
    "发布": "publishing",
    "传播": "dissemination",
    "影响力": "influence",
    "曝光": "exposure",
    "拓展": "expand",
    "资源": "resources",
    "配置": "configuration",
    "分配": "allocation",
    "调度": "scheduling",
    "排赛": "scheduling",
    "编排": "arrangement",
    "生成": "generation",
    "导出": "export",
    "导入": "import",
    "对接": "integration",
    "无缝": "seamless",
    "集成": "integration",
    "连接": "connection",
    "共享": "sharing",
    "协作": "collaboration",
    "远程": "remote",
    "线上": "online",
    "线下": "offline",
    "混合": "hybrid",
    "虚拟": "virtual",
    "沉浸式": "immersive",
    "实时": "real-time",
    "同步": "sync",
    "异步": "async",
    "即时": "instant",
    "并发": "concurrent",
    "处理": "processing",
    "计算": "calculation",
    "统计": "statistics",
    "排名": "ranking",
    "积分": "points",
    "证书": "certificates",
    "成绩": "scores/results",
    "表现": "performance",
    "技能": "skills",
    "体能": "fitness",
    "战术": "tactics",
    "训练": "training",
    "指导": "guidance",
    "建议": "recommendations",
    "策略": "strategies",
    "方法": "methods",
    "手段": "means",
    "措施": "measures",
    "标准配置": "standard configuration",
    "新阶段": "new stage",
    "新趋势": "new trend",
    "将成为": "will become",
    "将继续": "will continue",
    "将更加": "will become more",
    "将实现": "will achieve",
    "将提供": "will provide",
    "将被": "will be",
    "可能被": "may be",
    "将进一步": "will further",
    "将持续": "will continue",
    "已无法": "cannot",
    "无法": "cannot",
    "不能够": "cannot",
    "能够": "can",
    "可以": "can",
    "需要": "need",
    "要求": "require",
    "面向": "for",
    "针对": "for",
    "专为": "specifically for",
    "设计": "designed",
    "开发": "developed",
    "构建": "building",
    "实现": "achieving",
    "达到": "achieving",
    "满足": "meet",
    "应对": "handle",
    "解决": "solve",
    "处理": "handle",
    "完成": "complete",
    "执行": "execute",
    "实施": "implement",
    "部署": "deploy",
    "配置": "configure",
    "建立": "establish",
    "创建": "create",
    "生成": "generate",
    "制作": "make",
    "发送": "send",
    "接收": "receive",
    "显示": "display",
    "展示": "showcase",
    "呈现": "present",
    "提供": "provide",
    "输出": "output",
    "输入": "input",
    "更新": "update",
    "删除": "delete",
    "添加": "add",
    "修改": "modify",
    "调整": "adjust",
    "优化": "optimize",
    "改进": "improve",
    "升级": "upgrade",
    "扩展": "extend",
    "增强": "enhance",
    "强化": "strengthen",
    "深入": "deep",
    "全面": "comprehensive",
    "系统化": "systematic",
    "一体化": "integrated",
    "全程": "full-process",
    "全流程": "full-process",
    "端到端": "end-to-end",
    "一站式": "one-stop",
    "全方位": "all-around",
    "多层次": "multi-level",
    "多维度": "multi-dimensional",
    "多场景": "multi-scenario",
    "多功能": "multi-function",
    "多平台": "multi-platform",
    "多设备": "multi-device",
    "多用户": "multi-user",
    "多租户": "multi-tenant",
    "多语言": "multi-language",
    "多渠道": "multi-channel",
    "多形式": "multi-form",
    "多类型": "multi-type",
    "多阶段": "multi-stage",
    "多步骤": "multi-step",
    "多环节": "multi-link",
    "多方面": "multi-aspect",
    "多角度": "multi-angle",
    "多视角": "multi-perspective",
    "多来源": "multi-source",
    "多目标": "multi-goal",
    "多任务": "multi-task",
    "多线程": "multi-thread",
    "多进程": "multi-process",
    "多实例": "multi-instance",
    "多版本": "multi-version",
    "多模式": "multi-mode",
    "多选项": "multi-option",
    "多配置": "multi-config",
    "多参数": "multi-param",
    "多指标": "multi-metric",
    "多数据": "multi-data",
    "多信息": "multi-info",
    "多内容": "multi-content",
    "多元素": "multi-element",
    "多组件": "multi-component",
    "多模块": "multi-module",
    "多系统": "multi-system",
    "多应用": "multi-app",
    "多服务": "multi-service",
    "多接口": "multi-interface",
    "多端口": "multi-port",
    "多协议": "multi-protocol",
    "多格式": "multi-format",
    "多编码": "multi-codec",
    "多标准": "multi-standard",
    "多规范": "multi-spec",
    "多认证": "multi-cert",
    "多授权": "multi-auth",
    "多加密": "multi-encrypt",
    "多解密": "multi-decrypt",
    "多备份": "multi-backup",
    "多恢复": "multi-restore",
    "多迁移": "multi-migrate",
    "多同步": "multi-sync",
    "多异步": "multi-async",
    "多并发": "multi-concurrent",
    "多顺序": "multi-sequential",
    "多循环": "multi-loop",
    "多条件": "multi-condition",
    "多判断": "multi-judge",
    "多选择": "multi-choice",
    "多分支": "multi-branch",
    "多路径": "multi-path",
    "多节点": "multi-node",
    "多层级": "multi-tier",
    "多结构": "multi-structure",
    "多架构": "multi-arch",
    "多框架": "multi-framework",
    "多库": "multi-lib",
    "多包": "multi-package",
    "多插件": "multi-plugin",
    "多扩展": "multi-extension",
    "多主题": "multi-theme",
    "多样式": "multi-style",
    "多布局": "multi-layout",
    "多界面": "multi-interface",
    "多页面": "multi-page",
    "多视图": "multi-view",
    "多窗口": "multi-window",
    "多标签": "multi-tab",
    "多菜单": "multi-menu",
    "多按钮": "multi-button",
    "多输入": "multi-input",
    "多输出": "multi-output",
    "多显示": "multi-display",
    "多隐藏": "multi-hide",
    "多启用": "multi-enable",
    "多禁用": "multi-disable",
    "多激活": "multi-activate",
    "多冻结": "multi-freeze",
    "多锁定": "multi-lock",
    "多解锁": "multi-unlock",
    "多绑定": "multi-bind",
    "多解绑": "multi-unbind",
    "多关联": "multi-associate",
    "多解耦": "multi-decouple",
    "多聚合": "multi-aggregate",
    "多分散": "multi-disperse",
    "多集中": "multi-centralize",
    "多分布": "multi-distribute",
    "多本地": "multi-local",
    "多远程": "multi-remote",
    "多内网": "multi-intranet",
    "多外网": "multi-internet",
    "多私有": "multi-private",
    "多公有": "multi-public",
    "多混合": "multi-hybrid",
    "多独享": "multi-exclusive",
    "多共享": "multi-shared",
    "多协作": "multi-collab",
    "多竞争": "multi-competitive",
    "多合作": "multi-cooperative",
    "多联盟": "multi-league",
    "多团队": "multi-team",
    "多小组": "multi-group",
    "多部门": "multi-department",
    "多组织": "multi-organization",
    "多公司": "multi-company",
    "多企业": "multi-enterprise",
    "多机构": "multi-institution",
    "多单位": "multi-unit",
    "多场所": "multi-location",
    "多地点": "multi-site",
    "多区域": "multi-region",
    "多范围": "multi-range",
    "多领域": "multi-field",
    "多行业": "multi-industry",
    "多市场": "multi-market",
    "多用户群": "multi-user-group",
    "多客户群": "multi-customer-group",
    "多受众": "multi-audience",
    "多群体": "multi-community",
    "多人群": "multi-demographic",
}

def translate_file(filepath):
    """Translate a single JSON file from Chinese to English."""
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)

    # Translate title
    if 'title' in data and contains_chinese(data['title']):
        data['title'] = translate_text(data['title'])

    # Translate description
    if 'description' in data and contains_chinese(data['description']):
        data['description'] = translate_text(data['description'])

    # Translate content
    if 'content' in data and contains_chinese(data['content']):
        data['content'] = translate_content(data['content'])

    # Translate seo_keywords
    if 'seo_keywords' in data:
        data['seo_keywords'] = [translate_keyword(k) for k in data['seo_keywords']]

    # Translate author if needed
    if 'author' in data and contains_chinese(data['author']):
        data['author'] = translate_text(data['author'])

    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"Translated: {filepath}")

def contains_chinese(text):
    """Check if text contains Chinese characters."""
    return bool(re.search('[一-鿿]', text))

def translate_text(text):
    """Translate text using the translation dictionary."""
    result = text
    for chinese, english in TRANSLATIONS.items():
        result = result.replace(chinese, english)
    return result

def translate_content(content):
    """Translate HTML content."""
    # Translate headings
    content = re.sub(r'<h1>([^<]+)</h1>', lambda m: f'<h1>{translate_text(m.group(1))}</h1>', content)
    content = re.sub(r'<h2>([^<]+)</h2>', lambda m: f'<h2>{translate_text(m.group(1))}</h2>', content)
    content = re.sub(r'<h3>([^<]+)</h3>', lambda m: f'<h3>{translate_text(m.group(1))}</h3>', content)

    # Translate table headers and cells
    content = re.sub(r'<th>([^<]+)</th>', lambda m: f'<th>{translate_text(m.group(1))}</th>', content)
    content = re.sub(r'<td>([^<]+)</td>', lambda m: f'<td>{translate_text(m.group(1))}</td>', content)

    # Translate paragraphs
    content = re.sub(r'<p>([^<]+)</p>', lambda m: f'<p>{translate_text(m.group(1))}</p>', content)

    return content

def translate_keyword(keyword):
    """Translate a single keyword."""
    if contains_chinese(keyword):
        return translate_text(keyword)
    return keyword

def main():
    directory = '/Users/gejiayu/owner/seo/data/sports-recreation-management'

    # Find all files with Chinese content
    files_with_chinese = []
    for filename in os.listdir(directory):
        if filename.endswith('.json'):
            filepath = os.path.join(directory, filename)
            with open(filepath, 'r', encoding='utf-8') as f:
                content = f.read()
                if re.search('[一-鿿]', content):
                    files_with_chinese.append(filepath)

    print(f"Found {len(files_with_chinese)} files with Chinese content")

    # Translate each file
    for filepath in files_with_chinese:
        translate_file(filepath)

    print(f"Translated {len(files_with_chinese)} files")

if __name__ == '__main__':
    main()