#!/usr/bin/env python3
import json
import os

# Semantic translation mappings for medical equipment rental domain
MEDICAL_RENTAL_VOCAB = {
    # Core terms
    "医疗设备租赁": "Medical Equipment Rental",
    "合规管理": "Compliance Management",
    "系统评测": "System Review",
    "认证追踪": "Certification Tracking",
    "安全检查": "Safety Inspection",
    "FDA认证": "FDA Certification",
    "CE认证": "CE Certification",
    "ISO质量认证": "ISO Quality Certification",
    "有效期追踪": "Validity Period Tracking",
    "过期提醒": "Expiration Reminder",
    "消毒合规": "Disinfection Compliance",
    "召回管理": "Recall Management",
    "检查计划": "Inspection Plan",
    "检查记录": "Inspection Record",
    "整改追踪": "Rectification Tracking",
    "认证类型": "Certification Type",
    "认证范围": "Certification Scope",
    "技术文档": "Technical Documentation",
    "公告机构": "Notified Body",
    "年度审核": "Annual Audit",
    "检查项目": "Inspection Items",
    "电气安全": "Electrical Safety",
    "机械安全": "Mechanical Safety",
    "辐射安全": "Radiation Safety",
    "不合格设备": "Non-compliant Equipment",
    "消毒标准": "Disinfection Standard",
    "高温消毒": "High-temperature Disinfection",
    "化学消毒": "Chemical Disinfection",
    "紫外线消毒": "UV Disinfection",
    "消毒验证": "Disinfection Verification",
    "租赁前消毒": "Pre-rental Disinfection",
    "租赁后消毒": "Post-rental Disinfection",
    "深度评测": "In-depth Review",
    "产品对比表": "Product Comparison Table",
    "定价策略": "Pricing Strategy",
    "基础版": "Basic Version",
    "专业版": "Professional Version",
    "云端部署": "Cloud Deployment",
    "自动生成": "Automatic Generation",
    "实时更新": "Real-time Update",
    "移动端APP": "Mobile App",
    "现场检查录入": "On-site Inspection Entry",
    "合规报告": "Compliance Report",
    "监管要求": "Regulatory Requirements",
    "合规风险": "Compliance Risk",
    "客户信任": "Customer Trust",
    "法律责任": "Legal Liability",
    "停租": "Rental Suspension",
    "罚款": "Fines",
    "客户投诉": "Customer Complaints",
    "数字化": "Digitalization",
    "流程化": "Process Standardization",
    "自动化": "Automation",
    "降低风险": "Risk Reduction",
    "提升信任": "Trust Enhancement",
    "确保安全": "Safety Assurance",
    "核心要素": "Core Elements",
    "解析": "Analysis",
    "美国市场": "US Market",
    "欧洲市场": "European Market",
    "中国市场": "Chinese Market",
    "必备证书": "Essential Certificate",
    "准入": "Market Access",
    "有效期": "Validity Period",
    "续期": "Renewal",
    "到期前": "Before Expiration",
    "自动提醒": "Automatic Reminder",
    "设备型号": "Equipment Model",
    "功能": "Functionality",
    "用途": "Usage",
    "覆盖": "Covering",
    "设计": "Design",
    "生产": "Production",
    "维护": "Maintenance",
    "全过程": "Full Process",
    "审核报告": "Audit Report",
    "存储": "Storage",
    "周期设定": "Period Setting",
    "月度": "Monthly",
    "季度": "Quarterly",
    "年度": "Annual",
    "项目清单": "Item List",
    "结果记录": "Result Recording",
    "预警": "Warning",
    "完成后": "After Completion",
    "恢复租赁": "Resume Rental",
    "防止交叉感染": "Prevent Cross-infection",
    "关键": "Key",
    "消毒时间": "Disinfection Time",
    "消毒剂": "Disinfectant",
    "消毒人员": "Disinfection Personnel",
    "禁止租赁": "Rental Prohibition",
    "主流": "Mainstream",
    "产品": "Product",
    "专业": "Professional",
    "套件": "Suite",
    "全流程": "Full Process",
    "专注": "Focus",
    "适合": "Suitable",
    "对接": "Integration",
    "状态": "Status",
    "法规": "Regulations",
    "数据库": "Database",
    "版本追踪": "Version Tracking",
    "信息管理": "Information Management",
    "任务分配": "Task Allocation",
    "人员管理": "Personnel Management",
    "流程管理": "Process Management",
    "对比维度": "Comparison Dimension",
    "核心定位": "Core Positioning",
    "月费范围": "Monthly Fee Range",
    "无": "None",
    "移动支持": "Mobile Support",
    "目标市场": "Target Market",
    "全球": "Global",
    "痛点": "Pain Points",
    "解决方案": "Solution",
    "遗漏": "Missing",
    "及时": "Timely",
    "发送": "Send",
    "流程追踪": "Process Tracking",
    "行业趋势": "Industry Trends",
    "预测": "Prediction",
    "数字化趋势": "Digital Trends",
    "AI合规预警": "AI Compliance Warning",
    "预测认证过期风险": "Predict Certification Expiration Risk",
    "提前预警": "Advance Warning",
    "实时监控": "Real-time Monitoring",
    "异常": "Abnormal",
    "多地区": "Multi-region",
    "全球合规": "Global Compliance",
    "整合": "Integration",
    "一站式管理": "One-stop Management",
    "一键导出": "One-click Export",
    "提交监管机构": "Submit to Regulatory Authorities",
    "在线化": "Online",
    "在线课程": "Online Courses",
    "员工合规考核追踪": "Employee Compliance Assessment Tracking",
    "选型建议": "Selection Recommendations",
    "针对": "Targeting",
    "推荐": "Recommend",
    "选型策略": "Selection Strategy",
    "一体化": "Integrated",
    "直接影响": "Directly Impact",
    "综合评估": "Comprehensive Evaluation",
}

# Files to translate
files_to_translate = [
    "/Users/gejiayu/owner/seo/data/medical-equipment-rental-tools/medical-equipment-rental-compliance-management-system-review.json",
    "/Users/gejiayu/owner/seo/data/medical-equipment-rental-tools/medical-equipment-rental-contract-management-system-review.json",
    "/Users/gejiayu/owner/seo/data/medical-equipment-rental-tools/medical-equipment-rental-cost-management-system-review.json",
    "/Users/gejiayu/owner/seo/data/medical-equipment-rental-tools/medical-equipment-rental-crm-system-review.json",
    "/Users/gejiayu/owner/seo/data/medical-equipment-rental-tools/medical-equipment-rental-customer-satisfaction-system-review.json",
    "/Users/gejiayu/owner/seo/data/medical-equipment-rental-tools/medical-equipment-rental-customer-service-management-system-review.json",
    "/Users/gejiayu/owner/seo/data/medical-equipment-rental-tools/medical-equipment-rental-data-analytics-platform-review.json",
    "/Users/gejiayu/owner/seo/data/medical-equipment-rental-tools/medical-equipment-rental-delivery-management-system-review.json",
    "/Users/gejiayu/owner/seo/data/medical-equipment-rental-tools/medical-equipment-rental-demand-prediction-system-review.json",
    "/Users/gejiayu/owner/seo/data/medical-equipment-rental-tools/medical-equipment-rental-digital-transformation-system-review.json",
    "/Users/gejiayu/owner/seo/data/medical-equipment-rental-tools/medical-equipment-rental-document-management-system-review.json",
    "/Users/gejiayu/owner/seo/data/medical-equipment-rental-tools/medical-equipment-rental-energy-management-system-review.json",
    "/Users/gejiayu/owner/seo/data/medical-equipment-rental-tools/medical-equipment-rental-finance-management-system-review.json",
    "/Users/gejiayu/owner/seo/data/medical-equipment-rental-tools/medical-equipment-rental-financial-management-system-review.json",
    "/Users/gejiayu/owner/seo/data/medical-equipment-rental-tools/medical-equipment-rental-fleet-management-system-review.json",
    "/Users/gejiayu/owner/seo/data/medical-equipment-rental-tools/medical-equipment-rental-globalization-management-system-review.json",
    "/Users/gejiayu/owner/seo/data/medical-equipment-rental-tools/medical-equipment-rental-hr-management-system-review.json",
    "/Users/gejiayu/owner/seo/data/medical-equipment-rental-tools/medical-equipment-rental-innovation-management-system-review.json",
]

print("=" * 80)
print("FILES TO BE TRANSLATED (18 Chinese files)")
print("=" * 80)

for filepath in files_to_translate:
    filename = os.path.basename(filepath)
    print(f"  - {filename}")

print("\nThese files contain Chinese content that needs semantic translation to English.")
print("Next step: Use Claude Sonnet for semantic translation of each file.")
