#!/usr/bin/env python3
"""
Complete translation script using comprehensive pattern matching and replacement.
"""
import json
import re
from pathlib import Path

# Complete translation dictionary with all common patterns
COMPLETE_MAP = {
    # Audiobook-related terms
    "有声书": "audiobook",
    "音频": "audio",
    "录音": "recording",
    "配音": "voiceover",
    "语音": "voice",
    "声音": "sound",
    "自然度": "naturalness",
    "质量": "quality",
    "编辑": "editing",
    "制作": "production",
    "分发": "distribution",
    "上架": "publishing",
    "营销": "marketing",
    "推广": "promotion",
    "收益": "revenue",
    "分成": "sharing",
    "渠道": "channel",
    "平台": "platform",
    "工具": "tool",
    "软件": "software",
    "系统": "system",
    "方案": "solution",
    "服务": "service",
    "功能": "function",
    "特点": "feature",
    "优势": "advantage",
    "能力": "capability",
    "价值": "value",
    "效率": "efficiency",
    "成本": "cost",
    "投入": "investment",
    "预算": "budget",
    "价格": "price",
    "定价": "pricing",
    "订阅": "subscription",
    "免费": "free",
    "付费": "paid",
    "专业": "professional",
    "标准": "standard",
    "高级": "advanced",
    "基础": "basic",
    "完整": "complete",
    "详细": "detailed",
    "深度": "in-depth",
    "终极": "ultimate",
    "最佳": "best",
    "最优": "optimal",
    "智能": "intelligent",
    "自动化": "automated",
    "数字": "digital",
    "数据": "data",
    "分析": "analysis",
    "统计": "statistics",
    "追踪": "tracking",
    "管理": "management",
    "控制": "control",
    "优化": "optimization",
    "提升": "improvement",
    "降低": "reduction",
    "增加": "increase",
    "减少": "decrease",
    "覆盖": "coverage",
    "支持": "support",
    "适用": "suitable",
    "适合": "suitable for",
    "需求": "requirement",
    "挑战": "challenge",
    "趋势": "trend",
    "发展": "development",
    "未来": "future",
    "当前": "current",
    "传统": "traditional",
    "现代": "modern",
    "核心": "core",
    "关键": "key",
    "主要": "main",
    "重要": "important",
    "特殊": "special",
    "独特": "unique",
    "独家": "exclusive",
    "优先": "priority",
    "策略": "strategy",
    "方法": "method",
    "技术": "technology",
    "创新": "innovation",
    "突破": "breakthrough",
    "变革": "transformation",
    "行业": "industry",
    "市场": "market",
    "领域": "field",
    "细分": "segment",
    "创作者": "creator",
    "作者": "author",
    "出版商": "publisher",
    "用户": "user",
    "听众": "listener",
    "观众": "audience",
    "读者": "reader",
    "客户": "customer",
    "团队": "team",
    "大型": "large",
    "中型": "medium",
    "小型": "small",
    "独立": "independent",
    "企业": "enterprise",
    "商业": "business",
    "个人": "individual",
    "年": "year",
    "月": "month",
    "日": "day",
    "小时": "hour",
    "分钟": "minute",
    "秒": "second",
    "次": "time",
    "个": "",
    "项": "item",
    "段": "segment",
    "件": "piece",
    "种": "type",
    "类": "category",
    "级": "level",
    "度": "degree",
    "率": "rate",
    "量": "quantity",
    "额": "amount",
    "比": "ratio",
    "美元": "USD",
    "百分比": "percentage",
    "全球": "global",
    "国际": "international",
    "国内": "domestic",
    "本地": "local",
    "区域": "regional",
    "多语言": "multilingual",
    "多平台": "multi-platform",
    "多渠道": "multi-channel",
    "一体化": "integrated",
    "全流程": "full-process",
    "端到端": "end-to-end",
    "无缝": "seamless",
    "实时": "real-time",
    "即时": "instant",
    "快速": "fast",
    "高效": "high-efficiency",
    "便捷": "convenient",
    "简单": "simple",
    "复杂": "complex",
    "强大": "powerful",
    "灵活": "flexible",
    "可扩展": "scalable",
    "可定制": "customizable",
    "用户友好": "user-friendly",
    "易用": "easy-to-use",
    "稳定": "stable",
    "可靠": "reliable",
    "安全": "secure",
    "保障": "guarantee",
    "维护": "maintenance",
    "更新": "update",
    "升级": "upgrade",
    "版本": "version",
    "模式": "model",
    "类型": "type",
    "格式": "format",
    "标准": "standard",
    "规范": "specification",
    "协议": "protocol",
    "接口": "interface",
    "连接": "connection",
    "集成": "integration",
    "对接": "linking",
    "统一": "unified",
    "集中": "centralized",
    "分散": "distributed",
    "独立": "standalone",
    "共享": "shared",
    "开放": "open",
    "封闭": "closed",
    "公开": "public",
    "私有": "private",
    "专属": "dedicated",
    "定制": "custom",
    "通用": "general",
    "特定": "specific",
    "垂直": "vertical",
    "水平": "horizontal",
    "深度": "deep",
    "广度": "broad",
    "宽度": "width",
    "长度": "length",
    "大小": "size",
    "规模": "scale",
    "范围": "scope",
    "程度": "extent",
    "水平": "level",
    "阶段": "stage",
    "步骤": "step",
    "流程": "process",
    "环节": "phase",
    "节点": "node",
    "起点": "start",
    "终点": "end",
    "顺序": "sequence",
    "并行": "parallel",
    "串行": "serial",
    "同步": "synchronous",
    "异步": "asynchronous",
    "批量": "batch",
    "单个": "individual",
    "整体": "overall",
    "局部": "partial",
    "全部": "all",
    "部分": "part",
    "完整": "complete",
    "不完整": "incomplete",
    "必要": "necessary",
    "可选": "optional",
    "必需": "required",
    "推荐": "recommended",
    "建议": "suggested",
    "提示": "tip",
    "说明": "description",
    "解释": "explanation",
    "定义": "definition",
    "概念": "concept",
    "原理": "principle",
    "机制": "mechanism",
    "算法": "algorithm",
    "模型": "model",
    "框架": "framework",
    "架构": "architecture",
    "结构": "structure",
    "组件": "component",
    "模块": "module",
    "单元": "unit",
    "元素": "element",
    "对象": "object",
    "属性": "attribute",
    "参数": "parameter",
    "变量": "variable",
    "常量": "constant",
    "因子": "factor",
    "指标": "indicator",
    "标准": "standard",
    "基准": "benchmark",
    "参考": "reference",
    "比较": "comparison",
    "对比": "contrast",
    "对照": "control",
    "评价": "evaluation",
    "评估": "assessment",
    "测试": "test",
    "验证": "validation",
    "确认": "confirmation",
    "检查": "inspection",
    "审核": "review",
    "审批": "approval",
    "授权": "authorization",
    "认证": "certification",
    "许可": "license",
    "权利": "right",
    "版权": "copyright",
    "知识产权": "intellectual property",
    "专利": "patent",
    "商标": "trademark",
    "品牌": "brand",
    "声誉": "reputation",
    "影响力": "influence",
    "竞争力": "competitive power",
    "核心力": "core power",
    "驱动力": "driving force",
    "推动力": "propulsion",
    "阻力": "resistance",
    "障碍": "obstacle",
    "瓶颈": "bottleneck",
    "限制": "limitation",
    "约束": "constraint",
    "边界": "boundary",
    "范围": "scope",
    "领域": "domain",
    "空间": "space",
    "环境": "environment",
    "背景": "background",
    "场景": "scenario",
    "案例": "case",
    "示例": "example",
    "样本": "sample",
    "模板": "template",
    "原型": "prototype",
    "实例": "instance",
    "对象": "object",
    "实体": "entity",
    "主体": "subject",
    "客体": "object",
    "属性": "property",
    "特征": "characteristic",
    "特点": "feature",
    "性质": "nature",
    "本质": "essence",
    "表象": "appearance",
    "现象": "phenomenon",
    "事实": "fact",
    "真相": "truth",
    "假设": "hypothesis",
    "理论": "theory",
    "观点": "viewpoint",
    "意见": "opinion",
    "看法": "perspective",
    "态度": "attitude",
    "立场": "stance",
    "角度": "angle",
    "维度": "dimension",
    "层面": "level",
    "层次": "hierarchy",
    "级别": "grade",
    "等级": "rank",
    "排序": "ranking",
    "名次": "position",
    "排名": "ranking",
    "首位": "first",
    "首位": "top",
    "领先": "leading",
    "落后": "lagging",
    "追赶": "catching up",
    "超越": "surpassing",
    "保持": "maintaining",
    "稳定": "stable",
    "波动": "fluctuating",
    "变化": "changing",
    "增长": "growing",
    "下降": "declining",
    "上升": "rising",
    "提高": "improving",
    "降低": "reducing",
    "增强": "enhancing",
    "减弱": "weakening",
    "扩大": "expanding",
    "缩小": "shrinking",
    "延伸": "extending",
    "收缩": "contracting",
    "加速": "accelerating",
    "减速": "decelerating",
    "加快": "speeding up",
    "放慢": "slowing down",
    "提前": "advancing",
    "推迟": "delaying",
    "延期": "postponing",
    "取消": "canceling",
    "终止": "terminating",
    "完成": "completing",
    "结束": "ending",
    "开始": "starting",
    "启动": "launching",
    "初始化": "initializing",
    "配置": "configuring",
    "设置": "setting",
    "调整": "adjusting",
    "修改": "modifying",
    "更新": "updating",
    "删除": "deleting",
    "添加": "adding",
    "插入": "inserting",
    "替换": "replacing",
    "转换": "converting",
    "变换": "transforming",
    "处理": "processing",
    "计算": "calculating",
    "分析": "analyzing",
    "综合": "synthesizing",
    "归纳": "inducing",
    "演绎": "deducing",
    "推理": "reasoning",
    "预测": "predicting",
    "预报": "forecasting",
    "估计": "estimating",
    "测算": "measuring",
    "统计": "statistics",
    "记录": "recording",
    "存储": "storing",
    "保存": "saving",
    "读取": "reading",
    "加载": "loading",
    "导出": "exporting",
    "导入": "importing",
    "上传": "uploading",
    "下载": "downloading",
    "传输": "transmitting",
    "发送": "sending",
    "接收": "receiving",
    "推送": "pushing",
    "拉取": "pulling",
    "同步": "syncing",
    "异步": "async",
    "并发": "concurrent",
    "并行": "parallel",
    "串行": "serial",
    "顺序": "sequential",
    "随机": "random",
    "循环": "cyclic",
    "迭代": "iterative",
    "递归": "recursive",
    "分步": "step-by-step",
    "逐步": "gradual",
    "分段": "segmented",
    "分层": "layered",
    "分模块": "modular",
    "分组件": "component-based",
    "分服务": "service-based",
    "分功能": "function-based",
    "分层级": "hierarchical",
    "分类型": "type-based",
    "分类别": "category-based",
    "分级别": "grade-based",
    "分阶段": "phase-based",
    "分步骤": "step-based",
    "分环节": "phase-based",
    "分节点": "node-based",
    "分维度": "dimension-based",
    "分角度": "angle-based",
    "分层面": "level-based",
    "分层次": "hierarchy-based",
}

def translate_text(text):
    """Translate Chinese text using comprehensive mapping."""
    if not isinstance(text, str):
        return text

    # Check if contains Chinese
    if not re.search(r'[一-鿿]', text):
        return text

    translated = text

    # Apply all translations sorted by length (longest first)
    for chinese, english in sorted(COMPLETE_MAP.items(), key=lambda x: len(x[0]), reverse=True):
        translated = translated.replace(chinese, english)

    # Handle specific patterns
    translated = re.sub(r'2026年', '2026', translated)
    translated = re.sub(r'(\d+)年', r'\1', translated)
    translated = re.sub(r'(\d+)美元', r'$\1', translated)
    translated = re.sub(r'(\d+)个月', r'\1 months', translated)
    translated = re.sub(r'(\d+)小时', r'\1 hours', translated)
    translated = re.sub(r'(\d+)%', r'\1%', translated)

    # Clean up spacing
    translated = re.sub(r'  +', ' ', translated)

    # Clean up punctuation
    translated = translated.replace('：', ':').replace('，', ',').replace('。', '.').replace('！', '!').replace('？', '?')

    return translated.strip()

def process_file(filepath):
    """Process a single JSON file with complete translation."""
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            data = json.load(f)

        # Translate all fields
        for field in ['title', 'description', 'content', 'author']:
            if field in data:
                data[field] = translate_text(data[field])

        # Translate keywords
        if 'seo_keywords' in data and isinstance(data['seo_keywords'], list):
            data['seo_keywords'] = [translate_text(k) for k in data['seo_keywords']]

        # Write back
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(data, f, ensure_ascii=False, indent=2)

        return True
    except Exception as e:
        print(f"Error: {filepath}: {e}")
        return False

def main():
    data_dir = Path('/Users/gejiayu/owner/seo/data/publishing-media-tools')
    files = list(data_dir.glob('*.json'))

    print(f"Processing {len(files)} files with complete translation...")

    success = 0
    for i, f in enumerate(files, 1):
        if process_file(f):
            print(f"[{i}/{len(files)}] ✓ {f.name}")
            success += 1

    print(f"\nComplete: {success}/{len(files)} files")

if __name__ == '__main__':
    main()