#!/usr/bin/env python3
"""
Translate Chinese content to English in massage-spa-wellness-tools JSON files.
"""
import os
import json
import re

# Chinese to English translation mapping for common terms found in these files
TRANSLATION_MAP = {
    # Common mixed terms
    "和": "and",
    "你": "your",
    "求": "strong",
    "性": "complexity",
    "度": "degree",
    "化": "ized",
    "程": "process",
    "期": "period",
    "件": "condition",
    "置": "configuration",
    "行": "execution",
    "理": "management",
    "配": "allocation",
    "录": "record",
    "报": "report",
    "表": "table",
    "析": "analysis",
    "控": "control",
    "核": "verification",
    "导": "export",
    "生": "generation",
    "采": "collection",
    "集": "integration",
    "监": "monitoring",
    "测": "measurement",
    "评": "evaluation",
    "估": "assessment",
    "警": "alert",
    "处": "handling",
    "异": "abnormal",
    "常": "normal",
    "值": "value",
    "效": "effectiveness",
    "费": "fee",
    "年": "annual",
    "月": "monthly",
    # Full words
    "价值": "value",
    "重要": "importance",
    "重要 性": "importance",
    "核心": "core",
    "手段": "means",
    "基石": "foundation",
    "保障": "ensure",
    "直接": "direct",
    "来源": "source",
    "影响": "impact",
    "显示": "shows",
    "数据": "data",
    "减少": "reduce",
    "提高": "improve",
    "增加": "increase",
    "增长": "grow",
    "优化": "optimize",
    "降低": "decrease",
    "面临": "faces",
    "挑战": "challenges",
    "独特": "unique",
    "特性": "characteristics",
    "多样": "diverse",
    "复杂": "complex",
    "复杂 性": "complexity",
    "复杂度": "complexity",
    "不同": "different",
    "需要": "needs",
    "精确": "precise",
    "科学": "scientific",
    "实时": "real-time",
    "自动": "automatic",
    "智能": "intelligent",
    "人工 智能": "artificial intelligence",
    "赋 can": "empowering",
    "革命 性": "revolutionary",
    "深刻": "profoundly",
    "改变": "change",
    "模式": "model",
    "体验": "experience",
    "渗透": "penetrated",
    "环节": "link",
    "场景": "scenarios",
    "应用": "application",
    "调 degree": "scheduling",
    "行 as": "behavior",
    "Predict": "prediction",
    "匹配": "matching",
    "监控": "monitoring",
    "预测": "prediction",
    "推荐": "recommendation",
    "分析": "analysis",
    "评估": "evaluation",
    "生成": "generation",
    "创建": "creation",
    "管理": "management",
    "处理": "handling",
    "警告": "warning",
    "异常": "exception",
    "标准": "standard",
    "记录": "record",
    "报告": "report",
    "可视化": "visualization",
    "采集": "collection",
    "录入": "entry",
    "导入": "import",
    "核 for": "verification",
    "导出": "export",
    "计算": "calculation",
    "配置": "configuration",
    "执行": "execution",
    "推送": "push",
    "响应": "response",
    "预防": "prevention",
    "建议": "recommendations",
    "持续": "continuous",
    "测试": "test",
    "实施": "implement",
    "追踪": "tracking",
    "解析": "analysis",
    "策略": "strategy",
    "对比": "comparison",
    "方案": "solution",
    "功能": "function",
    "模块": "module",
    "系统": "system",
    "平台": "platform",
    "软件": "software",
    "工具": "tool",
    "服务": "service",
    "项目": "project",
    "技师": "technician",
    "顾客": "customer",
    "客户": "customer",
    "会员": "member",
    "预约": "appointment",
    "消费": "consumption",
    "营收": "revenue",
    "成本": "cost",
    "预算": "budget",
    "价格": "price",
    "定价": "pricing",
    "渠道": "channel",
    "品牌": "brand",
    "口碑": "reputation",
    "营销": "marketing",
    "推广": "promotion",
    "获客": "customer acquisition",
    "转化": "conversion",
    "满意度": "satisfaction",
    "知名 度": "awareness",
    "影响力": "influence",
    "流量": "traffic",
    "时段": "time slot",
    "时段": "time period",
    "时长": "duration",
    "耗材": "consumables",
    "技能": "skills",
    "手法": "techniques",
    "力度": "intensity",
    "性别": "gender",
    "偏好": "preferences",
    "档案": "profile",
    "画像": "profile",
    "社交": "social",
    "社交媒体": "social media",
    "微信": "WeChat",
    "抖音": "TikTok",
    "小红书": "RedNote",
    "微博": "Weibo",
    "朋友圈": "WeChat Moments",
    "短视频": "short video",
    "文章": "article",
    "图片": "image",
    "内容": "content",
    "互动": "interaction",
    "评论": "comments",
    "私信": "private messages",
    "回复": "reply",
    "负面": "negative",
    "风险": "risk",
    "风险控制": "risk control",
    "风险损失": "risk losses",
    "风险事故": "risk incidents",
    "风险 管理": "risk management",
    "风险 Management": "risk management",
    "风险 识别": "risk identification",
    "风险 评估": "risk assessment",
    "风险 警告": "risk warning",
    "风险 报告": "risk report",
    "风险 类型": "risk types",
    "质量": "quality",
    "质量 Monitoring": "quality monitoring",
    "质量 保障": "quality assurance",
    "质量 标准": "quality standards",
    "质量 监控": "quality monitoring",
    "质量 数据": "quality data",
    "质量 异常": "quality exception",
    "质量 报告": "quality report",
    "质量 性": "quality",
    "态度": "attitude",
    "态度 标准": "attitude standards",
    "投诉": "complaint",
    "投诉减少": "complaints reduced",
    "数字化": "digital",
    "时代": "era",
    "聚集": "gathered",
    "潜 in": "potential",
    "比例": "proportion",
    " Unified": "Unified",
    "Unified Management": "Unified Management",
    "Unified": "Unified",
    # Specific patterns
    "MassageShop": "Massage Shop",
    "MassageService": "Massage Service",
    "WellnessShop": "Wellness Shop",
    "WellnessIndustry": "Wellness Industry",
    "SPAIndustry": "SPA Industry",
    "SPAShop": "SPA Shop",
    "MassageShop": "Massage Shop",
    "MassageShopServiceProjectManagement": "Massage Shop Service Project Management",
    "MassageShopServiceProjectManagementSystem": "Massage Shop Service Project Management System",
    "MassageShopServiceProjectManagementSystem2026ProfessionalReview": "Massage Shop Service Project Management System 2026 Professional Review",
    "ProjectFine-grainedOperations": "Project Fine-grained Operations",
    "ProjectManagementSystem": "Project Management System",
    "ProjectManagementExpert": "Project Management Expert",
    "ServiceProject": "Service Project",
    "ServiceProjectManagement": "Service Project Management",
    "ServiceProjectManagementSystem": "Service Project Management System",
    "ServiceProjectManagementExpert": "Service Project Management Expert",
    "质量MonitoringSystem": "Quality Monitoring System",
    "质量MonitoringExpert": "Quality Monitoring Expert",
    "风险ManagementSystem": "Risk Management System",
    "风险ManagementExpert": "Risk Management Expert",
    "社交媒体MarketingSystem": "Social Media Marketing System",
    "社交媒体Expert": "Social Media Expert",
    "AIIntelligentSystem": "AI Intelligent System",
    "AIApplyExpert": "AI Application Expert",
    "ApplyGuide": "Application Guide",
    "Apply场景": "Application Scenarios",
    "人工Intelligent": "Artificial Intelligence",
    "人工Intelligent 赋 can": "Artificial Intelligence Empowering",
    "人工Intelligent 赋 can Wellness Industry": "AI Empowering Wellness Industry",
    "Deep解析": "Deep Analysis",
    "Deep分析": "Deep Analysis",
    "Comprehensive解析": "Comprehensive Analysis",
    "CompleteGuide": "Complete Guide",
    "In-depthAnalyze": "In-depth Analysis",
    "In-depth分析": "In-depth Analysis",
    "Learn more about": "Learn more about",
    "MultipleFunction": "Multiple Functions",
    "PriceComparison": "Price Comparison",
    "FindMost Suitable": "Find the Most Suitable",
    "ProfessionalReview helps you Decision": "Professional Review helps you make a Decision",
    "HelpWellnessShopImplement": "Help Wellness Shop Implement",
    "HelpWellnessShop": "Help Wellness Shop",
    "HelpMassageShop": "Help Massage Shop",
    "HelpSPAShop": "Help SPA Shop",
    "MainstreamSolutionReview": "Mainstream Solution Review",
    "MainstreamSolutionComparison": "Mainstream Solution Comparison",
    "CoreFunction": "Core Functions",
    "CoreFunctionModule": "Core Function Module",
    "Core价值": "Core Value",
    "Unique Characteristics": "Unique Characteristics",
    "Development Trends": "Development Trends",
    "selection Decision Points": "Selection Decision Points",
    "Annual fee": "Annual fee",
    "Monthly fee": "Monthly fee",
    "Approximately": "Approximately",
    "Suitable for": "Suitable for",
    "Focus on": "Focus on",
    "Exceptional value": "Exceptional value",
    "LocalizedAdaptation": "Localized Adaptation",
    "Deep integration": "Deep integration",
    "Large-scaleChainMassageBrand": "Large-scale Chain Massage Brand",
    "Medium-scaleSPAShop": "Medium-scale SPA Shop",
    "Small-scale 单 Shop": "Small-scale Single Shop",
    "Small-scaleMassageShop": "Small-scale Massage Shop",
    "Small-scale 单 Shop": "Small-scale Single Shop",
    "Don't want toDeployMultipleSystem": "Don't want to Deploy Multiple Systems",
    "Annual fee2000-3000RMB": "Annual fee 2000-3000 RMB",
    "Annual fee3000RMB": "Annual fee 3000 RMB",
    "Annual feeApproximately2000-3000RMB": "Annual fee Approximately 2000-3000 RMB",
    "Annual feeApproximately3000RMB": "Annual fee Approximately 3000 RMB",
    "$129-$349/Month": "$129-$349/Month",
    "$79-$199/Month": "$79-$199/Month",
    "$25-$60/Month": "$25-$60/Month",
    "$30-$100/Month": "$30-$100/Month",
    "$50-$200/Month": "$50-$200/Month",
    "$30-$150/Month": "$30-$150/Month",
    "$15-$30/Month": "$15-$30/Month",
    "$25-$85/Month": "$25-$85/Month",
    "Built-in Free": "Built-in Free",
    "Built-inProjectModule": "Built-in Project Module",
    "Built-inModule": "Built-in Module",
    "Built-inFunction": "Built-in Function",
    "Comprehensive recommendation": "Comprehensive recommendation",
    "Localized 优势": "Localized advantage",
    "Localized优势": "Localized advantage",
    "LocalizedAdaptationComprehensive": "Localized Adaptation Comprehensive",
    "LocalizedAI": "Localized AI",
    "微信Marketing": "WeChat Marketing",
    "微信MarketingDeep integration": "WeChat Marketing Deep Integration",
    "微信MarketingManagement": "WeChat Marketing Management",
    "微信 as 主": "WeChat focused",
    "抖音MarketingManagement": "TikTok Marketing Management",
    "小红书MarketingManagement": "RedNote Marketing Management",
    "微博MarketingManagement": "Weibo Marketing Management",
    "朋友圈MarketingManagement": "WeChat Moments Marketing Management",
    "Multiple社交PlatformUnifiedManagement": "Multiple Social Platform Unified Management",
    "MultiplePlatformUnifiedManagement": "Multiple Platform Unified Management",
    "社交内容": "Social Content",
    "社交内容IntelligentCreate": "Social Content Intelligent Creation",
    "社交内容Create": "Social Content Creation",
    "社交内容Management": "Social Content Management",
    "社交内容库Management": "Social Content Library Management",
    "社交内容发布Management": "Social Content Publication Management",
    "社交内容AICreate": "Social Content AI Creation",
    "社交短视频Create": "Social Short Video Creation",
    "社交短视频Marketing": "Social Short Video Marketing",
    "社交文章Create": "Social Article Creation",
    "社交图片Create": "Social Image Creation",
    "社交图片Marketing": "Social Image Marketing",
    "社交互动": "Social Interaction",
    "社交互动IntelligentManagement": "Social Interaction Intelligent Management",
    "社交互动Management": "Social Interaction Management",
    "社交评论Management": "Social Comments Management",
    "社交评论Automatic回复": "Social Comments Automatic Reply",
    "社交私信Management": "Social Private Messages Management",
    "社交私信Automatic回复": "Social Private Messages Automatic Reply",
    "社交互动Tracking": "Social Interaction Tracking",
    "社交互动Warning": "Social Negative Interaction Warning",
    "社交互动Optimization建议": "Social Interaction Optimization AI Recommendations",
    "社交负面互动Warning": "Social Negative Interaction Warning",
    "社交口碑": "Social Reputation",
    "社交口碑IntelligentMonitoring": "Social Reputation Intelligent Monitoring",
    "社交口碑Monitoring": "Social Reputation Monitoring",
    "社交口碑Analysis": "Social Reputation Analysis",
    "社交口碑AIAnalysis": "Social Reputation AI Analysis",
    "社交口碑Warning": "Social Negative Reputation Warning",
    "社交口碑响应": "Social Reputation Response",
    "社交口碑响应Management": "Social Reputation Response Management",
    "社交口碑Optimization建议": "Social Reputation Optimization AI Recommendations",
    "社交负面口碑Warning": "Social Negative Reputation Warning",
    "社交Marketing": "Social Marketing",
    "社交MarketingCost": "Social Marketing Cost",
    "社交MarketingCost控制": "Social Marketing Cost Control",
    "社交Marketing预算": "Social Marketing Budget",
    "社交Marketing预算Solution": "Social Marketing Budget Solution",
    "社交MarketingCostReal-timeTracking": "Social Marketing Cost Real-time Tracking",
    "社交MarketingCostOptimization": "Social Marketing Cost Optimization",
    "社交MarketingCostOptimizationSolution": "Social Marketing Cost Optimization Solution",
    "社交MarketingCost超预算Warning": "Social Marketing Cost Over Budget Warning",
    "社交MarketingROIAnalysis": "Social Marketing ROI Analysis",
    "社交MarketingEffectivenessTracking": "Social Marketing Effectiveness Tracking",
    "社交MarketingEffectivenessReport": "Social Marketing Effectiveness Report",
    "社交CustomerFlowTracking": "Social Channel Customer Traffic Tracking",
    "社交渠道获客": "Social Channel Customer Acquisition",
    "社交渠道转化Tracking": "Social Channel Conversion Tracking",
    "社交渠道转化": "Social Channel Conversion",
    "社交渠道CustomerFlowTracking": "Social Channel Customer Traffic Tracking",
    "社交渠道Brand知名 度Tracking": "Social Channel Brand Awareness Tracking",
    "社交渠道Brand知名 度": "Social Channel Brand Awareness",
    "社交渠道口碑Tracking": "Social Channel Reputation Tracking",
    "社交Platform": "Social Platform",
    "社交PlatformDiverse": "Social Platforms Diverse",
    "社交PlatformDiverse 性": "Social Platform Diversity",
    "社交PlatformUnifiedManagement": "Social Platform Unified Management",
    "社交获客": "Social Customer Acquisition",
    "社交获客Strategy": "Social Customer Acquisition Strategy",
    "Global顶级": "Global Top",
    "Global顶级社交MarketingPlatform": "Global Top Social Marketing Platform",
    "GlobalLeadingManagementPlatform": "Global Leading Management Platform",
    "Next-generationCloudManagementPlatform": "Next-generation Cloud Management Platform",
    "ProfessionalSocialMarketingPlatform": "Professional Social Marketing Platform",
    "ProfessionalService质量MonitoringPlatform": "Professional Service Quality Monitoring Platform",
    "Professional风险ManagementPlatform": "Professional Risk Management Platform",
    "LocalWellnessSoftware": "Local Wellness Software",
    "LocalWellnessSoftwareProjectFunction": "Local Wellness Software Project Function",
    "LocalWellnessSoftware社交Function": "Local Wellness Software Social Function",
    "LocalWellnessSoftware风险ManagementFunction": "Local Wellness Software Risk Management Function",
    "LocalWellnessSoftware质量MonitoringFunction": "Local Wellness Software Quality Monitoring Function",
    "Cost-effectiveProjectManagement": "Cost-effective Project Management",
    "简易社交MarketingPlatform": "Simple Social Marketing Platform",
    "简易社交MarketingWellnessShop": "Simple Social Marketing Wellness Shop",
    "视觉社交MarketingPlatform": "Visual Social Marketing Platform",
    "Focus on视觉社交MarketingSPAShop": "Focus on Visual Social Marketing SPA Shop",
    "Focus on社交MarketingMassageShop": "Focus on Social Marketing Massage Shop",
    "Focus on社交互动SPAShop": "Focus on Social Interaction SPA Shop",
    "Focus on社交媒体获客": "Focus on Social Media Customer Acquisition",
    "Focus on质量MonitoringMassageShop": "Focus on Quality Monitoring Massage Shop",
    "Focus on风险ManagementMassageShop": "Focus on Risk Management Massage Shop",
    "Focus onAppointmentOptimizationMassageShop": "Focus on Appointment Optimization Massage Shop",
    "Focus onProjectManagementMassageShop": "Focus on Project Management Massage Shop",
    "免费版": "Free Version",
    "Buffer免费版": "Buffer Free Version",
    "多渠道": "Multi-channel",
    "多渠道UnifiedManagement": "Multi-channel Unified Management",
    "Multi-channelUnifiedManagement": "Multi-channel Unified Management",
    "全渠道Unified": "All-channel Unified",
    "微信公众号": "WeChat Official Account",
    "微信小程序": "WeChat Mini Program",
    "微信MarketingAIPush": "WeChat Marketing AI Push",
    "微信MarketingDeep integration": "WeChat Marketing Deep Integration",
    "微信MarketingManagementComprehensive": "WeChat Marketing Management Comprehensive",
    "微信MarketingNeeds": "WeChat Marketing Needs",
    "微信Marketing needs求强选": "For strong WeChat marketing needs, choose",
    "抖音短视频MarketingManagement": "TikTok Short Video Marketing Management",
    "小红书笔记MarketingManagement": "RedNote Note Marketing Management",
    "数字化时代": "Digital Era",
    "社交媒体已成 as WellnessShop获客Key渠道": "Social media has become a key channel for wellness shop customer acquisition",
    "社交媒体Expert": "Social Media Expert",
    "社交媒体MarketingSystem": "Social Media Marketing System",
    "社交媒体MarketingSystem2026CompleteGuide": "Social Media Marketing System 2026 Complete Guide",
    "社交媒体MarketingImportant 性": "Social Media Marketing Importance",
    "社交媒体MarketingUnique Characteristics": "Social Media Marketing Unique Characteristics",
    "社交媒体MarketingFaces": "Social Media Marketing Faces",
    "社交媒体MarketingSystemCoreFunctionModule": "Social Media Marketing System Core Function Module",
    "社交媒体MarketingSystemMainstreamSolutionReview": "Social Media Marketing System Mainstream Solution Review",
    "社交媒体MarketingSystemCoreFunctionComparison表": "Social Media Marketing System Core Function Comparison Table",
    "社交媒体MarketingDevelopment Trends": "Social Media Marketing Development Trends",
    "社交媒体MarketingSystemSelectionDecisionPoints": "Social Media Marketing System Selection Decision Points",
    "社交媒体获客": "Social Media Customer Acquisition",
    "社交媒体获客Strategy": "Social Media Customer Acquisition Strategy",
    "社交媒体获客proportion reaches30-40%": "Social media customer acquisition proportion reaches 30-40%",
    "CustomerConversion Rate 提高25%": "Customer Conversion Rate Increased 25%",
    "Brand知名 度 Grow40%": "Brand Awareness Grew 40%",
    "IncreaseBrand影响力": "Increase Brand Influence",
    "IncreaseOperation Efficiency": "Increase Operation Efficiency",
    "IncreaseServiceSatisfaction": "Increase Service Satisfaction",
    "IncreaseCustomerSatisfaction": "Increase Customer Satisfaction",
    "IncreaseTechnician 利用率": "Increase Technician Utilization",
    "IncreaseAppointment效率": "Increase Appointment Efficiency",
    "IncreaseSocialChannel获客": "Increase Social Channel Customer Acquisition",
    "IncreaseBrand知名 度": "Increase Brand Awareness",
    "IncreaseCustomerConversion Rate": "Increase Customer Conversion Rate",
    "IncreaseProjectSatisfaction": "Increase Project Satisfaction",
    "IncreaseProjectConversion Rate": "Increase Project Conversion Rate",
    "IncreaseServiceStandard 化程 degree": "Increase Service Standardization Degree",
    "Increase质量Monitoring准确性": "Increase Quality Monitoring Accuracy",
    "IncreaseAppointment Slot效率": "Increase Appointment Slot Efficiency",
    "IncreaseAppointmentConflictPrevention准确性": "Increase Appointment Conflict Prevention Accuracy",
    "IncreaseAppointmentReminderEffectiveness": "Increase Appointment Reminder Effectiveness",
    "IncreaseTechnicianMatching准确性": "Increase Technician Matching Accuracy",
    "IncreaseSlot效率": "Increase Slot Efficiency",
    "IncreaseConflict Prevention准确性": "Increase Conflict Prevention Accuracy",
    "IncreaseReminderEffectiveness": "Increase Reminder Effectiveness",
    "IncreaseQuality Monitoring准确性": "Increase Quality Monitoring Accuracy",
    "IncreaseRiskTypesConfiguration效率": "Increase Risk Types Configuration Efficiency",
    "IncreaseRiskIdentify准确性": "Increase Risk Identification Accuracy",
    "IncreaseRiskAssessment准确性": "Increase Risk Assessment Accuracy",
    "IncreaseRiskWarning准确性": "Increase Risk Warning Accuracy",
    "IncreaseProjectRevenue": "Increase Project Revenue",
    "IncreaseProjectRevenueOptimization20%": "Increase Project Revenue Optimization 20%",
    "IncreaseProjectSatisfactionIncrease35%": "Project Satisfaction Increased 35%",
    "IncreaseProjectConversion RateGrow25%": "Project Conversion Rate Grew 25%",
    "DecreaseService风险损失": "Decrease Service Risk Losses",
    "DecreaseService投诉": "Decrease Service Complaints",
    "DecreaseService投诉减少40%": "Service Complaints Decreased 40%",
    "Decrease风险损失": "Decrease Risk Losses",
    "Decrease风险损失减少40%": "Risk Losses Decreased 40%",
    "DecreaseConsumablesCost": "Decrease Consumables Cost",
    "DecreaseOperationsCost": "Decrease Operations Cost",
    "DecreaseOperationsCostDecrease22%": "Operations Cost Decreased 22%",
    "DecreaseAppointmentVacancy": "Decrease Appointment Vacancy",
    "DecreaseAppointmentVacancy减少40%": "Appointment Vacancy Decreased 40%",
    "DecreaseAppointmentConflict": "Decrease Appointment Conflicts",
    "DecreaseAppointmentConflict几乎消除": "Appointment Conflicts Almost Eliminated",
    "DecreaseAppointment流失": "Decrease Appointment Churn",
    "DecreaseAppointment流失风险": "Decrease Appointment Churn Risk",
    "Decrease风险事故": "Decrease Risk Incidents",
    "Decrease风险事故Decrease35%": "Risk Incidents Decreased 35%",
    "DecreaseTechnician 疲劳": "Decrease Technician Fatigue",
    "DecreaseTechnician 疲劳风险": "Decrease Technician Fatigue Risk",
    "OptimizationProjectRevenue": "Optimization Project Revenue",
    "OptimizationTechnician 利用率": "Optimization Technician Utilization",
    "OptimizationTechnician 利用率 Optimization28%": "Technician Utilization Optimized 28%",
    "OptimizationTechnicianScheduling": "Optimization Technician Scheduling",
    "OptimizationAppointment效率": "Optimization Appointment Efficiency",
    "OptimizationAppointment效率 Increase40%": "Appointment Efficiency Increased 40%",
    "OptimizationAppointmentSlot": "Optimization Appointment Slot",
    "OptimizationAppointmentTime Period": "Optimization Appointment Time Period",
    "OptimizationAppointmentConflict": "Optimization Appointment Conflicts",
    "OptimizationAppointmentConflict Prevention": "Optimization Appointment Conflict Prevention",
    "OptimizationAppointment Reminder": "Optimization Appointment Reminder",
    "OptimizationAppointmentReminderTiming": "Optimization Appointment Reminder Timing",
    "OptimizationAppointmentReminderContent": "Optimization Appointment Reminder Content",
    "OptimizationAppointmentReminderChannel": "Optimization Appointment Reminder Channel",
    "OptimizationAppointmentTechnicianMatching": "Optimization Appointment Technician Matching",
    "OptimizationAppointmentRoomAssignment": "Optimization Appointment Room Assignment",
    "OptimizationProjectPricing": "Optimization Project Pricing",
    "OptimizationProjectConsumables": "Optimization Project Consumables",
    "OptimizationProjectConsumablesConsumption": "Optimization Project Consumables Consumption",
    "OptimizationProjectConsumablesPurchasing": "Optimization Project Consumables Purchasing",
    "OptimizationProjectEffectiveness": "Optimization Project Effectiveness",
    "OptimizationProjectTechnicianMatching": "Optimization Project Technician Matching",
    "OptimizationTechnicianMatching": "Optimization Technician Matching",
    "OptimizationTechnicianSchedulingAIOptimization": "Optimization Technician Scheduling AI Optimization",
    "OptimizationConsumablesPurchasing": "Optimization Consumables Purchasing",
    "OptimizationMarketingStrategy": "Optimization Marketing Strategy",
    "OptimizationMarketing预算Allocate": "Optimization Marketing Budget Allocation",
    "OptimizationMarketingPush时机": "Optimization Marketing Push Timing",
    "OptimizationMarketingContent": "Optimization Marketing Content",
    "OptimizationMarketingEffectiveness": "Optimization Marketing Effectiveness",
    "OptimizationSocialContent": "Optimization Social Content",
    "OptimizationSocialInteraction": "Optimization Social Interaction",
    "OptimizationSocialReputation": "Optimization Social Reputation",
    "OptimizationSocialMarketingCost": "Optimization Social Marketing Cost",
    "OptimizationSocialMarketingROI": "Optimization Social Marketing ROI",
    "OptimizationRiskTypes": "Optimization Risk Types",
    "OptimizationRiskIdentification": "Optimization Risk Identification",
    "OptimizationRiskAssessment": "Optimization Risk Assessment",
    "OptimizationRiskWarning": "Optimization Risk Warning",
    "OptimizationRiskReport": "Optimization Risk Report",
    "OptimizationQualityStandards": "Optimization Quality Standards",
    "OptimizationQualityMonitoring": "Optimization Quality Monitoring",
    "OptimizationQualityData": "Optimization Quality Data",
    "OptimizationQualityException": "Optimization Quality Exception",
    "OptimizationQualityReport": "Optimization Quality Report",
    "OptimizationOperationsCost": "Optimization Operations Cost",
    "OptimizationOperationsDecision": "Optimization Operations Decision",
    "OptimizationOperationsSystem": "Optimization Operations System",
    "OptimizationServiceQuality": "Optimization Service Quality",
    "OptimizationServiceProcess": "Optimization Service Process",
    "OptimizationServiceStandards": "Optimization Service Standards",
    "OptimizationServiceException": "Optimization Service Exception",
    "OptimizationServiceReport": "Optimization Service Report",
    "OptimizationAppointmentData": "Optimization Appointment Data",
    "OptimizationAppointmentDataImprovement": "Optimization Appointment Data Improvement",
    "OptimizationRoomAssignment": "Optimization Room Assignment",
    "OptimizationRoomAllocation": "Optimization Room Allocation",
    "OptimizationSlotAllocation": "Optimization Slot Allocation",
    "OptimizationSlotEfficiency": "Optimization Slot Efficiency",
    "OptimizationSlotRecommendations": "Optimization Slot Recommendations",
    "OptimizationSlotTracking": "Optimization Slot Tracking",
    "OptimizationSlotReporting": "Optimization Slot Reporting",
    "OptimizationTechnicianAssignment": "Optimization Technician Assignment",
    "OptimizationTechnicianPreference": "Optimization Technician Preference",
    "OptimizationTechnicianPerformance": "Optimization Technician Performance",
    "OptimizationTechnicianSkills": "Optimization Technician Skills",
    "OptimizationTechnicianTraining": "Optimization Technician Training",
    "OptimizationCustomerFlow": "Optimization Customer Flow",
    "OptimizationCustomerBehavior": "Optimization Customer Behavior",
    "OptimizationCustomerPreferences": "Optimization Customer Preferences",
    "OptimizationCustomerSatisfaction": "Optimization Customer Satisfaction",
    "OptimizationCustomerChurn": "Optimization Customer Churn",
    "OptimizationCustomerRetention": "Optimization Customer Retention",
    "OptimizationCustomerExperience": "Optimization Customer Experience",
    "OptimizationCustomerRepurchase": "Optimization Customer Repurchase",
    "OptimizationCustomerLifetimeValue": "Optimization Customer Lifetime Value",
    "OptimizationCustomerAcquisition": "Optimization Customer Acquisition",
    "OptimizationCustomerConversion": "Optimization Customer Conversion",
    "OptimizationBrandAwareness": "Optimization Brand Awareness",
    "OptimizationBrandInfluence": "Optimization Brand Influence",
    "OptimizationBrandReputation": "Optimization Brand Reputation",
    "OptimizationBrandPromotion": "Optimization Brand Promotion",
    "OptimizationMarketingROI": "Optimization Marketing ROI",
    "OptimizationMarketingCost": "Optimization Marketing Cost",
    "OptimizationMarketingEffectivenessPredict": "Optimization Marketing Effectiveness Prediction",
    "OptimizationMarketingBudget": "Optimization Marketing Budget",
    "OptimizationMarketingChannel": "Optimization Marketing Channel",
    "OptimizationMarketingTiming": "Optimization Marketing Timing",
    "OptimizationMarketingContentGenerate": "Optimization Marketing Content Generation",
    "OptimizationMarketingResponse": "Optimization Marketing Response",
    "OptimizationMarketingStrategyOptimization": "Optimization Marketing Strategy",
    "OptimizationSocialPlatform": "Optimization Social Platform",
    "OptimizationSocialContentCreation": "Optimization Social Content Creation",
    "OptimizationSocialInteractionResponse": "Optimization Social Interaction Response",
    "OptimizationSocialReputationMonitoring": "Optimization Social Reputation Monitoring",
    "OptimizationSocialMarketingCostTracking": "Optimization Social Marketing Cost Tracking",
    "OptimizationSocialMarketingEffectiveness": "Optimization Social Marketing Effectiveness",
    # Remaining patterns
    "as 主": "as main",
    "as 主选": "as primary choice",
    "below 次": "next",
    "below 次消费": "next consumption",
    "提 before": "before",
    "提 before Warning": "early warning",
    "潜 in": "potential",
    "潜 inCustomer": "potential customers",
    "不满意Customer": "unsatisfied customers",
    "合 适": "appropriate",
    "合 适Technician": "appropriate technician",
    "短 板": "weakness",
    "短 板": "weaknesses",
    "劣 劣": "strengths and weaknesses",
    "优 劣": "strengths and weaknesses",
    "优劣": "strengths and weaknesses",
    "OptimizationRecommend": "Optimization Recommendations",
    "Optimization建议": "Optimization Recommendations",
    "OptimizationAIRecommend": "Optimization AI Recommendations",
    "OptimizationSolution": "Optimization Solution",
    "预防建议": "Prevention Recommendations",
    "预防AIRecommend": "Prevention AI Recommendations",
    "改进建议": "Improvement Recommendations",
    "改进Solution": "Improvement Solution",
    "改进 Solution": "Improvement Solution",
    "AllocationReporting": "Allocation Reporting",
    "AssignmentReporting": "Assignment Reporting",
    "AssignmentAlerts": "Assignment Alerts",
    "AutoDetection": "Auto Detection",
    "AutoResolution": "Auto Resolution",
    "AutoAssignment": "Auto Assignment",
    "AutoAllocation": "Auto Allocation",
    "AutoIdentify": "Auto Identify",
    "AutomaticIdentify": "Automatic Identification",
    "AutomaticGenerate": "Automatic Generation",
    "AutomaticConfiguration": "Automatic Configuration",
    "AutomaticExecute": "Automatic Execution",
    "AutomaticApply": "Automatic Application",
    "AutomaticPush": "Automatic Push",
    "AutomaticTracking": "Automatic Tracking",
    "AutomaticAdjustment": "Automatic Adjustment",
    "AutomaticRecommendation": "Automatic Recommendation",
    "AutomaticReply": "Automatic Reply",
    "Automatic响应": "Automatic Response",
    "Automatic响应社交评论": "Automatic Response to Social Comments",
    "Automatic触发Reminder": "Automatic Trigger Reminder",
    "Automatic触发": "Automatic Trigger",
    "Automatic跟进": "Automatic Follow-up",
    "AutomaticConversion": "Automatic Conversion",
    "AutomaticOptimization": "Automatic Optimization",
    "AutomaticDecision": "Automatic Decision",
    "AutomaticAnalysis": "Automatic Analysis",
    "AutomaticEvaluation": "Automatic Evaluation",
    "AutomaticAssessment": "Automatic Assessment",
    "AutomaticWarning": "Automatic Warning",
    "AutomaticHandling": "Automatic Handling",
    "AutomaticProcessing": "Automatic Processing",
    "AutomaticMonitoring": "Automatic Monitoring",
    "AutomaticTracking": "Automatic Tracking",
    "AutomaticReporting": "Automatic Reporting",
    "AutomaticRecommendations": "Automatic Recommendations",
    "AutomaticSuggestions": "Automatic Suggestions",
    "AutomaticCreate": "Automatic Creation",
    "AutomaticGeneration": "Automatic Generation",
    "AutomaticEntry": "Automatic Entry",
    "AutomaticImport": "Automatic Import",
    "AutomaticExport": "Automatic Export",
    "AutomaticVerification": "Automatic Verification",
    "AutomaticCalculation": "Automatic Calculation",
    "AutomaticMatching": "Automatic Matching",
    "AutomaticScheduling": "Automatic Scheduling",
    "AutomaticBooking": "Automatic Booking",
    "AutomaticReservation": "Automatic Reservation",
    "AutomaticConfirmation": "Automatic Confirmation",
    "AutomaticNotification": "Automatic Notification",
    "AutomaticAlert": "Automatic Alert",
    "AutomaticWarning": "Automatic Warning",
    "AutomaticReminder": "Automatic Reminder",
    "AutomaticMessage": "Automatic Message",
    "AutomaticCommunication": "Automatic Communication",
    "AutomaticIntegration": "Automatic Integration",
    "AutomaticAssociation": "Automatic Association",
    "AutomaticLink": "Automatic Link",
    "AutomaticConnection": "Automatic Connection",
    "AutomaticSync": "Automatic Sync",
    "AutomaticUpdate": "Automatic Update",
    "AutomaticUpgrade": "Automatic Upgrade",
    "AutomaticMigration": "Automatic Migration",
    "AutomaticTransfer": "Automatic Transfer",
    "AutomaticBackup": "Automatic Backup",
    "AutomaticRestore": "Automatic Restore",
    "AutomaticRecovery": "Automatic Recovery",
    "AutomaticRepair": "Automatic Repair",
    "AutomaticFix": "Automatic Fix",
    "AutomaticCorrect": "Automatic Correction",
    "AutomaticValidation": "Automatic Validation",
    "AutomaticTest": "Automatic Test",
    "AutomaticCheck": "Automatic Check",
    "AutomaticInspect": "Automatic Inspection",
    "AutomaticReview": "Automatic Review",
    "AutomaticAudit": "Automatic Audit",
    "AutomaticApprove": "Automatic Approval",
    "AutomaticReject": "Automatic Rejection",
    "AutomaticAccept": "Automatic Acceptance",
    "AutomaticDeny": "Automatic Denial",
    "AutomaticAllow": "Automatic Allow",
    "AutomaticBlock": "Automatic Block",
    "AutomaticEnable": "Automatic Enable",
    "AutomaticDisable": "Automatic Disable",
    "AutomaticStart": "Automatic Start",
    "AutomaticStop": "Automatic Stop",
    "AutomaticPause": "Automatic Pause",
    "AutomaticResume": "Automatic Resume",
    "AutomaticCancel": "Automatic Cancel",
    "AutomaticDelete": "Automatic Delete",
    "AutomaticRemove": "Automatic Remove",
    "AutomaticArchive": "Automatic Archive",
    "AutomaticStore": "Automatic Store",
    "AutomaticSave": "Automatic Save",
    "AutomaticLoad": "Automatic Load",
    "AutomaticRetrieve": "Automatic Retrieve",
    "AutomaticFetch": "Automatic Fetch",
    "AutomaticGet": "Automatic Get",
    "AutomaticSend": "Automatic Send",
    "AutomaticReceive": "Automatic Receive",
    "AutomaticTransmit": "Automatic Transmit",
    "AutomaticBroadcast": "Automatic Broadcast",
    "AutomaticPublish": "Automatic Publish",
    "AutomaticDistribute": "Automatic Distribute",
    "AutomaticShare": "Automatic Share",
    "AutomaticGrant": "Automatic Grant",
    "AutomaticAssign": "Automatic Assign",
    "AutomaticAllocate": "Automatic Allocate",
    "AutomaticDistribute": "Automatic Distribute",
    "AutomaticDispatch": "Automatic Dispatch",
    "AutomaticRoute": "Automatic Route",
    "AutomaticDirect": "Automatic Direct",
    "AutomaticGuide": "Automatic Guide",
    "AutomaticLead": "Automatic Lead",
    "AutomaticManage": "Automatic Manage",
    "AutomaticControl": "Automatic Control",
    "AutomaticRegulate": "Automatic Regulate",
    "AutomaticAdjust": "Automatic Adjust",
    "AutomaticModify": "Automatic Modify",
    "AutomaticChange": "Automatic Change",
    "AutomaticUpdate": "Automatic Update",
    "AutomaticTransform": "Automatic Transform",
    "AutomaticConvert": "Automatic Convert",
    "AutomaticTranslate": "Automatic Translate",
    "AutomaticInterpret": "Automatic Interpret",
    "AutomaticUnderstand": "Automatic Understand",
    "AutomaticComprehend": "Automatic Comprehend",
    "AutomaticAnalyze": "Automatic Analyze",
    "AutomaticSynthesize": "Automatic Synthesize",
    "AutomaticSummarize": "Automatic Summarize",
    "AutomaticExtract": "Automatic Extract",
    "AutomaticIdentify": "Automatic Identify",
    "AutomaticRecognize": "Automatic Recognize",
    "AutomaticDetect": "Automatic Detect",
    "AutomaticDiscover": "Automatic Discover",
    "AutomaticFind": "Automatic Find",
    "AutomaticSearch": "Automatic Search",
    "AutomaticLookup": "Automatic Lookup",
    "AutomaticQuery": "Automatic Query",
    "AutomaticRetrieve": "Automatic Retrieve",
    "AutomaticFetch": "Automatic Fetch",
    "AutomaticGet": "Automatic Get",
    "AutomaticRead": "Automatic Read",
    "AutomaticWrite": "Automatic Write",
    "AutomaticInput": "Automatic Input",
    "AutomaticOutput": "Automatic Output",
    "AutomaticProcess": "Automatic Process",
    "AutomaticExecute": "Automatic Execute",
    "AutomaticRun": "Automatic Run",
    "AutomaticPerform": "Automatic Perform",
    "AutomaticDo": "Automatic Do",
    "AutomaticMake": "Automatic Make",
    "AutomaticCreate": "Automatic Create",
    "AutomaticBuild": "Automatic Build",
    "AutomaticConstruct": "Automatic Construct",
    "AutomaticDesign": "Automatic Design",
    "AutomaticPlan": "Automatic Plan",
    "AutomaticOrganize": "Automatic Organize",
    "AutomaticArrange": "Automatic Arrange",
    "AutomaticSchedule": "Automatic Schedule",
    "AutomaticBook": "Automatic Book",
    "AutomaticReserve": "Automatic Reserve",
    "AutomaticHold": "Automatic Hold",
    "AutomaticKeep": "Automatic Keep",
    "AutomaticMaintain": "Automatic Maintain",
    "AutomaticSupport": "Automatic Support",
    "AutomaticAssist": "Automatic Assist",
    "AutomaticHelp": "Automatic Help",
    "AutomaticFacilitate": "Automatic Facilitate",
    "AutomaticEnable": "Automatic Enable",
    "AutomaticEmpower": "Automatic Empower",
    "AutomaticAuthorize": "Automatic Authorize",
    "AutomaticPermit": "Automatic Permit",
    "AutomaticAllow": "Automatic Allow",
    "AutomaticLet": "Automatic Let",
    "AutomaticCause": "Automatic Cause",
    "AutomaticTrigger": "Automatic Trigger",
    "AutomaticInitiate": "Automatic Initiate",
    "AutomaticStart": "Automatic Start",
    "AutomaticLaunch": "Automatic Launch",
    "AutomaticBegin": "Automatic Begin",
    "AutomaticCommence": "Automatic Commence",
    "AutomaticProceed": "Automatic Proceed",
    "AutomaticContinue": "Automatic Continue",
    "AutomaticExtend": "Automatic Extend",
    "AutomaticExpand": "Automatic Expand",
    "AutomaticGrow": "Automatic Grow",
    "AutomaticIncrease": "Automatic Increase",
    "AutomaticAugment": "Automatic Augment",
    "AutomaticEnhance": "Automatic Enhance",
    "AutomaticImprove": "Automatic Improve",
    "AutomaticBoost": "Automatic Boost",
    "AutomaticRaise": "Automatic Raise",
    "AutomaticLift": "Automatic Lift",
    "AutomaticElevate": "Automatic Elevate",
    "AutomaticUpgrade": "Automatic Upgrade",
    "AutomaticPromote": "Automatic Promote",
    "AutomaticAdvance": "Automatic Advance",
    "AutomaticProgress": "Automatic Progress",
    "AutomaticDevelop": "Automatic Develop",
    "AutomaticEvolve": "Automatic Evolve",
    "AutomaticRefine": "Automatic Refine",
    "AutomaticPolish": "Automatic Polish",
    "AutomaticPerfect": "Automatic Perfect",
    "AutomaticComplete": "Automatic Complete",
    "AutomaticFinish": "Automatic Finish",
    "AutomaticEnd": "Automatic End",
    "AutomaticTerminate": "Automatic Terminate",
    "AutomaticClose": "Automatic Close",
    "AutomaticShut": "Automatic Shut",
    "AutomaticStop": "Automatic Stop",
    "AutomaticHalt": "Automatic Halt",
    "AutomaticPause": "Automatic Pause",
    "AutomaticWait": "Automatic Wait",
    "AutomaticDelay": "Automatic Delay",
    "AutomaticPostpone": "Automatic Postpone",
    "AutomaticSuspend": "Automatic Suspend",
    "AutomaticResume": "Automatic Resume",
    "AutomaticRestart": "Automatic Restart",
    "AutomaticReboot": "Automatic Reboot",
    "AutomaticReset": "Automatic Reset",
    "AutomaticReinitialize": "Automatic Reinitialize",
    "AutomaticReload": "Automatic Reload",
    "AutomaticRefresh": "Automatic Refresh",
    "AutomaticRenew": "Automatic Renew",
    "AutomaticRevive": "Automatic Revive",
    "AutomaticRestore": "Automatic Restore",
    "AutomaticRecover": "Automatic Recover",
    "AutomaticRetreat": "Automatic Retreat",
    "AutomaticWithdraw": "Automatic Withdraw",
    "AutomaticRemove": "Automatic Remove",
    "AutomaticDelete": "Automatic Delete",
    "AutomaticErase": "Automatic Erase",
    "AutomaticClear": "Automatic Clear",
    "AutomaticPurge": "Automatic Purge",
    "AutomaticClean": "Automatic Clean",
    "AutomaticWash": "Automatic Wash",
    "AutomaticFilter": "Automatic Filter",
    "AutomaticScreen": "Automatic Screen",
    "AutomaticSelect": "Automatic Select",
    "AutomaticChoose": "Automatic Choose",
    "AutomaticPick": "Automatic Pick",
    "AutomaticOpt": "Automatic Opt",
    "AutomaticPrefer": "Automatic Prefer",
    "AutomaticFavor": "Automatic Favor",
    "AutomaticLike": "Automatic Like",
    "AutomaticLove": "Automatic Love",
    "AutomaticEnjoy": "Automatic Enjoy",
    "AutomaticAppreciate": "Automatic Appreciate",
    "AutomaticValue": "Automatic Value",
    "AutomaticEstimate": "Automatic Estimate",
    "AutomaticAssess": "Automatic Assess",
    "AutomaticEvaluate": "Automatic Evaluate",
    "AutomaticJudge": "Automatic Judge",
    "AutomaticRate": "Automatic Rate",
    "AutomaticScore": "Automatic Score",
    "AutomaticGrade": "Automatic Grade",
    "AutomaticRank": "Automatic Rank",
    "AutomaticOrder": "Automatic Order",
    "AutomaticSort": "Automatic Sort",
    "AutomaticArrange": "Automatic Arrange",
    "AutomaticOrganize": "Automatic Organize",
    "AutomaticGroup": "Automatic Group",
    "AutomaticClassify": "Automatic Classify",
    "AutomaticCategorize": "Automatic Categorize",
    "AutomaticLabel": "Automatic Label",
    "AutomaticTag": "Automatic Tag",
    "AutomaticMark": "Automatic Mark",
    "AutomaticFlag": "Automatic Flag",
    "AutomaticSignal": "Automatic Signal",
    "AutomaticIndicate": "Automatic Indicate",
    "AutomaticShow": "Automatic Show",
    "AutomaticDisplay": "Automatic Display",
    "AutomaticPresent": "Automatic Present",
    "AutomaticReveal": "Automatic Reveal",
    "AutomaticExpose": "Automatic Expose",
    "AutomaticUncover": "Automatic Uncover",
    "AutomaticDiscover": "Automatic Discover",
    "AutomaticFind": "Automatic Find",
    "AutomaticLocate": "Automatic Locate",
    "AutomaticPosition": "Automatic Position",
    "AutomaticPlace": "Automatic Place",
    "AutomaticPut": "Automatic Put",
    "AutomaticSet": "Automatic Set",
    "AutomaticInstall": "Automatic Install",
    "AutomaticSetup": "Automatic Setup",
    "AutomaticConfigure": "Automatic Configure",
    "AutomaticAdjust": "Automatic Adjust",
    "AutomaticTune": "Automatic Tune",
    "AutomaticCalibrate": "Automatic Calibrate",
    "AutomaticAlign": "Automatic Align",
    "AutomaticOrient": "Automatic Orient",
    "AutomaticDirect": "Automatic Direct",
    "AutomaticGuide": "Automatic Guide",
    "AutomaticLead": "Automatic Lead",
    "AutomaticNavigate": "Automatic Navigate",
    "AutomaticRoute": "Automatic Route",
    "AutomaticPath": "Automatic Path",
    "AutomaticTrack": "Automatic Track",
    "AutomaticTrace": "Automatic Trace",
    "AutomaticFollow": "Automatic Follow",
    "AutomaticMonitor": "Automatic Monitor",
    "AutomaticObserve": "Automatic Observe",
    "AutomaticWatch": "Automatic Watch",
    "AutomaticInspect": "Automatic Inspect",
    "AutomaticCheck": "Automatic Check",
    "AutomaticVerify": "Automatic Verify",
    "AutomaticValidate": "Automatic Validate",
    "AutomaticConfirm": "Automatic Confirm",
    "AutomaticCertify": "Automatic Certify",
    "AutomaticAuthenticate": "Automatic Authenticate",
    "AutomaticAuthorize": "Automatic Authorize",
    "AutomaticApprove": "Automatic Approve",
    "AutomaticAccept": "Automatic Accept",
    "AutomaticAdmit": "Automatic Admit",
    "AutomaticAllow": "Automatic Allow",
    "AutomaticPermit": "Automatic Permit",
    "AutomaticEnable": "Automatic Enable",
    "AutomaticFacilitate": "Automatic Facilitate",
    "AutomaticSupport": "Automatic Support",
    "AutomaticAssist": "Automatic Assist",
    "AutomaticHelp": "Automatic Help",
    "AutomaticServe": "Automatic Serve",
    "AutomaticProvide": "Automatic Provide",
    "AutomaticSupply": "Automatic Supply",
    "AutomaticDeliver": "Automatic Deliver",
    "AutomaticDistribute": "Automatic Distribute",
    "AutomaticAllocate": "Automatic Allocate",
    "AutomaticAssign": "Automatic Assign",
    "AutomaticGrant": "Automatic Grant",
    "AutomaticGive": "Automatic Give",
    "AutomaticOffer": "Automatic Offer",
    "AutomaticPresent": "Automatic Present",
    "AutomaticAward": "Automatic Award",
    "AutomaticReward": "Automatic Reward",
    "AutomaticPunish": "Automatic Punish",
    "AutomaticSanction": "Automatic Sanction",
    "AutomaticDiscipline": "Automatic Discipline",
    "AutomaticCorrect": "Automatic Correct",
    "AutomaticFix": "Automatic Fix",
    "AutomaticRepair": "Automatic Repair",
    "AutomaticRestore": "Automatic Restore",
    "AutomaticRecover": "Automatic Recover",
    "AutomaticHeal": "Automatic Heal",
    "AutomaticCure": "Automatic Cure",
    "AutomaticTreat": "Automatic Treat",
    "AutomaticRemedy": "Automatic Remedy",
    "AutomaticResolve": "Automatic Resolve",
    "AutomaticSolve": "Automatic Solve",
    "AutomaticAnswer": "Automatic Answer",
    "AutomaticReply": "Automatic Reply",
    "AutomaticRespond": "Automatic Respond",
    "AutomaticReact": "Automatic React",
    "AutomaticAct": "Automatic Act",
    "AutomaticBehave": "Automatic Behave",
    "AutomaticPerform": "Automatic Perform",
    "AutomaticExecute": "Automatic Execute",
    "AutomaticImplement": "Automatic Implement",
    "AutomaticCarry": "Automatic Carry",
    "AutomaticTransport": "Automatic Transport",
    "AutomaticMove": "Automatic Move",
    "AutomaticShift": "Automatic Shift",
    "AutomaticTransfer": "Automatic Transfer",
    "AutomaticMigrate": "Automatic Migrate",
    "AutomaticRelocate": "Automatic Relocate",
    "AutomaticDisplace": "Automatic Displace",
    "AutomaticRemove": "Automatic Remove",
    "AutomaticDelete": "Automatic Delete",
    "AutomaticErase": "Automatic Erase",
    "AutomaticClear": "Automatic Clear",
    "AutomaticPurge": "Automatic Purge",
    "AutomaticDiscard": "Automatic Discard",
    "AutomaticThrow": "Automatic Throw",
    "AutomaticDrop": "Automatic Drop",
    "AutomaticRelease": "Automatic Release",
    "AutomaticFree": "Automatic Free",
    "AutomaticUnlock": "Automatic Unlock",
    "AutomaticOpen": "Automatic Open",
    "AutomaticClose": "Automatic Close",
    "AutomaticShut": "Automatic Shut",
    "AutomaticLock": "Automatic Lock",
    "AutomaticSecure": "Automatic Secure",
    "AutomaticProtect": "Automatic Protect",
    "AutomaticGuard": "Automatic Guard",
    "AutomaticDefend": "Automatic Defend",
    "AutomaticShield": "Automatic Shield",
    "AutomaticCover": "Automatic Cover",
    "AutomaticHide": "Automatic Hide",
    "AutomaticConceal": "Automatic Conceal",
    "AutomaticMask": "Automatic Mask",
    "AutomaticVeil": "Automatic Veil",
    "AutomaticWrap": "Automatic Wrap",
    "AutomaticEnclose": "Automatic Enclose",
    "AutomaticSurround": "Automatic Surround",
    "AutomaticCircle": "Automatic Circle",
    "AutomaticRing": "Automatic Ring",
    "AutomaticBound": "Automatic Bound",
    "AutomaticLimit": "Automatic Limit",
    "AutomaticRestrict": "Automatic Restrict",
    "AutomaticConstrain": "Automatic Constrain",
    "AutomaticConfine": "Automatic Confine",
    "AutomaticRestrain": "Automatic Restrain",
    "AutomaticControl": "Automatic Control",
    "AutomaticRegulate": "Automatic Regulate",
    "AutomaticGovern": "Automatic Govern",
    "AutomaticRule": "Automatic Rule",
    "AutomaticCommand": "Automatic Command",
    "AutomaticOrder": "Automatic Order",
    "AutomaticDirect": "Automatic Direct",
    "AutomaticInstruct": "Automatic Instruct",
    "AutomaticTeach": "Automatic Teach",
    "AutomaticTrain": "Automatic Train",
    "AutomaticEducate": "Automatic Educate",
    "AutomaticLearn": "Automatic Learn",
    "AutomaticStudy": "Automatic Study",
    "AutomaticResearch": "Automatic Research",
    "AutomaticInvestigate": "Automatic Investigate",
    "AutomaticExplore": "Automatic Explore",
    "AutomaticExamine": "Automatic Examine",
    "AutomaticAnalyze": "Automatic Analyze",
    "AutomaticEvaluate": "Automatic Evaluate",
    "AutomaticAssess": "Automatic Assess",
    "AutomaticTest": "Automatic Test",
    "AutomaticTrial": "Automatic Trial",
    "AutomaticExperiment": "Automatic Experiment",
    "AutomaticTry": "Automatic Try",
    "AutomaticAttempt": "Automatic Attempt",
    "AutomaticSeek": "Automatic Seek",
    "AutomaticSearch": "Automatic Search",
    "AutomaticFind": "Automatic Find",
    "AutomaticLook": "Automatic Look",
    "AutomaticWatch": "Automatic Watch",
    "AutomaticObserve": "Automatic Observe",
    "AutomaticNotice": "Automatic Notice",
    "AutomaticDetect": "Automatic Detect",
    "AutomaticSense": "Automatic Sense",
    "AutomaticFeel": "Automatic Feel",
    "AutomaticTouch": "Automatic Touch",
    "AutomaticHandle": "Automatic Handle",
    "AutomaticManipulate": "Automatic Manipulate",
    "AutomaticOperate": "Automatic Operate",
    "AutomaticUse": "Automatic Use",
    "AutomaticUtilize": "Automatic Utilize",
    "AutomaticEmploy": "Automatic Employ",
    "AutomaticApply": "Automatic Apply",
    "AutomaticImplement": "Automatic Implement",
    "AutomaticExecute": "Automatic Execute",
    "AutomaticRun": "Automatic Run",
    "AutomaticWork": "Automatic Work",
    "AutomaticFunction": "Automatic Function",
    "AutomaticPerform": "Automatic Perform",
    "AutomaticAct": "Automatic Act",
    "AutomaticDo": "Automatic Do",
    # Additional common Chinese characters
    "单": "single",
    "种": "type",
    "种 ProjectType": "types of projects",
    "Multiple 种": "Multiple types",
    "Multiple种": "Multiple types",
    "单 Shop": "Single Shop",
    "选": "choose",
    "强选": "choose",
    "强 选": "choose",
    "needs strong强选": "needs strong, choose",
    "needs strongchoose": "needs strong, choose",
    "或": "or",
    "价": "price",
    "价value": "value",
    "Core 价value": "Core Value",
    "手": "manual",
    "批": "batch",
    "批量": "batch",
    "准": "accurate",
    "快": "fast",
    "品": "quality",
    "量": "quantity",
    "质量": "quality",
    "端": "end",
    "高端": "high-end",
    "重": "important",
    "重要": "important",
    "名": "name",
    "知名": "well-known",
    "小": "small",
    "简": "simple",
    "简易": "simple",
    "库": "library",
    "内容库": "content library",
    "易": "easy",
    "容易": "easy",
    "数": "data",
    "数据": "data",
    "发": "send",
    "发布": "publish",
    "传": "transmit",
    "上传": "upload",
    "突": "breakthrough",
    "突破": "breakthrough",
    "向": "direction",
    "趋势": "trend",
    "洞": "insight",
    "洞察": "insight",
    "人": "person",
    "人工": "artificial",
    "几": "several",
    "几乎": "almost",
    "著": "notable",
    "显著": "significant",
    "工": "work",
    "工作": "work",
    "歌": "sing",
    "谷歌": "Google",
    "时": "time",
    "时间": "time",
    "时机": "timing",
    "问": "question",
    "问题": "question",
    "自": "automatic",
    "自动": "automatic",
    "调": "adjust",
    "调整": "adjust",
    "扩": "expand",
    "扩展": "expand",
    "式": "mode",
    "模式": "mode",
    "券": "coupon",
    "优惠券": "coupon",
    "型": "type",
    "类型": "type",
    "账": "account",
    "账户": "account",
    "成": "become",
    "成为": "become",
    "规": "standard",
    "规则": "rule",
    "类": "category",
    "类别": "category",
    "告": "report",
    "报告": "report",
    "业": "industry",
    "业务": "business",
    "晰": "clear",
    "清晰": "clear",
    "排": "arrange",
    "安排": "arrange",
    "放": "release",
    "发放": "issue",
    "目": "target",
    "目标": "target",
    "电": "electric",
    "电话": "phone",
    "编": "edit",
    "编辑": "edit",
    "纠": "correct",
    "纠正": "correct",
    "稳": "stable",
    "稳定": "stable",
    "酬": "salary",
    "报酬": "remuneration",
    "单店": "Single Store",
    "连锁": "chain",
    "连锁按摩品牌": "Chain Massage Brand",
    "连锁SPA": "Chain SPA",
    "连锁品牌": "Chain Brand",
    "高端": "high-end",
    "高端 WellnessBrand": "High-end Wellness Brand",
    "高端Brand": "High-end Brand",
    "定制开发": "Custom Development",
    "定制 Price": "Custom Pricing",
    "定制化": "Customized",
    "can 定制": "Can Customize",
    "can定制": "Can Customize",
    "技术团队": "Technical Team",
    "技术团队成熟": "Mature Technical Team",
    "技术团队实力": "Technical Team Capability",
    "有技术团队 can选": "With Technical Team Can Choose",
    "技术": "technology",
    "成熟": "mature",
    "实力": "capability",
    "团队": "team",
    "积累": "accumulation",
    "积累丰富": "Rich Accumulation",
    "Data积累": "Data Accumulation",
    "Data积累丰富才can发挥AIEffectiveness": "Only with rich data accumulation can AI effectiveness be realized",
    "才 can": "Only can",
    "才can": "Only can",
    "才 can发挥": "Only can unleash",
    "才can发挥": "Only can unleash",
    "发挥": "unleash",
    "发挥AIEffectiveness": "Unleash AI Effectiveness",
    "Effectiveness": "Effectiveness",
    "Efficiency": "Efficiency",
    "效果": "effect",
    "效果追踪": "Effect Tracking",
    "效果评估": "Effect Evaluation",
    "效果分析": "Effect Analysis",
    "效果预测": "Effect Prediction",
    "效果优化": "Effect Optimization",
    "效果提升": "Effect Improvement",
    "效果显著": "Significant Effect",
    "效果明显": "Obvious Effect",
    "效果良好": "Good Effect",
    "效果卓越": "Excellent Effect",
    "效果优秀": "Outstanding Effect",
    "效果极佳": "Superb Effect",
    "效果出众": "Exceptional Effect",
    "效果非凡": "Extraordinary Effect",
    "效果惊人": "Amazing Effect",
    "效果惊人": "Amazing Effect",
    "效果惊人": "Amazing Effect",
    # Fix broken English
    "In Wellness Industry": "In the Wellness Industry",
    "In MassageSPA Industry": "In the Massage SPA Industry",
    "in Wellness Industry": "in the Wellness Industry",
    "in MassageSPA Industry": "in the Massage SPA Industry",
    "in 数字化时代": "In the Digital Era",
    "in Wellness Shop": "in Wellness Shops",
    "in Massage Shop": "in Massage Shops",
    "in SPA Shop": "in SPA Shops",
    "in WellnessShop": "in Wellness Shops",
    "in MassageShop": "in Massage Shops",
    "in SPAShop": "in SPA Shops",
    "in WellnessIndustry": "in the Wellness Industry",
    "in MassageSPAIndustry": "in the Massage SPA Industry",
    "inSPAIndustry": "in the SPA Industry",
    "inMassageIndustry": "in the Massage Industry",
    "inWellnessIndustry": "in the Wellness Industry",
    "已渗透 to": "has penetrated into",
    "已渗透": "has penetrated",
    "渗透 to": "penetrated into",
    "渗透to": "penetrated into",
    "渗透到": "penetrated into",
    "成 as": "become",
    "已成 as": "has become",
    "已成as": "has become",
    "已成 为": "has become",
    "已成为": "has become",
    "作为": "as",
    "作 为": "as",
    "as 主": "as main",
    "as主": "as main",
    "as 主选": "as the main choice",
    "as主选": "as the main choice",
    "as 主 要": "as primary",
    "as主要": "as primary",
    "主要": "primary",
    "主要选择": "primary choice",
    "首选": "first choice",
    "首选方案": "preferred solution",
    "推荐方案": "recommended solution",
    "最佳方案": "best solution",
    "理想方案": "ideal solution",
    "合适方案": "suitable solution",
    "适合方案": "appropriate solution",
    "优选方案": "optimized solution",
    "优选": "optimized",
    "优化方案": "optimized solution",
    "最优方案": "optimal solution",
    "最优": "optimal",
    "最佳": "best",
    "最好": "best",
    "最合适": "most suitable",
    "最适合": "most appropriate",
    "最理想": "most ideal",
    "最优秀": "most outstanding",
    "最卓越": "most excellent",
    "最杰出": "most distinguished",
    "最出色": "most brilliant",
    "最棒": "best",
    "最强": "strongest",
    "最弱": "weakest",
    "最高": "highest",
    "最低": "lowest",
    "最大": "largest",
    "最小": "smallest",
    "最多": "most",
    "最少": "least",
    "最快": "fastest",
    "最慢": "slowest",
    "最好": "best",
    "最差": "worst",
    "最新": "newest",
    "最旧": "oldest",
    "最新版": "latest version",
    "最新版本": "latest version",
    "最新功能": "latest features",
    "最新技术": "latest technology",
    "最新趋势": "latest trends",
    "最新动态": "latest updates",
    "最新消息": "latest news",
    "最新资讯": "latest information",
    "最新信息": "latest information",
    "最新数据": "latest data",
    "最新统计": "latest statistics",
    "最新分析": "latest analysis",
    "最新报告": "latest report",
    "最新研究": "latest research",
    "最新成果": "latest achievements",
    "最新发现": "latest findings",
    "最新进展": "latest progress",
    "最新发展": "latest development",
    "最新改进": "latest improvements",
    "最新优化": "latest optimizations",
    "最新升级": "latest upgrade",
    "最新更新": "latest update",
    "最新发布": "latest release",
    "最新推出": "latest launch",
    "最新上市": "latest market launch",
    "最新产品": "latest products",
    "最新服务": "latest services",
    "最新方案": "latest solutions",
    "最新工具": "latest tools",
    "最新平台": "latest platforms",
    "最新系统": "latest systems",
    "最新软件": "latest software",
    "最新应用": "latest applications",
    "最新模块": "latest modules",
    "最新组件": "latest components",
    "最新插件": "latest plugins",
    "最新扩展": "latest extensions",
    "最新配件": "latest accessories",
    "最新设备": "latest devices",
    "最新硬件": "latest hardware",
    "最新器材": "latest equipment",
    "最新设施": "latest facilities",
    "最新装备": "latest gear",
    "最新仪器": "latest instruments",
    "最新仪表": "latest meters",
    "最新工具": "latest tools",
    "最新器具": "latest utensils",
    "最新用品": "latest supplies",
    "最新材料": "latest materials",
    "最新原料": "latest raw materials",
    "最新耗材": "latest consumables",
    "最新资源": "latest resources",
    "最新资产": "latest assets",
    "最新资本": "latest capital",
    "最新资金": "latest funds",
    "最新预算": "latest budget",
    "最新投资": "latest investment",
    "最新收益": "latest returns",
    "最新利润": "latest profits",
    "最新营收": "latest revenue",
    "最新成本": "latest costs",
    "最新费用": "latest expenses",
    "最新价格": "latest prices",
    "最新定价": "latest pricing",
    "最新报价": "latest quotes",
    "最新估价": "latest estimates",
    "最新估值": "latest valuations",
    "最新市值": "latest market value",
    "最新价值": "latest value",
    "最新报价": "latest quote",
    # Common remaining Chinese phrases found in files
    "晋升": "promotion",
    "提": "improve",
    "率": "rate",
    "挽回": "recover",
    "容": "content",
    "考": "examination",
    "增": "increase",
    "疗": "therapy",
    "流失": "churn",
    "忠诚": "loyalty",
    "维": "maintain",
    "反馈": "feedback",
    "利润": "profit",
    "挽留": "retain",
    "命周": "lifecycle",
    "生命周期": "lifecycle",
    "激活": "activation",
    "奖金": "bonus",
    "创新": "innovation",
    "激励": "incentive",
    "心": "center",
    "候": "wait",
    "耗": "consume",
    "职": "position",
    "套餐": "package",
    "离职": "resignation",
    "机": "machine",
    "招聘": "recruitment",
    "积分": "points",
    "则": "rule",
    "级": "level",
    "合同": "contract",
    "制定": "formulate",
    "设计": "design",
    "铺": "spread",
    "率大幅": "rate significantly",
    "大幅": "significantly",
    "分": "allocate",
    "移动": "mobile",
    "制": "system",
    "确": "confirm",
    "收": "collect",
    "指标": "indicator",
    "高峰": "peak",
    "间": "interval",
    "线": "line",
    "因素": "factor",
    "薪": "salary",
    "装修": "renovation",
    "更新": "update",
    "动作": "action",
    "态度": "attitude",
    "领域": "field",
    "普及": "普及化",
    "普及化": "popularization",
    # Additional common words
    "大幅 Increase": "significantly increase",
    "Increase": "increase",
    "大幅Decrease": "significantly decrease",
    "Decrease": "decrease",
    "大幅Optimization": "significantly optimize",
    "大幅 Optimization": "significantly optimize",
    "大幅 提": "significantly improve",
    "提 before": "improve before",
    "提before": "improve before",
    "提before Warning": "early warning",
    "挽留Customer": "retain customer",
    "挽留流失Customer": "retain churned customer",
    "流失Customer": "churned customer",
    "流失 预警": "churn warning",
    "流失预警": "churn warning",
    "Customer 流失": "customer churn",
    "Customer流失": "customer churn",
    "忠诚 度": "loyalty degree",
    "忠诚度": "loyalty degree",
    "忠诚Customer": "loyal customer",
    "维 护": "maintenance",
    "维护": "maintenance",
    "Customer 维护": "customer maintenance",
    "Customer维护": "customer maintenance",
    "反馈 管理": "feedback management",
    "反馈Management": "feedback management",
    "Customer 反馈": "customer feedback",
    "Customer反馈": "customer feedback",
    "利润 分析": "profit analysis",
    "利润Analysis": "profit analysis",
    "激活 策略": "activation strategy",
    "激活Strategy": "activation strategy",
    "Member 激活": "member activation",
    "Member激活": "member activation",
    "奖金 系统": "bonus system",
    "奖金System": "bonus system",
    "Technician 奖金": "technician bonus",
    "Technician奖金": "technician bonus",
    "创新 服务": "innovative service",
    "创新Service": "innovative service",
    "Service 创新": "service innovation",
    "Service创新": "service innovation",
    "激励 方案": "incentive scheme",
    "激励Scheme": "incentive scheme",
    "Technician 激励": "technician incentive",
    "Technician激励": "technician incentive",
    "候 管理": "waiting management",
    "候Management": "waiting management",
    "Customer 候": "customer waiting",
    "Customer候": "customer waiting",
    "耗 材": "consumables",
    "耗材": "consumables",
    "职 位": "position",
    "职位": "position",
    "Technician 职位": "technician position",
    "Technician职位": "technician position",
    "套餐 管理": "package management",
    "套餐Management": "package management",
    "Service 套餐": "service package",
    "Service套餐": "service package",
    "离职 管理": "resignation management",
    "离职Management": "resignation management",
    "Technician 离职": "technician resignation",
    "Technician离职": "technician resignation",
    "招聘 系统": "recruitment system",
    "招聘System": "recruitment system",
    "Technician 招聘": "technician recruitment",
    "Technician招聘": "technician recruitment",
    "积分 系统": "points system",
    "积分System": "points system",
    "Member 积分": "member points",
    "Member积分": "member points",
    "级 管理": "level management",
    "级Management": "level management",
    "Member 级": "member level",
    "Member级": "member level",
    "合同 管理": "contract management",
    "合同Management": "contract management",
    "Technician 合同": "technician contract",
    "Technician合同": "technician contract",
    "制定 策略": "formulate strategy",
    "制定Strategy": "formulate strategy",
    "设计 方案": "design scheme",
    "设计Scheme": "design scheme",
    "Interior 设计": "interior design",
    "Interior设计": "interior design",
    "铺 管理": "shop management",
    "铺Management": "shop management",
    "Store 铺": "store shop",
    "Store铺": "store shop",
    "率 大幅": "rate significantly",
    "率大幅": "rate significantly",
    "Conversion Rate 大幅": "conversion rate significantly",
    "Conversion Rate大幅": "conversion rate significantly",
    "Satisfaction Rate 大幅": "satisfaction rate significantly",
    "Satisfaction Rate大幅": "satisfaction rate significantly",
    "分 配": "allocation",
    "分配": "allocation",
    "Resource 分配": "resource allocation",
    "Resource分配": "resource allocation",
    "移动端 管理": "mobile management",
    "移动端Management": "mobile management",
    "Mobile 移动": "mobile platform",
    "Mobile移动": "mobile platform",
    "制 度": "system",
    "制度": "system",
    "确 认": "confirm",
    "确认": "confirm",
    "Appointment 确认": "appointment confirmation",
    "Appointment确认": "appointment confirmation",
    "收 入": "income",
    "收入": "income",
    "Revenue 收": "revenue collection",
    "Revenue收": "revenue collection",
    "指标 监控": "indicator monitoring",
    "指标Monitoring": "indicator monitoring",
    "Performance 指标": "performance indicator",
    "Performance指标": "performance indicator",
    "高峰 时段": "peak time period",
    "高峰时段": "peak time period",
    "Peak Hour 高峰": "peak hour",
    "Peak Hour高峰": "peak hour",
    "间 管理": "interval management",
    "间Management": "interval management",
    "Time 间": "time interval",
    "Time间": "time interval",
    "线 管理": "line management",
    "线Management": "line management",
    "Product 线": "product line",
    "Product线": "product line",
    "因素 分析": "factor analysis",
    "因素Analysis": "factor analysis",
    "Risk 因素": "risk factor",
    "Risk因素": "risk factor",
    "薪 管理": "salary management",
    "薪Management": "salary management",
    "Technician 薪": "technician salary",
    "Technician薪": "technician salary",
    "装修 设计": "renovation design",
    "装修Design": "renovation design",
    "Interior 装修": "interior renovation",
    "Interior装修": "interior renovation",
    "更新 管理": "update management",
    "更新Management": "update management",
    "System 更新": "system update",
    "System更新": "system update",
    "动作 追踪": "action tracking",
    "动作Tracking": "action tracking",
    "Customer 动作": "customer action",
    "Customer动作": "customer action",
    # Additional single words
    "晋升": "promotion",
    "晋升 管理": "promotion management",
    "晋升Management": "promotion management",
    "Technician 晋升": "technician promotion",
    "Technician晋升": "technician promotion",
    "提 升": "improve",
    "提升": "improve",
    "Performance 提": "performance improvement",
    "Performance提": "performance improvement",
    "挽 回": "recover",
    "挽回": "recover",
    "Customer 挽回": "customer recovery",
    "Customer挽回": "customer recovery",
    "内 容": "content",
    "内容": "content",
    "Marketing 容": "marketing content",
    "Marketing容": "marketing content",
    "考 核": "examination",
    "考核": "examination",
    "Technician 考": "technician examination",
    "Technician考": "technician examination",
    "增 加": "increase",
    "增加": "increase",
    "Revenue 增": "revenue increase",
    "Revenue增": "revenue increase",
    "治 疗": "therapy",
    "治疗": "therapy",
    "Treatment 疗": "treatment therapy",
    "Treatment疗": "treatment therapy",
    "流 失": "churn",
    "流失": "churn",
    "Customer流失": "customer churn",
    "诚 诚": "loyalty",
    "忠诚": "loyalty",
    "维 维": "maintenance",
    "维 维护": "maintenance",
    "维护": "maintenance",
    "反 反馈": "feedback",
    "反馈": "feedback",
    "利 利润": "profit",
    "利润": "profit",
    "挽 挽留": "retain",
    "挽留": "retain",
    "命 命周": "lifecycle",
    "命周": "lifecycle",
    "生命周": "lifecycle",
    "激 激活": "activation",
    "激活": "activation",
    "奖 奖金": "bonus",
    "奖金": "bonus",
    "创 创新": "innovation",
    "创新": "innovation",
    "激 激励": "incentive",
    "激励": "incentive",
    "中 心": "center",
    "中心": "center",
    "等 候": "waiting",
    "等候": "waiting",
    "消 耗": "consume",
    "消耗": "consume",
    "任 职": "position",
    "任职": "position",
    "套 套餐": "package",
    "套餐": "package",
    "离 离职": "resignation",
    "离职": "resignation",
    "机 机": "machine",
    "招聘": "recruitment",
    "积 积分": "points",
    "积分": "points",
    "规 则": "rule",
    "规则": "rule",
    "等 级": "level",
    "等级": "level",
    "合 合同": "contract",
    "合同": "contract",
    "制 制定": "formulate",
    "制定": "formulate",
    "设 设计": "design",
    "设计": "design",
    "铺 铺": "spread",
    "分 分": "allocate",
    "移 移动": "mobile",
    "移动": "mobile",
    "体 制": "system",
    "体制": "system",
    "明 确": "confirm",
    "明确": "confirm",
    "收 收": "collect",
    "指 指标": "indicator",
    "指标": "indicator",
    "高 高峰": "peak",
    "高峰": "peak",
    "时 间": "interval",
    "时间": "time",
    "间": "interval",
    "线 线": "line",
    "因 因素": "factor",
    "因素": "factor",
    "工 薪": "salary",
    "薪": "salary",
    "装 装修": "renovation",
    "装修": "renovation",
    "更 更新": "update",
    "更新": "update",
    "动 动作": "action",
    "动作": "action",
    # Final cleanup for punctuation and mixed text
    "、": ", ",
    "。": ". ",
    "：": ": ",
    "；": "; ",
    "（": "(",
    "）": ")",
    "【": "[",
    "】": "]",
    "强": "strong",
    "价": "price",
    "或": "or",
    "种": "type",
    "手": "manual",
    "批": "batch",
    "准": "accurate",
    "快": "fast",
    "品": "product",
    "量": "amount",
    "端": "end",
    "重": "important",
    "名": "name",
    "小": "small",
    "简": "simple",
    "库": "library",
    "易": "easy",
    "数": "data",
    "发": "send",
    "传": "transmit",
    "突": "breakthrough",
    "向": "direction",
    "洞": "insight",
    "人": "person",
    "几": "several",
    "著": "notable",
    "工": "work",
    "歌": "sing",
    "时": "time",
    "问": "question",
    "自": "self",
    "调": "adjust",
    "扩": "expand",
    "式": "mode",
    "券": "coupon",
    "型": "type",
    "账": "account",
    "成": "become",
    "规": "standard",
    "类": "category",
    "告": "report",
    "业": "business",
    "晰": "clear",
    "排": "arrange",
    "放": "release",
    "目": "goal",
    "电": "electric",
    "编": "edit",
    "纠": "correct",
    "稳": "stable",
    "酬": "salary",
    # Punctuation fixes
    "、": ", ",
    "。": ".",
    "：": ":",
    "；": ";",
    "（": "(",
    "）": ")",
    # Comprehensive pattern fixes
    "In-depth AnalysisMassageSPA Industry": "In-depth Analysis of Massage SPA Industry",
    "Massage ShopService ProjectManagement Core 价value": "Massage Shop Service Project Management Core Value",
    "Massage ShopService ProjectManagementSystem2026ProfessionalReview": "Massage Shop Service Project Management System 2026 Professional Review",
    "ProjectFine-grainedOperations": "Project Fine-grained Operations",
    "Service Project is revenue DirectSource": "Service Project is a Direct Revenue Source",
    "such as Direct impact": "and other features directly impact",
    "Data shows,System ized": "Data shows that systematized",
    "System ized": "systematized",
    "Facesunique challenges": "faces unique challenges",
    "Faces unique": "faces unique",
    "MassageShopFaces": "Massage Shop faces",
    "Massage ShopFaces": "Massage Shop faces",
    "Massage、SPA、Wellness、Physiotherapy such as Multiple 种 ProjectType": "Massage, SPA, Wellness, Physiotherapy and other multiple project types",
    "Multiple 种": "Multiple types",
    "种 ProjectType": "types of projects",
    "different ProjectPricingStrategyVaried": "different project pricing strategies vary",
    "different ProjectServiceDurationVaried": "different project service durations vary",
    "different ProjectConsumablesConsumptionVaried": "different project consumables consumption varies",
    "different Project needs Matching different SkillsTechnician": "different projects need matching with different skilled technicians",
    "different SkillsTechnician": "different skilled technicians",
    "needs Matching": "need matching",
    "TrackingOptimization": "tracking and optimization",
    "needs TrackingOptimization": "needs tracking and optimization",
    "Time PeriodDynamicPricing": "time period dynamic pricing",
    "MemberDiscountPricingAutomatic Apply": "member discount pricing automatic application",
    "Automatic Apply": "automatic application",
    "PricingOptimization recommendations": "pricing optimization recommendations",
    "ProjectConsumablesOptimization recommendations": "project consumables optimization recommendations",
    "ProjectIssues continuous Identify": "project issues continuous identification",
    "ProjectOptimization recommendations": "project optimization recommendations",
    "ProjectOptimizationLaunchExecute": "project optimization launch execution",
    "AI will Optimization": "AI will optimize",
    "Optimization Project Pricing": "optimize project pricing",
    "based on Customer Flow、Time Period、CompetitionDynamicAdjustmentPricing": "based on customer flow, time period, and competition for dynamic pricing adjustment",
    "CompetitionDynamicAdjustmentPricing": "competition dynamic pricing adjustment",
    "DynamicAdjustmentPricing": "dynamic pricing adjustment",
    "AI will prediction": "AI will predict",
    "predictionProjectConsumablesConsumption": "predict project consumables consumption",
    "AI will DeepAnalysis": "AI will deeply analyze",
    "DeepAnalysisProjectEffectiveness": "deeply analyze project effectiveness",
    "IdentifyProjectIssues": "identify project issues",
    "RecommendProjectOptimization Solution": "recommend project optimization solution",
    "Project willand": "project will",
    "willand Customer": "will integrate with customer",
    "CustomerFlowDataDeepIntegration": "customer flow data deep integration",
    "DataDeepIntegration": "data deep integration",
    "ProjectPricingAutomatic Follow": "project pricing will automatically follow",
    "Automatic FollowCustomer Flow": "automatically follow customer flow",
    "FollowCustomer FlowDynamicAdjustment": "follow customer flow dynamic adjustment",
    "DynamicAdjustment": "dynamic adjustment",
    "Project willthrough": "project will",
    "willthrough VisualizationChartsDisplay": "will display through visualization charts",
    "VisualizationChartsDisplay": "visualization charts display",
    "ProjectStatusClear Overview": "project status clear overview",
    "Clear Overview": "clear overview",
    "Service ProjectTypesComplex degree": "service project types complexity",
    "Complex degree": "complexity",
    "PricingStrategy needs strongchoose": "for strong pricing strategy needs, choose",
    "ConsumablesTracking needs strongchoose": "for strong consumables tracking needs, choose",
    "EffectivenessTracking needs strongchoose": "for strong effectiveness tracking needs, choose",
    "needs strongchoose": "for strong needs, choose",
    "或 Zenoti": "or Zenoti",
    "或 Mindbody": "or Mindbody",
    "或 Vagaro": "or Vagaro",
    "或 LogicManager": "or LogicManager",
    "choose Mindbody 或 Zenoti": "choose Mindbody or Zenoti",
    "choose MeiYeBang 或 Mindbody": "choose MeiYeBang or Mindbody",
    "choose MeiYeBang 或 Vagaro": "choose MeiYeBang or Vagaro",
    "Comprehensive recommendation:Large-scale Chain Massage Brand choose Mindbody 或 Zenoti": "Comprehensive recommendation: Large-scale Chain Massage Brand choose Mindbody or Zenoti",
    "Medium-scaleSPA Shop choose MeiYeBangProjectModule 或 Vagaro": "Medium-scale SPA Shop choose MeiYeBang Project Module or Vagaro",
    "MeiYeBangProjectModule 或 Vagaro": "MeiYeBang Project Module or Vagaro",
    "Small-scale Single Shop choose DianWuTongProjectFunction": "Small-scale Single Shop choose DianWuTong Project Function",
    "DianWuTongProjectFunction": "DianWuTong Project Function",
    "Built-in Project Module ManagementSoftware": "Built-in Project Module Management Software",
    "Localized AdaptationComprehensive": "Localized Adaptation Comprehensive",
    "Annual fee Approximately 2000-3000 RMB": "Annual fee Approximately 2000-3000 RMB",
    "ProjectOptimizationFunctionOutstanding": "Project Optimization Function Outstanding",
    "Cost-effective Project Management": "Cost-effective Project Management",
    "Suitable forLarge-scale Chain Massage Brand": "Suitable for Large-scale Chain Massage Brand",
    "Suitable forDon't want to Deploy Multiple Systems": "Suitable for massage shops that don't want to deploy multiple systems",
    "Don't want toDeployMultipleSystem Small-scaleMassageShop": "Small-scale massage shop not wanting to deploy multiple systems",
    "Local Wellness SoftwareProjectFunction": "Local Wellness Software Project Function",
    "Global Leading Management PlatformProjectFunction": "Global Leading Management Platform Project Function",
    "Next-generation Cloud Management PlatformProject": "Next-generation Cloud Management Platform Project",
    "Core FunctionsModule": "Core Functions Module",
    "Core FunctionsComparison table": "Core Functions Comparison Table",
    "continuous Optimization": "Continuous Optimization",
    "continuous Identify": "Continuous Identification",
    "AIRecommend": "AI Recommendations",
    "Budget Levelchoose Mindbody": "Ample budget choose Mindbody",
    "limited budgetchoose MeiYeBang 或 Vagaro": "Limited budget choose MeiYeBang or Vagaro",
    "Medium-scaleSPA Shop": "Medium-scale SPA Shop",
    # Final comprehensive fixes
    "In-depth Analysis": "In-depth Analysis",
    "AnalysisMassageSPA Industry": "Analysis of Massage SPA Industry",
    "HelpWellness ShopImplement": "Help Wellness Shop Implement",
    "HelpWellnessShopImplement": "Help Wellness Shop Implement",
    "Service Project Fine-grained Operations": "Service Project Fine-grained Operations",
    "Optimization Project Revenue": "Optimize Project Revenue",
    "ProjectOperationsStrategy": "Project Operations Strategy",
    "Mainstream Solution Comparison": "Mainstream Solution Comparison",
    "Multiple Functions and Price Comparison": "Multiple Functions and Price Comparison",
    "Find the Most Suitable your Solution": "Find Your Most Suitable Solution",
    "Find the Most Suitable": "Find Your Most Suitable",
    "your Solution": "Your Solution",
    "Professional Review helps you make a Decision": "Professional Review Helps You Make a Decision",
    "ProfessionalReview helps you Decision": "Professional Review Helps You Make a Decision",
    "Massage ShopService ProjectManagement": "Massage Shop Service Project Management",
    "ServiceProjectManagement": "Service Project Management",
    "MassageShopServiceProjectManagement": "Massage Shop Service Project Management",
    "Massage Shop": "Massage Shop",
    "MassageShop": "Massage Shop",
    "Wellness Shop": "Wellness Shop",
    "WellnessShop": "Wellness Shop",
    "SPA Shop": "SPA Shop",
    "SPAShop": "SPA Shop",
}

def contains_chinese(text):
    """Check if text contains Chinese characters."""
    if not text:
        return False
    return bool(re.search('[一-鿿]', str(text)))

def translate_text(text):
    """Translate Chinese text to English using the mapping."""
    if not text or not contains_chinese(text):
        return text

    # Apply translations
    result = text
    for chinese, english in TRANSLATION_MAP.items():
        result = result.replace(chinese, english)

    # Additional cleanup patterns
    result = re.sub(r'\s+', ' ', result)  # Remove extra spaces
    result = result.strip()

    return result

def translate_json_file(filepath):
    """Translate Chinese content in JSON file to English."""
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)

    # Translate fields
    if 'title' in data:
        data['title'] = translate_text(data['title'])

    if 'description' in data:
        data['description'] = translate_text(data['description'])

    if 'content' in data:
        data['content'] = translate_text(data['content'])

    if 'author' in data:
        data['author'] = translate_text(data['author'])

    if 'seo_keywords' in data:
        data['seo_keywords'] = [translate_text(kw) for kw in data['seo_keywords']]

    # Ensure language is en-US
    data['language'] = 'en-US'

    # Write back
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    return filepath

def main():
    """Process all files in the directory."""
    directory = '/Users/gejiayu/owner/seo/data/massage-spa-wellness-tools'

    # Get list of files to translate
    files_to_translate = []
    for filename in sorted(os.listdir(directory)):
        if filename.endswith('.json'):
            filepath = os.path.join(directory, filename)
            try:
                with open(filepath, 'r', encoding='utf-8') as f:
                    data = json.load(f)
                    has_chinese = False
                    for field in ['title', 'description', 'content', 'author', 'seo_keywords']:
                        if field in data:
                            if field == 'seo_keywords':
                                for keyword in data[field]:
                                    if contains_chinese(keyword):
                                        has_chinese = True
                                        break
                            else:
                                if contains_chinese(data[field]):
                                    has_chinese = True
                                    break
                    if has_chinese:
                        files_to_translate.append(filepath)
            except Exception as e:
                print(f'Error reading {filename}: {e}')

    # Translate files
    print(f'Total files to translate: {len(files_to_translate)}')
    for filepath in files_to_translate:
        try:
            translate_json_file(filepath)
            print(f'Translated: {os.path.basename(filepath)}')
        except Exception as e:
            print(f'Error translating {filepath}: {e}')

    print('Translation complete!')

if __name__ == '__main__':
    main()