#!/usr/bin/env python3
"""
批量翻译 furniture-home-rental-tools 英文JSON到中文
遵循pSEO Production Engine标准
"""

import json
import os
import re
from pathlib import Path

# 英文到中文关键词映射
KEYWORD_TRANSLATIONS = {
    "furniture rental": "家具租赁",
    "inventory management": "库存管理",
    "software": "软件",
    "platform": "平台",
    "system": "系统",
    "tracking": "追踪",
    "warehouse": "仓库",
    "management": "管理",
    "rental": "租赁",
    "furniture": "家具",
    "home": "家居",
    "tools": "工具",
    "solution": "解决方案",
    "software platforms": "软件平台",
    "control": "控制",
    "stock": "库存",
    "availability": "可用性",
    "organization": "组织",
    "optimization": "优化",
    "analytics": "分析",
    "reporting": "报告",
    "dashboard": "仪表板",
    "crm": "客户关系管理",
    "customer": "客户",
    "portal": "门户",
    "maintenance": "维护",
    "security": "安全",
    "insurance": "保险",
    "delivery": "配送",
    "logistics": "物流",
    "pricing": "定价",
    "quoting": "报价",
    "reservation": "预订",
    "booking": "预订",
    "payment": "支付",
    "processing": "处理",
    "signature": "签名",
    "document": "文档",
    "storage": "存储",
    "backup": "备份",
    "data": "数据",
    "protection": "保护",
    "compliance": "合规",
    "audit": "审计",
    "trail": "轨迹",
    "automation": "自动化",
    "workflow": "工作流",
    "integration": "集成",
    "api": "API接口",
    "mobile": "移动",
    "apps": "应用",
    "smartphone": "智能手机",
    "rfid": "RFID射频识别",
    "barcode": "条形码",
    "scanning": "扫描",
    "iot": "物联网",
    "monitoring": "监控",
    "condition": "条件",
    "grading": "分级",
    "damage": "损坏",
    "assessment": "评估",
    "return": "退货",
    "pickup": "取货",
    "scheduling": "调度",
    "fleet": "车队",
    "asset": "资产",
    "lifecycle": "生命周期",
    "replacement": "更换",
    "timing": "时机",
    "disposal": "处置",
    "planning": "规划",
    "budget": "预算",
    "financial": "财务",
    "revenue": "收入",
    "forecasting": "预测",
    "performance": "性能",
    "kpi": "关键绩效指标",
    "goal": "目标",
    "setting": "设定",
    "growth": "增长",
    "scaling": "扩展",
    "enterprise": "企业",
    "small business": "中小企业",
    "startup": "初创企业",
    "franchise": "特许经营",
    "b2b": "企业对企业",
    "partnership": "合作伙伴",
    "team": "团队",
    "coordination": "协调",
    "staff": "员工",
    "training": "培训",
    "productivity": "生产力",
    "efficiency": "效率",
    "quality": "质量",
    "control": "控制",
    "process": "流程",
    "optimization": "优化",
    "innovation": "创新",
    "technology": "技术",
    "adoption": "采用",
    "digital": "数字化",
    "transformation": "转型",
    "migration": "迁移",
    "cloud": "云端",
    "saas": "SaaS软件即服务",
    "hybrid": "混合",
    "on-premise": "本地部署",
    "multi-location": "多地点",
    "geographic": "地理",
    "distribution": "分布",
    "peak": "高峰",
    "capacity": "容量",
    "seasonal": "季节性",
    "demand": "需求",
    "prediction": "预测",
    "market": "市场",
    "research": "研究",
    "analysis": "分析",
    "trend": "趋势",
    "competitor": "竞争对手",
    "monitoring": "监控",
    "benchmark": "基准",
    "industry": "行业",
    "legal": "法律",
    "contract": "合同",
    "agreement": "协议",
    "template": "模板",
    "generation": "生成",
    "regulatory": "监管",
    "recovery": "恢复",
    "change": "变更",
    "notification": "通知",
    "alert": "警报",
    "reminder": "提醒",
    "update": "更新",
    "version": "版本",
    "history": "历史",
    "record": "记录",
    "archive": "归档",
    "user": "用户",
    "permission": "权限",
    "access": "访问",
    "onboarding": "入职",
    "subscription": "订阅",
    "student housing": "学生住房",
    "corporate housing": "企业住房",
    "event": "活动",
    "leasing": "租赁",
    "packages": "套餐",
    "guide": "指南",
    "comparison": "对比",
    "review": "评测",
}

def translate_keywords(keywords):
    """翻译关键词数组"""
    translated = []
    for kw in keywords:
        # 尝试完整匹配
        if kw.lower() in KEYWORD_TRANSLATIONS:
            translated.append(KEYWORD_TRANSLATIONS[kw.lower()])
        else:
            # 部分匹配和替换
            translated_kw = kw
            for en, zh in KEYWORD_TRANSLATIONS.items():
                if en in translated_kw.lower():
                    translated_kw = translated_kw.replace(en, zh)
            translated.append(translated_kw)
    return translated

def translate_title(title):
    """翻译标题"""
    # 基础翻译映射
    title_map = {
        "Top 10": "十大最佳",
        "Best": "最佳",
        "Comparison": "对比评测",
        "Guide": "指南",
        "Review": "评测",
        "Platforms": "平台",
        "Software": "软件",
        "Systems": "系统",
        "Tools": "工具",
        "Solutions": "解决方案",
        "2026": "2026年",
        "Furniture Rental": "家具租赁",
        "Inventory Management": "库存管理",
        "Warehouse": "仓库",
        "Organization": "组织",
        "Tracking": "追踪",
        "Control": "控制",
        "Stock": "库存",
        "Analytics": "分析",
        "Reporting": "报告",
        "Dashboard": "仪表板",
        "CRM": "客户关系管理",
        "Customer": "客户",
        "Portal": "门户",
        "Maintenance": "维护",
        "Security": "安全",
        "Insurance": "保险",
        "Delivery": "配送",
        "Logistics": "物流",
        "Pricing": "定价",
        "Quoting": "报价",
        "Reservation": "预订",
        "Payment": "支付",
        "Processing": "处理",
        "Signature": "签名",
        "Document": "文档",
        "Storage": "存储",
        "Backup": "备份",
        "Data": "数据",
        "Protection": "保护",
        "Compliance": "合规",
        "Audit": "审计",
        "Trail": "轨迹",
        "Automation": "自动化",
        "Workflow": "工作流",
        "Integration": "集成",
        "API": "API接口",
        "Mobile": "移动",
        "Apps": "应用",
        "RFID": "RFID射频识别",
        "Barcode": "条形码",
        "Scanning": "扫描",
        "IoT": "物联网",
        "Monitoring": "监控",
        "Condition": "条件",
        "Grading": "分级",
        "Damage": "损坏",
        "Assessment": "评估",
        "Return": "退货",
        "Pickup": "取货",
        "Scheduling": "调度",
        "Fleet": "车队",
        "Asset": "资产",
        "Lifecycle": "生命周期",
        "Replacement": "更换",
        "Timing": "时机",
        "Disposal": "处置",
        "Planning": "规划",
        "Budget": "预算",
        "Financial": "财务",
        "Revenue": "收入",
        "Forecasting": "预测",
        "Performance": "性能",
        "KPI": "关键绩效指标",
        "Goal": "目标",
        "Setting": "设定",
        "Growth": "增长",
        "Scaling": "扩展",
        "Enterprise": "企业",
        "Small Business": "中小企业",
        "Startup": "初创企业",
        "Franchise": "特许经营",
        "B2B": "企业对企业",
        "Partnership": "合作伙伴",
        "Team": "团队",
        "Coordination": "协调",
        "Staff": "员工",
        "Training": "培训",
        "Productivity": "生产力",
        "Efficiency": "效率",
        "Quality": "质量",
        "Process": "流程",
        "Innovation": "创新",
        "Technology": "技术",
        "Adoption": "采用",
        "Digital": "数字化",
        "Transformation": "转型",
        "Migration": "迁移",
        "Cloud": "云端",
        "SaaS": "SaaS软件即服务",
        "Hybrid": "混合",
        "On-Premise": "本地部署",
        "Multi-Location": "多地点",
        "Geographic": "地理",
        "Distribution": "分布",
        "Peak": "高峰",
        "Capacity": "容量",
        "Seasonal": "季节性",
        "Demand": "需求",
        "Prediction": "预测",
        "Market": "市场",
        "Research": "研究",
        "Analysis": "分析",
        "Trend": "趋势",
        "Competitor": "竞争对手",
        "Benchmark": "基准",
        "Industry": "行业",
        "Legal": "法律",
        "Contract": "合同",
        "Agreement": "协议",
        "Template": "模板",
        "Generation": "生成",
        "Regulatory": "监管",
        "Recovery": "恢复",
        "Change": "变更",
        "Notification": "通知",
        "Alert": "警报",
        "Reminder": "提醒",
        "Update": "更新",
        "Version": "版本",
        "History": "历史",
        "Record": "记录",
        "Archive": "归档",
        "User": "用户",
        "Permission": "权限",
        "Access": "访问",
        "Onboarding": "入职",
        "Subscription": "订阅",
        "Student Housing": "学生住房",
        "Corporate Housing": "企业住房",
        "Event": "活动",
        "Leasing": "租赁",
        "Packages": "套餐",
        "Home": "家居",
        "Value": "价值",
        "Peak Capacity": "高峰容量",
        "Staff Management": "员工管理",
        "Small Business": "中小企业",
        "Software Platforms": "软件平台",
        "Guide": "完整指南",
        "Startp Management": "初创企业管理",
        "Technology Adoption": "技术采用",
        "Trend Tracking": "趋势追踪",
        "Update Tracking": "更新追踪",
        "User Permission": "用户权限",
        "Value Tracking": "价值追踪",
        "Version Control": "版本控制",
        "Warehouse Organization": "仓库组织",
        "Home Furniture": "家居家具",
        "Student Housing Furniture": "学生住房家具",
    }

    result = title
    for en, zh in title_map.items():
        if en in result:
            result = result.replace(en, zh)

    # 清理格式
    result = result.replace(":", "：")
    result = result.replace("-", " ")

    return result.strip()

def translate_content(content):
    """翻译HTML内容到中文"""
    # 简化翻译 - 保持HTML结构，翻译关键术语
    translations = {
        "Introduction to": "介绍",
        "Essential Features for": "核心功能评测",
        "Top Furniture Rental": "顶级家具租赁",
        "Platforms Comparison": "平台对比",
        "Deep Review": "深度评测",
        "Analysis": "分析",
        "Evaluation": "评估",
        "Review": "评测",
        "Considerations": "考虑因素",
        "Future Trends in": "未来趋势",
        "Furniture Rental": "家具租赁",
        "Inventory Management": "库存管理",
        "Software": "软件",
        "Platforms": "平台",
        "2026": "2026年",
        "provides": "提供",
        "delivers": "交付",
        "specializes in": "专注于",
        "concentrates on": "集中于",
        "offers": "提供",
        "enables": "使能够",
        "supports": "支持",
        "manages": "管理",
        "tracks": "追踪",
        "monitors": "监控",
        "optimizes": "优化",
        "analyzes": "分析",
        "integrates": "集成",
        "automates": "自动化",
        "The platform": "该平台",
        "platform's": "平台的",
        "feature": "功能",
        "features": "功能",
        "capability": "能力",
        "capabilities": "能力",
        "tool": "工具",
        "tools": "工具",
        "system": "系统",
        "systems": "系统",
        "solution": "解决方案",
        "solutions": "解决方案",
        "rental": "租赁",
        "furniture": "家具",
        "inventory": "库存",
        "warehouse": "仓库",
        "tracking": "追踪",
        "management": "管理",
        "availability": "可用性",
        "stock": "库存",
        "organization": "组织",
        "optimization": "优化",
        "analytics": "分析",
        "reporting": "报告",
        "customer": "客户",
        "portal": "门户",
        "maintenance": "维护",
        "security": "安全",
        "insurance": "保险",
        "delivery": "配送",
        "logistics": "物流",
        "pricing": "定价",
        "quoting": "报价",
        "reservation": "预订",
        "payment": "支付",
        "signature": "签名",
        "document": "文档",
        "storage": "存储",
        "backup": "备份",
        "data": "数据",
        "protection": "保护",
        "compliance": "合规",
        "audit": "审计",
        "trail": "轨迹",
        "automation": "自动化",
        "workflow": "工作流",
        "integration": "集成",
        "api": "API接口",
        "mobile": "移动",
        "apps": "应用",
        "smartphone": "智能手机",
        "rfid": "RFID射频识别",
        "barcode": "条形码",
        "scanning": "扫描",
        "iot": "物联网",
        "monitoring": "监控",
        "condition": "条件",
        "grading": "分级",
        "damage": "损坏",
        "assessment": "评估",
        "return": "退货",
        "pickup": "取货",
        "scheduling": "调度",
        "fleet": "车队",
        "asset": "资产",
        "lifecycle": "生命周期",
        "replacement": "更换",
        "timing": "时机",
        "disposal": "处置",
        "planning": "规划",
        "budget": "预算",
        "financial": "财务",
        "revenue": "收入",
        "forecasting": "预测",
        "performance": "性能",
        "kpi": "关键绩效指标",
        "goal": "目标",
        "setting": "设定",
        "growth": "增长",
        "scaling": "扩展",
        "enterprise": "企业",
        "small business": "中小企业",
        "startup": "初创企业",
        "franchise": "特许经营",
        "b2b": "企业对企业",
        "partnership": "合作伙伴",
        "team": "团队",
        "coordination": "协调",
        "staff": "员工",
        "training": "培训",
        "productivity": "生产力",
        "efficiency": "效率",
        "quality": "质量",
        "control": "控制",
        "process": "流程",
        "innovation": "创新",
        "technology": "技术",
        "adoption": "采用",
        "digital": "数字化",
        "transformation": "转型",
        "migration": "迁移",
        "cloud": "云端",
        "saas": "SaaS软件即服务",
        "hybrid": "混合",
        "on-premise": "本地部署",
        "multi-location": "多地点",
        "geographic": "地理",
        "distribution": "分布",
        "peak": "高峰",
        "capacity": "容量",
        "seasonal": "季节性",
        "demand": "需求",
        "prediction": "预测",
        "market": "市场",
        "research": "研究",
        "analysis": "分析",
        "trend": "趋势",
        "competitor": "竞争对手",
        "benchmark": "基准",
        "industry": "行业",
        "legal": "法律",
        "contract": "合同",
        "agreement": "协议",
        "template": "模板",
        "generation": "生成",
        "regulatory": "监管",
        "recovery": "恢复",
        "change": "变更",
        "notification": "通知",
        "alert": "警报",
        "reminder": "提醒",
        "update": "更新",
        "version": "版本",
        "history": "历史",
        "record": "记录",
        "archive": "归档",
        "user": "用户",
        "permission": "权限",
        "access": "访问",
        "onboarding": "入职",
        "subscription": "订阅",
        "student housing": "学生住房",
        "corporate housing": "企业住房",
        "event": "活动",
        "leasing": "租赁",
        "packages": "套餐",
        "home": "家居",
        "Best": "最佳",
        "Top": "顶级",
        "Compare": "对比",
        "Review": "评测",
        "Key Features": "关键功能",
        "Price Range": "价格范围",
        "Best For": "适用对象",
        "Category": "类别",
        "Platform": "平台",
        "pros": "优点",
        "cons": "缺点",
        "question": "问题",
        "answer": "答案",
        "FAQ": "常见问题",
    }

    result = content
    for en, zh in translations.items():
        # 简单替换（保持HTML标签）
        pattern = r'(?<!["\'])(' + re.escape(en) + r')(?!["\'])'
        result = re.sub(pattern, zh, result, flags=re.IGNORECASE)

    return result

def process_file(en_file_path, zh_dir):
    """处理单个JSON文件"""
    with open(en_file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    # 翻译各个字段
    zh_data = {
        "title": translate_title(data.get("title", "")),
        "description": translate_title(data.get("description", "")),
        "content": translate_content(data.get("content", "")),
        "seo_keywords": translate_keywords(data.get("seo_keywords", [])),
        "slug": data.get("slug", ""),
        "published_at": "2026-05-02",  # 使用当前日期
        "author": "家具租赁行业专家",
        "pros_and_cons": {
            "pros": [translate_content(p) for p in data.get("pros_and_cons", {}).get("pros", [])],
            "cons": [translate_content(c) for c in data.get("pros_and_cons", {}).get("cons", [])]
        },
        "faq": [
            {
                "question": translate_content(faq.get("question", "")),
                "answer": translate_content(faq.get("answer", ""))
            }
            for faq in data.get("faq", [])
        ],
        "language": "zh-CN",
        "canonical_link": f"https://www.housecar.life/zh/posts/{data.get('slug', '')}",
        "alternate_links": {
            "en-US": f"https://www.housecar.life/posts/{data.get('slug', '')}",
            "zh-CN": f"https://www.housecar.life/zh/posts/{data.get('slug', '')}"
        }
    }

    # 保存中文JSON
    zh_file_path = os.path.join(zh_dir, os.path.basename(en_file_path))
    with open(zh_file_path, 'w', encoding='utf-8') as f:
        json.dump(zh_data, f, ensure_ascii=False, indent=2)

    return zh_file_path

def main():
    en_dir = "/Users/gejiayu/owner/seo/data/furniture-home-rental-tools"
    zh_dir = "/Users/gejiayu/owner/seo/data/zh/furniture-home-rental-tools"

    # 获取所有JSON文件
    en_files = sorted(Path(en_dir).glob("*.json"))

    print(f"开始处理 {len(en_files)} 个文件...")

    processed = 0
    for en_file in en_files:
        zh_file = process_file(str(en_file), zh_dir)
        processed += 1
        print(f"[{processed}/{len(en_files)}] 已处理: {os.path.basename(zh_file)}")

    print(f"\n✅ 完成！已生成 {processed} 个中文JSON文件")

if __name__ == "__main__":
    main()