#!/usr/bin/env python3
"""
Script to translate Chinese seo_keywords to English in JSON files.
Processes files in batches of 100.
"""

import json
import os
import re
from pathlib import Path

# Comprehensive translation dictionary for common SEO keywords
TRANSLATION_DICT = {
    # General terms
    "管理": "management",
    "系统": "system",
    "软件": "software",
    "工具": "tools",
    "平台": "platform",
    "解决方案": "solution",
    "评测": "review",
    "对比": "comparison",
    "分析": "analysis",
    "优化": "optimization",
    "自动化": "automation",
    "智能化": "intelligent",
    "数字化": "digital",
    "监控": "monitoring",
    "追踪": "tracking",
    "调度": "scheduling",
    "预警": "alert",
    "预测": "prediction",
    "诊断": "diagnosis",
    "维护": "maintenance",
    "保养": "maintenance",
    "维修": "repair",
    "检查": "inspection",
    "测试": "testing",
    "质量": "quality",
    "安全": "safety",
    "合规": "compliance",
    "风险": "risk",
    "控制": "control",
    "流程": "process",
    "效率": "efficiency",
    "成本": "cost",
    "预算": "budget",
    "财务": "finance",
    "结算": "settlement",
    "发票": "invoice",
    "合同": "contract",
    "客户": "customer",
    "用户": "user",
    "员工": "employee",
    "团队": "team",
    "培训": "training",
    "服务": "service",
    "支持": "support",
    "体验": "experience",
    "满意度": "satisfaction",
    "忠诚度": "loyalty",
    "留存": "retention",
    "转化": "conversion",
    "营销": "marketing",
    "推广": "promotion",
    "销售": "sales",
    "采购": "procurement",
    "供应链": "supply chain",
    "物流": "logistics",
    "配送": "delivery",
    "库存": "inventory",
    "备件": "spare parts",
    "资产": "asset",
    "设备": "equipment",
    "产品": "product",
    "商品": "goods",
    "订单": "order",
    "预订": "booking",
    "预约": "reservation",
    "租赁": "rental",
    "出租": "rental",
    "借用": "loan",
    "归还": "return",
    "交接": "handover",
    "安装": "installation",
    "配置": "configuration",
    "设置": "settings",
    "参数": "parameter",
    "数据": "data",
    "报表": "report",
    "统计": "statistics",
    "指标": "metrics",
    "评估": "evaluation",
    "评分": "rating",
    "排名": "ranking",
    "筛选": "filtering",
    "搜索": "search",
    "查询": "query",
    "导入": "import",
    "导出": "export",
    "同步": "sync",
    "备份": "backup",
    "恢复": "recovery",
    "更新": "update",
    "升级": "upgrade",
    "版本": "version",
    "集成": "integration",
    "接口": "interface",
    "连接": "connection",
    "对接": "integration",
    "扩展": "extension",
    "插件": "plugin",
    "模块": "module",
    "组件": "component",
    "功能": "function",
    "特性": "feature",
    "能力": "capability",
    "性能": "performance",
    "稳定性": "stability",
    "可用性": "availability",
    "可靠性": "reliability",
    "兼容性": "compatibility",
    "灵活性": "flexibility",
    "可扩展性": "scalability",
    "易用性": "usability",
    "便捷性": "convenience",
    "专业性": "professionalism",
    "定制": "customization",
    "个性化": "personalization",
    "多语言": "multilingual",
    "国际化": "internationalization",
    "本地化": "localization",
    "移动端": "mobile",
    "桌面": "desktop",
    "云端": "cloud",
    "在线": "online",
    "实时": "real-time",
    "即时": "instant",
    "快速": "fast",
    "高效": "efficient",
    "精准": "precise",
    "准确": "accurate",
    "智能": "smart",
    "自动": "automatic",
    "手动": "manual",
    "批量": "batch",
    "单次": "single",
    "定时": "scheduled",
    "周期": "cycle",
    "频率": "frequency",
    "时长": "duration",
    "期限": "period",
    "到期": "expiry",
    "续约": "renewal",
    "提醒": "reminder",
    "通知": "notification",
    "消息": "message",
    "邮件": "email",
    "短信": "SMS",
    "推送": "push",
    "权限": "permission",
    "认证": "authentication",
    "授权": "authorization",
    "登录": "login",
    "注册": "registration",
    "账户": "account",
    "角色": "role",
    "部门": "department",
    "组织": "organization",
    "企业": "enterprise",
    "公司": "company",
    "商家": "merchant",
    "店铺": "store",
    "品牌": "brand",
    "商标": "trademark",
    "专利": "patent",
    "版权": "copyright",
    "知识产权": "intellectual property",
    "法律": "legal",
    "法规": "regulation",
    "政策": "policy",
    "标准": "standard",
    "规范": "specification",
    "指南": "guide",
    "手册": "manual",
    "文档": "documentation",
    "知识": "knowledge",
    "经验": "experience",
    "案例": "case",
    "示例": "example",
    "模板": "template",
    "样式": "style",
    "布局": "layout",
    "设计": "design",
    "界面": "interface",
    "显示": "display",
    "视图": "view",
    "图表": "chart",
    "图像": "image",
    "图片": "picture",
    "照片": "photo",
    "视频": "video",
    "音频": "audio",
    "文件": "file",
    "文件夹": "folder",
    "目录": "directory",
    "路径": "path",
    "链接": "link",
    "网址": "URL",
    "域名": "domain",
    "服务器": "server",
    "数据库": "database",
    "存储": "storage",
    "计算": "compute",
    "处理": "processing",
    "算法": "algorithm",
    "模型": "model",
    "机器学习": "machine learning",
    "人工智能": "AI",
    "深度学习": "deep learning",
    "神经网络": "neural network",
    "大数据": "big data",
    "云计算": "cloud computing",
    "物联网": "IoT",
    "传感器": "sensor",
    "设备端": "device",
    "终端": "terminal",
    "节点": "node",
    "网络": "network",
    "通信": "communication",
    "传输": "transmission",
    "协议": "protocol",
    "加密": "encryption",
    "解密": "decryption",
    "安全防护": "security protection",
    "防护": "protection",
    "漏洞": "vulnerability",
    "攻击": "attack",
    "威胁": "threat",
    "防御": "defense",
    "检测": "detection",
    "响应": "response",
    "恢复": "recovery",
    "备份": "backup",
    "灾备": "disaster recovery",
    "故障": "fault",
    "错误": "error",
    "异常": "exception",
    "问题": "issue",
    "挑战": "challenge",
    "难点": "difficulty",
    "痛点": "pain point",
    "需求": "requirement",
    "目标": "goal",
    "目的": "purpose",
    "愿景": "vision",
    "使命": "mission",
    "价值观": "value",
    "文化": "culture",
    "理念": "philosophy",
    "策略": "strategy",
    "规划": "planning",
    "计划": "plan",
    "方案": "solution",
    "建议": "recommendation",
    "意见": "opinion",
    "反馈": "feedback",
    "评价": "evaluation",
    "评估": "assessment",
    "审核": "review",
    "审批": "approval",
    "确认": "confirmation",
    "验证": "verification",
    "校验": "validation",
    "测试": "test",
    "实验": "experiment",
    "研究": "research",
    "探索": "exploration",
    "创新": "innovation",
    "发明": "invention",
    "专利": "patent",
    "技术": "technology",
    "科技": "tech",
    "科学": "science",
    "工程": "engineering",
    "制造": "manufacturing",
    "生产": "production",
    "加工": "processing",
    "组装": "assembly",
    "包装": "packaging",
    "运输": "transportation",
    "仓储": "warehousing",
    "配送": "distribution",
    "零售": "retail",
    "批发": "wholesale",
    "交易": "transaction",
    "支付": "payment",
    "收款": "collection",
    "退款": "refund",
    "折扣": "discount",
    "优惠": "promotion",
    "奖励": "reward",
    "惩罚": "penalty",
    "罚款": "fine",
    "赔偿": "compensation",
    "索赔": "claim",
    "保险": "insurance",
    "理赔": "claim settlement",
    "保单": "policy",
    "保费": "premium",
    "保额": "coverage",
    "保期": "insurance period",

    # Industry specific terms
    "车辆": "vehicle",
    "汽车": "car",
    "电动滑板车": "electric scooter",
    "摩托车": "motorcycle",
    "自行车": "bicycle",
    "滑板车": "scooter",
    "电动车": "electric vehicle",
    "新能源": "new energy",
    "充电": "charging",
    "电池": "battery",
    "续航": "range",
    "能耗": "energy consumption",
    "排放": "emission",
    "环保": "eco-friendly",
    "绿色": "green",
    "低碳": "low carbon",
    "共享": "sharing",
    "出行": "mobility",
    "交通": "transportation",
    "路况": "road condition",
    "导航": "navigation",
    "定位": "positioning",
    "轨迹": "trajectory",
    "路线": "route",
    "里程": "mileage",
    "距离": "distance",
    "速度": "speed",
    "时间": "time",
    "时长": "duration",

    # Lighting equipment
    "灯光": "lighting",
    "灯具": "lamp",
    "照明": "illumination",
    "舞台灯光": "stage lighting",
    "演唱会": "concert",
    "剧院": "theater",
    "影视": "film",
    "拍摄": "shooting",
    "摄影": "photography",
    "摄像": "videography",
    "灯光设备": "lighting equipment",
    "照明设备": "lighting equipment",
    "专业灯光": "professional lighting",

    # Kitchen equipment
    "厨房": "kitchen",
    "烹饪": "cooking",
    "餐饮": "food service",
    "商用厨房": "commercial kitchen",
    "厨房设备": "kitchen equipment",
    "烹饪设备": "cooking equipment",
    "厨具": "kitchen utensils",
    "烤箱": "oven",
    "炉灶": "stove",
    "冰箱": "refrigerator",
    "洗碗机": "dishwasher",
    "搅拌机": "mixer",
    "切片机": "slicer",
    "蒸箱": "steamer",
    "油炸锅": "deep fryer",
    "烧烤架": "grill",

    # Quality control
    "质量控制": "quality control",
    "质量管理": "quality management",
    "质量检测": "quality inspection",
    "质量分析": "quality analysis",
    "统计过程控制": "statistical process control",
    "SPC": "SPC",
    "控制图": "control chart",
    "过程能力": "process capability",
    "能力分析": "capability analysis",
    "Cpk": "Cpk",
    "Ppk": "Ppk",
    "标准差": "standard deviation",
    "均值": "mean",
    "方差": "variance",
    "分布": "distribution",
    "正态分布": "normal distribution",

    # Water sports
    "潜水": "diving",
    "水上运动": "water sports",
    "潜水设备": "diving equipment",
    "潜水装备": "diving gear",
    "水上活动": "water activities",
    "游泳": "swimming",
    "冲浪": "surfing",
    "帆船": "sailing",
    "皮划艇": "kayaking",
    "游艇": "yacht",
    "船只": "boat",

    # Real estate
    "房地产": "real estate",
    "物业": "property",
    "租赁物业": "rental property",
    "房产": "property",
    "房屋": "house",
    "公寓": "apartment",
    "写字楼": "office building",
    "商铺": "commercial space",
    "租约": "lease",
    "合同审核": "contract review",
    "维修工单": "maintenance work order",

    # Business types
    "中小企业": "small business",
    "初创企业": "startup",
    "大型企业": "large enterprise",
    "企业级": "enterprise-level",
    "专业版": "professional version",
    "基础版": "basic version",
    "高级版": "advanced version",
    "标准版": "standard version",
    "定制版": "custom version",

    # CRM related
    "CRM": "CRM",
    "客户关系": "customer relationship",
    "客户管理": "customer management",
    "会员": "member",
    "会员管理": "member management",
    "会员营销": "member marketing",

    # Email related
    "邮件营销": "email marketing",
    "续费提醒": "renewal reminder",
    "活动推广": "event promotion",

    # Statistical terms
    "统计分析": "statistical analysis",
    "数据分析": "data analysis",
    "计算工具": "calculation tool",
    "分析工具": "analysis tool",

    # Common compound words patterns
    "管理系统": "management system",
    "管理软件": "management software",
    "管理平台": "management platform",
    "租赁系统": "rental system",
    "租赁软件": "rental software",
    "租赁平台": "rental platform",
    "租赁工具": "rental tools",
    "库存管理": "inventory management",
    "设备管理": "equipment management",
    "设备追踪": "equipment tracking",
    "设备租赁": "equipment rental",
    "设备维护": "equipment maintenance",
    "设备调度": "equipment scheduling",
    "设备监控": "equipment monitoring",
    "调度系统": "scheduling system",
    "调度软件": "scheduling software",
    "调度工具": "scheduling tools",
    "调度管理": "scheduling management",
    "预测系统": "prediction system",
    "预测工具": "prediction tools",
    "预警系统": "alert system",
    "预警工具": "alert tools",
    "故障预测": "fault prediction",
    "故障诊断": "fault diagnosis",
    "故障检测": "fault detection",
    "维护管理": "maintenance management",
    "维护系统": "maintenance system",
    "维护软件": "maintenance software",
    "维护工具": "maintenance tools",
    "维护计划": "maintenance planning",
    "维护调度": "maintenance scheduling",
    "维修管理": "repair management",
    "备件管理": "spare parts management",
    "备件库存": "spare parts inventory",
    "质量控制": "quality control",
    "质量检测": "quality inspection",
    "质量管理": "quality management",
    "安全管理": "safety management",
    "安全监控": "safety monitoring",
    "安全系统": "safety system",
    "合规管理": "compliance management",
    "风险管理": "risk management",
    "风险控制": "risk control",
    "风险预警": "risk alert",
    "成本管理": "cost management",
    "成本分析": "cost analysis",
    "成本控制": "cost control",
    "财务管理": "financial management",
    "财务系统": "financial system",
    "财务软件": "financial software",
    "合同管理": "contract management",
    "合同系统": "contract system",
    "客户管理": "customer management",
    "客户系统": "customer system",
    "客户服务": "customer service",
    "客户支持": "customer support",
    "客户体验": "customer experience",
    "员工管理": "employee management",
    "员工系统": "employee system",
    "培训管理": "training management",
    "培训系统": "training system",
    "培训平台": "training platform",
    "物流管理": "logistics management",
    "物流系统": "logistics system",
    "配送管理": "delivery management",
    "配送系统": "delivery system",
    "采购管理": "procurement management",
    "采购系统": "procurement system",
    "供应链管理": "supply chain management",
    "数据管理": "data management",
    "数据分析": "data analysis",
    "数据平台": "data platform",
    "报表管理": "report management",
    "报表系统": "report system",
    "报表工具": "report tools",
    "统计管理": "statistics management",
    "统计系统": "statistics system",
    "统计工具": "statistics tools",
    "智能管理": "intelligent management",
    "智能系统": "intelligent system",
    "智能平台": "intelligent platform",
    "自动化系统": "automation system",
    "自动化平台": "automation platform",
    "数字化系统": "digital system",
    "数字化平台": "digital platform",
    "在线系统": "online system",
    "在线平台": "online platform",
    "实时监控": "real-time monitoring",
    "实时系统": "real-time system",
    "移动管理": "mobile management",
    "移动系统": "mobile system",
    "云端系统": "cloud system",
    "云端平台": "cloud platform",
    "企业系统": "enterprise system",
    "企业平台": "enterprise platform",
    "专业系统": "professional system",
    "专业平台": "professional platform",
    "定制系统": "custom system",
    "定制平台": "custom platform",
    "集成系统": "integrated system",
    "集成平台": "integrated platform",
    "开放平台": "open platform",
    "服务平台": "service platform",
    "解决方案": "solution",
    "业务管理": "business management",
    "业务系统": "business system",
    "业务平台": "business platform",
    "运营管理": "operation management",
    "运营系统": "operation system",
    "运营平台": "operation platform",
    "资产管理": "asset management",
    "资产系统": "asset system",
    "生命周期": "lifecycle",
    "全生命周期": "full lifecycle",
    "生命周期管理": "lifecycle management",
    "身份验证": "identity verification",
    "用户培训": "user training",
    "行为分析": "behavior analysis",
    "满意度分析": "satisfaction analysis",
    "体验优化": "experience optimization",
    "智能分析": "intelligent analysis",
    "定价分析": "pricing analysis",
    "远程管理": "remote management",
    "数字化分析": "digital analysis",
    "质量控制": "quality control",
    "保险管理": "insurance management",
    "索赔管理": "claim management",
    "损坏评估": "damage assessment",
    "节能管理": "energy saving management",
    "价格计算": "price calculation",
    "可持续发展": "sustainability",
    "API集成": "API integration",
    "智能控制": "smart control",
    "灯光预订": "lighting booking",
    "特殊效果": "special effects",
    "智能照明": "smart lighting",
    "舞台灯光": "stage lighting",
    "清洁维护": "cleaning maintenance",
    "财务计费": "financial billing",
    "LED灯具": "LED lighting",
    "运营培训": "operation training",
    "婚礼灯光": "wedding lighting",
    "激光灯光": "laser lighting",
    "影视灯光": "film lighting",
    "室外照明": "outdoor lighting",
    "剧院舞台": "theater stage",
    "控制平台": "control platform",
    "活动餐饮": "event catering",
    "餐车设备": "food truck equipment",
    "活动调度": "event scheduling",
    "价格计算": "price calculation",
    "冰箱库存": "refrigerator inventory",
    "企业活动": "corporate event",
    "合同管理": "contract management",
    "商用搅拌机": "commercial mixer",
    "商用切片机": "commercial slicer",
    "婚礼厨房": "wedding kitchen",
    "商用蒸箱": "commercial steamer",
    "专业烧烤": "professional grill",
    "室外厨房": "outdoor kitchen",
    "移动厨房": "mobile kitchen",
    "商用油炸锅": "commercial deep fryer",
    "清洗维护": "cleaning maintenance",
    "食品加工": "food processing",
    "移动厨房布局": "mobile kitchen layout",
    "商用洗碗机": "commercial dishwasher",
    "餐厅炒锅": "restaurant wok",
    "商用烤箱": "commercial oven",
    "烘焙烤箱": "bakery oven",
    "中国": "Chinese",

    # More compound translations
    "关系": "relationship",
    "流失": "churn",
    "可持续发展": "sustainability development",
    "可持续": "sustainable",
    "碳足迹": "carbon footprint",
    "人员": "personnel",
    "任务分配": "task assignment",
    "任务": "task",
    "分配": "assignment",
    "绩效": "performance",
    "评估": "assessment",
    "商业": "business",
    "挖掘": "mining",
    "会计": "accounting",
    "报表": "report",
    "报告": "report",
    "支持": "support",
    "决策": "decision",
    "预警": "alert",
    "资质": "qualification",
    "驾驶": "driving",
    "驾驶员资质": "driver qualification",
    "事故处理": "incident handling",
    "事故": "incident",
    "处理": "handling",
    "安全事故": "safety incident",
    "人员管理": "personnel management",
    "员工管理": "employee management",
    "绩效评估": "performance assessment",
    "培训管理": "training management",
    "任务管理": "task management",
    "流失预警": "churn alert",
    "客户关系": "customer relationship",
    "数据挖掘": "data mining",
    "商业智能": "business intelligence",
    "决策支持": "decision support",
    "财务报表": "financial report",
    "会计管理": "accounting management",
    "第三方": "third-party",
    "平台对接": "platform integration",
    "对接": "integration",
    "库存同步": "inventory sync",
    "同步": "sync",
    "订单管理": "order management",
    "订单": "order",
    "移动端": "mobile",
    "端": "platform",
    "用户运营": "user operation",
    "运营": "operation",
    "优化": "optimization",
    "数据分析": "data analysis",
    "通道": "channel",
    "渠道": "channel",
    "绿色": "green",
    "环保": "eco-friendly",
    "碳足迹": "carbon footprint",
    "可持续发展": "sustainability",
    "报告": "report",
    "可持续报告": "sustainability report",
    "人员管理": "staff management",
    "人员运营": "personnel operation",
    "商业智能": "business intelligence",
    "预测分析": "predictive analysis",
    "商业分析": "business analysis",
    "商业数据": "business data",
    "财务报告": "financial report",
    "会计系统": "accounting system",
    "租赁会计": "rental accounting",
    "资产管理": "asset management",
    "成本管理": "cost management",
    "金融管理": "financial management",
    "金融软件": "financial software",
    "金融系统": "financial system",
    "移动端管理": "mobile management",
    "移动端优化": "mobile optimization",
    "移动端运营": "mobile operation",
    "用户管理": "user management",
    "用户运营": "user operation",
    "应用运营": "app operation",
    "应用数据": "app data",
    "数据分析": "data analysis",
    "商业智能": "business intelligence",
    "数据挖掘": "data mining",
    "预测分析": "forecast analysis",
    "决策支持": "decision support",
    "租赁财务": "rental finance",
    "租赁会计": "rental accounting",
    "资产": "asset",
    "成本": "cost",
    "财务": "financial",
    "第三方平台": "third-party platform",
    "平台": "platform",
    "库存": "inventory",
    "同步": "synchronization",
    "订单": "order",
    "第三方对接": "third-party integration",
    "渠道同步": "channel sync",
    "库存同步": "inventory synchronization",
    "租赁数据": "rental data",
    "分析平台": "analytics platform",
    "数据分析": "data analytics",
    "商业智能": "business intelligence",
    "数据挖掘": "data mining",
    "预测分析": "forecast analysis",
    "决策支持": "decision support",
    "租赁财务": "rental financial",
    "会计": "accounting",
    "资产管理": "asset management",
    "成本": "cost",
    "财务报表": "financial report",
    "绿色运营": "green operations",
    "环保管理": "eco-friendly management",
    "可持续发展报告": "sustainability reporting",
    "任务分配": "task assignment",
    "绩效评估": "performance assessment",
    "员工培训": "staff training",
    "人员管理": "personnel management",
    "员工管理": "employee management",
    "任务管理": "task management",
    "绩效管理": "performance management",
    "培训": "training",
    "评估": "assessment",
    "员工绩效": "staff performance",
    "人员绩效": "personnel performance",
    "员工运营": "staff operation",
    "任务调度": "task scheduling",
    "员工调度": "staff scheduling",
    "人员调度": "personnel scheduling",
    "绩效评估": "performance evaluation",
    "员工绩效评估": "staff performance evaluation",
    "人员绩效评估": "personnel performance evaluation",
    "员工培训系统": "staff training system",
    "人员培训系统": "personnel training system",
    "员工培训管理": "staff training management",
    "人员培训管理": "personnel training management",

    # Lighting rental specific terms
    "巡演设备管理": "tour equipment management",
    "巡演": "tour",
    "演出灯光排期": "performance lighting scheduling",
    "灯光排期": "lighting scheduling",
    "排期": "scheduling",
    "演出灯光管理": "performance lighting management",
    "演出": "performance",
    "节能照明租赁管理": "energy saving lighting rental management",
    "节能照明": "energy saving lighting",
    "节能": "energy saving",
    "碳排放追踪工具": "carbon emission tracking tools",
    "碳排放追踪": "carbon emission tracking",
    "碳排放": "carbon emission",
    "租赁定价工具": "rental pricing tools",
    "定价": "pricing",
    "动态定价系统": "dynamic pricing system",
    "动态定价": "dynamic pricing",
    "设备利用率分析": "equipment utilization rate analysis",
    "利用率": "utilization rate",
    "收益趋势预测": "revenue trend prediction",
    "收益趋势": "revenue trend",
    "活动照明库存系统": "event illumination inventory system",
    "活动照明": "event illumination",
    "追光灯租赁预订": "follow spot light rental booking",
    "追光灯": "follow spot light",
    "追光操控培训": "follow spot operation training",
    "追光操控": "follow spot operation",
    "追光距离计算": "follow spot distance calculation",
    "距离计算": "distance calculation",
    "特效灯光租赁管理": "special effects lighting rental management",
    "特效灯光": "special effects lighting",
    "烟雾机配套管理": "smoke machine integration management",
    "烟雾机配套": "smoke machine integration",
    "配套": "integration",
    "特效安全合规": "special effects safety compliance",
    "电子合同平台": "electronic contract platform",
    "电子合同": "electronic contract",
    "合同存证系统": "contract certification system",
    "合同存证": "contract certification",
    "存证": "certification",
    "语音控制照明": "voice control lighting",
    "语音控制": "voice control",
    "灯具清洁维护软件": "lamp cleaning maintenance software",
    "租赁账单生成": "rental invoice generation",
    "账单生成": "invoice generation",
    "多币种结算工具": "multi-currency settlement tools",
    "多币种结算": "multi-currency settlement",
    "灯光设备操作培训": "lighting equipment operation training",
    "操作培训": "operation training",
    "VR灯光模拟训练": "VR lighting simulation training",
    "VR模拟训练": "VR simulation training",
    "模拟训练": "simulation training",
    "婚礼灯光预订平台": "wedding lighting booking platform",
    "婚礼灯光套餐": "wedding lighting package",
    "套餐": "package",
    "婚礼现场灯光": "wedding venue lighting",
    "婚礼现场": "wedding venue",
    "激光灯租赁管理": "laser light rental management",
    "激光灯": "laser light",
    "激光安全合规": "laser safety compliance",
    "激光特效编程": "laser effect programming",
    "特效编程": "effect programming",
    "剧组照明设备": "film crew lighting equipment",
    "剧组": "film crew",
    "片场照明分布": "filming location lighting distribution",
    "片场": "filming location",
    "户户外照明租赁管理": "outdoor illumination rental management",
    "户户外照明": "outdoor illumination",
    "户户外": "outdoor",
    "防水照明设备": "waterproof lighting equipment",
    "防水": "waterproof",
    "户户外活动照明": "outdoor event illumination",
    "户户外活动": "outdoor event",
    "DMX控制台租赁": "DMX control console rental",
    "DMX控制台": "DMX control console",
    "控制台": "control console",
    "剧目灯光编排": "theater repertoire lighting arrangement",
    "剧目": "theater repertoire",
    "编排": "arrangement",

    # Additional single-word translations
    "演出": "performance",
    "碳": "carbon",
    "活动": "event",
    "追光": "follow spot",
    "特效": "special effects",
    "电子": "electronic",
    "语音": "voice",
    "清洁": "cleaning",
    "多币种": "multi-currency",
    "操作": "operation",
    "婚礼": "wedding",
    "激光": "laser",
    "台": "console",
    "计算": "calculation",
    "分布": "distribution",
    "控制": "control",
    "利用": "utilization",
    "排放": "emission",
    "收益": "revenue",
    "智能": "smart",
    "管理": "management",
    "系统": "system",
    "平台": "platform",
    "工具": "tools",
    "软件": "software",
    "设备": "equipment",
    "租赁": "rental",
    "预订": "booking",
    "库存": "inventory",
    "分析": "analysis",
    "培训": "training",
    "安全": "safety",
    "合规": "compliance",
    "编程": "programming",
    "编排": "arrangement",
    "分布": "distribution",
    "计算": "calculation",
    "趋势": "trend",
    "预测": "prediction",
    "存证": "certification",
    "套餐": "package",
    "现场": "venue",
    "配套": "integration",
    "操控": "operation",
    "追踪": "tracking",
    "账单": "invoice",
    "结算": "settlement",
    "模拟": "simulation",
    "编排": "arrangement",

    # Kitchen and food service translations
    "厨房租赁": "kitchen rental",
    "业务": "business",
    "宴会": "banquet",
    "布置指导": "layout guide",
    "布置": "layout",
    "指导": "guide",
    "餐车": "food truck",
    "餐车改装指导": "food truck modification guide",
    "改装": "modification",
    "餐车合规办理服务": "food truck compliance processing service",
    "办理": "processing",
    "创业": "startup",
    "餐车运营培训": "food truck operation training",
    "年会": "annual meeting",
    "规模匹配指导": "scale matching guide",
    "匹配": "matching",
    "规模": "scale",
    "安排": "arrangement",
    "生成": "generation",
    "条款": "terms",
    "估值": "valuation",
    "租金": "rental fee",
    "冷柜": "freezer",
    "冷藏柜": "refrigerator",
    "冷藏柜温度监控": "refrigerator temperature monitoring",
    "温度": "temperature",
    "冷链设备租赁系统": "cold chain equipment rental system",
    "冷链": "cold chain",
    "冷冻柜维护调度": "freezer maintenance scheduling",
    "冷冻柜": "freezer",
    "烘焙搅拌设备租赁": "baking mixer equipment rental",
    "搅拌": "mixing",
    "烘焙": "baking",
    "行星搅拌机": "planetary mixer",
    "行星": "planetary",
    "螺旋搅拌机": "spiral mixer",
    "螺旋": "spiral",
    "转速控制": "speed control",
    "转速": "speed",
    "食材切片设备租赁": "food slicing equipment rental",
    "食材": "food ingredient",
    "切片": "slicing",
    "切片精度调整指导": "slicing precision adjustment guide",
    "精度": "precision",
    "调整": "adjustment",
    "电动切片机": "electric slicer",
    "电动": "electric",
    "婚宴餐饮设备租赁": "wedding banquet catering equipment rental",
    "婚宴": "wedding banquet",
    "餐具租赁搭配": "tableware rental matching",
    "餐具": "tableware",
    "搭配": "matching",
    "商用蒸柜租赁": "commercial steamer rental",
    "蒸柜": "steamer",
    "蒸煮设备租赁": "steaming equipment rental",
    "蒸煮": "steaming",
    "多层蒸柜租赁管理": "multi-layer steamer rental management",
    "多层": "multi-layer",
    "蒸汽管道安装服务": "steam pipeline installation service",
    "蒸汽": "steam",
    "管道": "pipeline",
    "蒸柜安全培训": "steamer safety training",
    "燃气烧烤炉租赁": "gas grill rental",
    "烧烤炉": "grill",
    "燃气": "gas",
    "炭火烧烤炉租赁": "charcoal grill rental",
    "炭火": "charcoal",
    "烟熏炉租赁系统": "smoker rental system",
    "烟熏炉": "smoker",
    "烟熏": "smoking",
    "烧烤设备安全培训": "grill equipment safety training",
    "户外供电解决方案": "outdoor power supply solution",
    "供电": "power supply",
    "户外水源解决方案": "outdoor water supply solution",
    "水源": "water supply",
    "美食节摊位租赁": "food festival booth rental",
    "美食节": "food festival",
    "摊位": "booth",
    "压力炸锅租赁管理": "pressure fryer rental management",
    "炸锅": "fryer",
    "压力炸锅": "pressure fryer",
    "油脂更换服务": "oil replacement service",
    "油脂": "oil",
    "更换": "replacement",
    "油炸设备安全培训": "frying equipment safety training",
    "油炸": "frying",
    "设备健康度评估": "equipment health assessment",
    "健康度": "health",
    "预防性维护系统": "preventive maintenance system",
    "预防性": "preventive",
    "程序": "procedure",
    "绞肉机租赁软件": "meat grinder rental software",
    "绞肉机": "meat grinder",
    "绞肉": "meat grinding",
    "产能匹配指导": "capacity matching guide",
    "产能": "capacity",
    "布置解决方案": "layout solution",
    "搭建指导": "setup guide",
    "搭建": "setup",
    "空间规划软件": "space planning software",
    "空间": "space",
    "规划": "planning",
    "摆放布局系统": "placement layout system",
    "摆放": "placement",
    "洗涤效率优化指导": "washing efficiency optimization guide",
    "洗涤": "washing",
    "中式烹饪设备租赁": "Chinese cooking equipment rental",
    "中式": "Chinese",
    "烹饪": "cooking",
    "燃气炒锅租赁平台": "gas wok rental platform",
    "炒锅": "wok",
    "电磁炒锅租赁管理": "electric wok rental management",
    "电磁": "electromagnetic",
    "隧道炉租赁预订": "tunnel oven rental booking",
    "隧道炉": "tunnel oven",
    "隧道": "tunnel",
    "万能蒸烤炉租赁": "combi oven rental",
    "万能蒸烤炉": "combi oven",
    "万能": "universal",
    "蒸烤": "steam bake",
    "通道式洗碗机": "conveyor dishwasher",
    "通道式": "conveyor type",
    "商用厨房用具价格计算": "commercial kitchen utensils price calculation",
    "用具": "utensils",

    # Additional event-related translations
    "户外活动": "outdoor event",
    "户外烧烤": "outdoor barbecue",
    "户外": "outdoor",
    "户外照明": "outdoor lighting",
    "户外厨房": "outdoor kitchen",
    "布置效率": "layout efficiency",
    "效率": "efficiency",

    # Top common Chinese phrases from seo_keywords analysis
    "酒店": "hotel",
    "酒店转型": "hotel transformation",
    "转型": "transformation",
    "重型机械": "heavy machinery",
    "重型机械选型": "heavy machinery selection",
    "机械": "machinery",
    "选型": "selection",
    "园林": "landscaping",
    "园林报价": "landscaping quotation",
    "园林项目": "landscaping project",
    "园艺": "gardening",
    "教育": "education",
    "教育学习": "education learning",
    "学习": "learning",
    "养生": "wellness",
    "养生按摩": "wellness massage",
    "按摩": "massage",
    "按摩店": "massage shop",
    "按摩技师": "massage technician",
    "技师": "technician",
    "珠宝": "jewelry",
    "珠宝行业": "jewelry industry",
    "行业": "industry",
    "最佳实践": "best practices",
    "市场变化": "market change",
    "市场": "market",
    "课程": "course",
    "能源": "energy",
    "酒店能源": "hotel energy",
    "代理": "agency",
    "酒店代理": "hotel agency",
    "酒店佣金": "hotel commission",
    "佣金": "commission",
    "幼儿园": "kindergarten",
    "幼儿": "preschool",
    "托儿所": "daycare",
    "餐厅": "restaurant",
    "网球": "tennis",
    "价格": "price",
    "价格报价": "price quotation",
    "报价": "quotation",
    "报价估算": "quotation estimation",
    "估算": "estimation",
    "审计": "audit",
    "学员": "student",
    "学员识别": "student identification",
    "识别": "identification",
    "仪表板": "dashboard",
    "仪表盘": "dashboard",
    "可视化": "visualization",
    "推荐": "recommendation",
    "技能": "skill",
    "技能提升": "skill improvement",
    "提升": "improvement",
    "远程": "remote",
    "远程协作": "remote collaboration",
    "协作": "collaboration",
    "供应商": "supplier",
    "项目": "project",
    "记录": "record",
    "资源": "resource",
    "移动": "mobile",
    "移动应用": "mobile application",
    "应用": "application",
    "价值": "value",
    "体育": "sports",
    "档案": "archive",
    "收集": "collection",
    "监测": "monitoring",
    "电网": "power grid",
    "微电网": "microgrid",
    "电表": "electric meter",
    "工单": "work order",
    "仓库": "warehouse",
    "调查": "investigation",
    "电力": "electric power",
    "电力行业": "electric power industry",
    "配电": "power distribution",
    "发电": "power generation",
    "停电": "power outage",
    "电能": "electric energy",
    "电气": "electrical",
    "建筑": "construction",
    "效果": "effect",
    "公用事业": "public utility",
    "沟通": "communication",
    "投诉": "complaint",
    "排班": "shift scheduling",
    "班次": "shift",
    "核算": "accounting",
    "监管": "supervision",
    "执行": "execution",
    "作业": "operation",
    "离线作业": "offline operation",
    "环境": "environment",
    "教学": "teaching",
    "历史": "history",
    "客服": "customer service",
    "证书": "certificate",
    "定损": "damage assessment",
    "水": "water",
    "行为": "behavior",
    "追溯": "traceability",
    "改进": "improvement",
    "手表": "watch",
    "门户": "portal",
    "机器人": "robot",
    "洞察": "insight",
    "激励": "incentive",
    "信息": "information",
    "材料": "material",
    "整合": "integration",
    "内容": "content",
    "收银": "cashier",
    "考试": "exam",
    "水管工": "plumber",
    "电工": "electrician",
    "训练": "training",
    "状态": "status",
    "基准": "benchmark",
    "等级": "level",
    "中和": "neutralization",
    "分类": "classification",
    "参与": "engagement",
    "电梯": "elevator",
    "扶梯": "escalator",
    "利润": "profit",
    "教师": "teacher",
    "成绩": "grade",
    "旅游酒店": "tourism hotel",
    "跟踪": "tracking",
    "边缘": "edge",
    "进度": "progress",
    "检验": "inspection",
    "焊接": "welding",
    "寿险": "life insurance",
    "健康险": "health insurance",
    "车险": "car insurance",
    "财产险": "property insurance",
    "食品": "food",
    "起重机": "crane",
    "开票": "invoicing",
    "仿真": "simulation",
    "负荷": "load",
    "设施": "facility",
    "云": "cloud",
    "投资": "investment",
    "电商": "e-commerce",
    "帐篷": "tent",
    "装备": "equipment",
    "叉车": "forklift",
    "工作流": "workflow",
    "室": "room",
    "景观": "landscape",
    "证据": "evidence",
    "查勘": "survey",
    "客房": "guest room",
    "客人": "guest",
    "停车": "parking",
    "自助": "self-service",
    "支撑": "support",
    "储能": "energy storage",
    "应急": "emergency",
    "对标": "benchmarking",
    "签署": "signing",
    "健康": "health",
    "采集": "collection",
    "补贴": "subsidy",
    "税务": "tax",
    "画像": "profile",
    "综合": "comprehensive",
    "选址": "site selection",
    "回收": "recycling",
    "配额": "quota",
    "信用": "credit",
    "收入": "revenue",
    "检索": "search",
    "儿童": "children",
    "配件": "accessories",
    "职业": "career",
    "职业发展": "career development",
    "医疗": "medical",
    "西门子": "Siemens",
    "互动": "interaction",
    "促销": "promotion",
    "社交": "social",
    "季节": "season",
    "季节性": "seasonal",
    "化": "ization",
    "旅程": "journey",
    "考勤": "attendance",
    "关怀": "care",
    "库": "library",
    "竞争": "competition",
    "制药": "pharmaceutical",
    "更衣柜": "locker",
    "输送": "conveying",
    "瓶颈": "bottleneck",
    "压缩空气": "compressed air",
    "淋浴": "shower",
    "定期": "periodic",
    "应收账款": "accounts receivable",
    "赔付": "claim payment",
    "报案": "report case",
    "学校": "school",
    "积分": "points",
    "权益": "rights",
    "考核": "assessment",
    "全": "full",
    "发布": "release",
    "盘点": "inventory count",

    # More common Chinese phrases
    "家长": "parent",
    "险": "insurance",
    "家校": "school-family",
    "学生": "student",
    "办公": "office",
    "数学": "mathematics",
    "礼品卡": "gift card",
    "计费": "billing",
    "工时": "work hours",
    "偏好": "preference",
    "问卷": "questionnaire",
    "口碑": "reputation",
    "生日": "birthday",
    "晋升": "promotion",
    "接送": "transportation",
    "组合": "combination",
    "式": "style",
    "隐私": "privacy",
    "直播": "live streaming",
    "媒体": "media",
    "写作": "writing",
    "投票": "voting",
    "发展": "development",
    "汽修": "auto repair",
    "音乐": "music",
    "提成": "commission",
    "挽回": "recovery",
    "心理": "psychology",
    "案件": "case",
    "学": "learning",
    "旅行社": "travel agency",
    "展示": "display",
    "运维": "operation maintenance",
    "区块链": "blockchain",
    "创作": "creation",
    "挽留": "retention",
    "批次": "batch",
    "续保": "renewal insurance",
    "消费": "consumption",
    "增值": "value-added",
    "量": "volume",
    "增长": "growth",
    "门店": "store",
    "高峰": "peak",
    "归档": "archiving",
    "测评": "assessment",
    "标签": "label",
    "废物": "waste",
    "机": "machine",
    "纪念日": "anniversary",
    "欺诈": "fraud",
    "创建": "creation",
    "差异": "difference",
    "休息": "rest",
    "派工": "dispatch",
    "疗程": "treatment course",
    "房间": "room",
    "复购": "repeat purchase",
    "语言": "language",
    "观察": "observation",
    "率": "rate",
    "数字": "digital",
    "虚拟": "virtual",
    "协同": "collaboration",
    "开发": "development",
    "费率": "rate",
    "视觉": "visual",
    "劳动": "labor",
    "物料": "material",
    "报废": "scrapping",
    "节日": "festival",
    "缺陷": "defect",
    "危险物料": "hazardous material",
    "危险": "hazardous",
    "装配": "assembly",
    "无人机": "drone",
    "校准": "calibration",
    "离职": "resignation",
    "奖金": "bonus",
    "请假": "leave request",
    "灌溉": "irrigation",
    "毕业": "graduation",
    "睡眠": "sleep",
    "行程": "itinerary",
    "评论": "comment",
    "人力": "human resource",
    "本地": "local",
    "连锁": "chain",
    "洗衣": "laundry",
    "行李": "luggage",
    "战略": "strategy",
    "可再生": "renewable",
    "能效": "energy efficiency",
    "用电": "electricity usage",
    "工业": "industrial",
    "仪": "instrument",
    "线路": "line",
    "英语": "English",
    "制作": "production",
    "事件": "event",
    "申请": "application",
    "旅游酒店转型": "tourism hotel transformation",
    "旅游酒店最佳实践": "tourism hotel best practices",
    "酒店市场变化": "hotel market change",

    # More remaining Chinese phrases
    "作品": "work",
    "光伏": "photovoltaic",
    "保护": "protection",
    "辅助": "auxiliary",
    "社区": "community",
    "艺术": "art",
    "助手": "assistant",
    "分群": "segmentation",
    "储值": "stored value",
    "作品集": "portfolio",
    "招生": "enrollment",
    "干预": "intervention",
    "菜单": "menu",
    "序列号": "serial number",
    "拜访": "visit",
    "招聘": "recruitment",
    "时段": "time slot",
    "等候": "waiting",
    "天气": "weather",
    "金额": "amount",
    "责任": "responsibility",
    "意外": "accident",
    "植物": "plant",
    "文书": "document",
    "简历": "resume",
    "教案": "teaching plan",
    "翻译": "translation",
    "营养": "nutrition",
    "巡检": "inspection patrol",
    "工服": "work uniform",
    "周边": "peripheral",
    "鉴定": "appraisal",
    "减排": "emission reduction",
    "质": "quality",
    "账": "account",
    "抵消": "offset",
    "混凝土": "concrete",
    "引擎": "engine",
    "电钻": "electric drill",
    "广告": "advertisement",
    "迁移": "migration",
    "关键时刻": "critical moment",
    "区域": "region",
    "组": "group",
    "清洗": "cleaning",
    "感谢": "thank",
    "门禁": "access control",
    "新": "new",
    "现金流": "cash flow",
    "器材": "equipment",
    "防控": "prevention control",
    "微信": "WeChat",
    "激活": "activation",
    "装修": "renovation",
    "货运": "freight",
    "重疾": "critical illness",
    "情绪": "emotion",
    "草坪": "lawn",
    "印": "printing",
    "转换": "conversion",
    "压缩": "compression",
    "领导力": "leadership",
    "教程": "tutorial",
    "微": "micro",
    "动画": "animation",
    "游戏": "game",
    "前": "front",
    "居家": "home",
    "教": "teaching",
    "火灾": "fire",
    "券": "coupon",
    "场馆": "venue",
    "持续": "continuous",
    "工装": "tooling",
    "访客": "visitor",
    "排程": "scheduling",
    "套房": "suite",
    "换房": "room change",
    "修改": "modification",
    "迷你吧": "mini bar",
    "延住": "extend stay",
    "房型": "room type",
    "民宿": "homestay",
    "缴费": "payment",
    "管网": "pipe network",
    "变压器": "transformer",
    "损失": "loss",
    "质检": "quality inspection",
    "影响": "impact",
    "气候": "climate",
    "危废": "hazardous waste",
    "器": "device",
    "网站": "website",
    "盈利": "profitability",
    "降低": "reduce",
    "降级": "downgrade",
    "脱敏": "desensitization",
    "地址": "address",
    "分支": "branch",
    "终身": "lifetime",
    "国家": "national",
    "接触点": "touchpoint",
    "交叉": "cross",
    "访问": "access",
    "地域": "regional",
    "存档": "archive",
    "联系方": "contact",
    "便携": "portable",
    "试戴": "try-on",
    "入职": "onboarding",
    "调配": "allocation",
    "收藏": "collection",
    "装载": "loading",
    "推土": "earthmoving",
    "资格": "qualification",
    "情感": "sentiment",
    "问答": "Q&A",
    "自然": "natural",
    "编制": "preparation",
    "报送": "submission",
    "农": "agriculture",
    "手": "hand",
    "核赔": "claim review",
    "外包": "outsourcing",
    "登记": "registration",
    "调研": "research",
    "格": "grade",
    "合并": "merge",
    "拆分": "split",
    "创意": "creative",
    "绘画": "painting",
    "校友": "alumni",
    "建模": "modeling",
    "实战": "practice",
    "表": "table",
    "无障碍": "accessible",
    "物理": "physics",
    "运动": "sports",
    "力": "power",
    "过敏": "allergy",
    "认知": "cognitive",
    "准备": "preparation",
    "融合": "integration",
    "感官": "sensory",
    "整改": "rectification",
    "订阅": "subscription",
    "功": "function",
    "教练": "coach",
    "消防": "fire protection",
    "书籍": "books",
    "加盟": "franchise",
    "补货": "replenishment",
    "分拣": "sorting",
    "线": "line",
    "菜品": "dishes",
    "精益": "lean",
    "负载": "load",
    "回报": "return",
    "点餐": "ordering",
    "相邻": "adjacent",
    "礼宾": "concierge",
    "取消": "cancel",
    "礼包": "gift package",
    "工控": "industrial control",
    "计": "meter",
    "孪生": "twin",
    "治理": "governance",
    "电厂": "power plant",
    "处置": "disposal",
    "元宇宙": "metaverse",
    "退货": "return goods",
    "车间": "workshop",
    "看板": "kanban",
    "体系": "system",
    "废弃物": "waste",
    "噪声": "noise",
    "措施": "measure",
    "气体": "gas",
    "清单": "list",
    "签名": "signature",
    "制": "system",
    "测": "measure",
    "平": "balance",
    "切割": "cutting",
    "技巧": "technique",
    "获客": "customer acquisition",
    "气动": "pneumatic",
    "发送": "send",
    "专业": "professional",
    "电话": "phone",
    "入": "input",
    "单": "order",
    "店": "store",

    # More remaining Chinese phrases
    "衡": "balance",
    "商": "business",
    "务": "service",
    "面试": "interview",
    "筛查": "screening",
    "建设": "construction",
    "员": "staff",
    "环": "environment",
    "费用": "fee",
    "住": "stay",
    "部署": "deployment",
    "影像": "imaging",
    "房": "room",
    "规则": "rule",
    "培养": "training",
    "视": "visual",
    "听": "audio",
    "书写": "writing",
    "预防": "prevention",
    "品": "product",
    "空气": "air",
    "细分": "segmentation",
    "人才": "talent",
    "课堂": "classroom",
    "会议": "meeting",
    "上": "up",
    "报警": "alarm",
    "宠物": "pet",
    "编辑": "editing",
    "座位": "seat",
    "紧急": "emergency",
    "模": "mode",
    "协调": "coordination",
    "寿命": "lifespan",
    "集中": "centralized",
    "管控": "management control",
    "复租": "repeat rental",
    "兑换": "exchange",
    "搬运": "transport",
    "食堂": "cafeteria",
    "均衡": "balance",
    "覆盖": "coverage",
    "分享": "sharing",
    "打卡": "check-in",
    "比赛": "competition",
    "发放": "distribution",
    "合作伙伴": "partner",
    "等待": "waiting",
    "期": "period",
    "签到": "sign-in",
    "地点": "location",
    "请求": "request",
    "超订": "overbooking",
    "安置": "placement",
    "押金": "deposit",
    "锁定": "lock",
    "气象": "meteorology",
    "风电": "wind power",
    "大": "large",
    "情报": "intelligence",
    "履约": "fulfillment",
    "基础": "basic",
    "现实": "reality",
    "论坛": "forum",
    "资金": "fund",
    "陈列": "display",
    "打包": "packaging",
    "温湿度": "temperature humidity",
    "语法": "grammar",
    "构建": "build",
    "申报": "declaration",
    "对": "pair",
    "废": "waste",
    "废弃物管理": "waste management",
    "危废处置": "hazardous waste disposal",
    "减排措施": "emission reduction measures",
    "噪音防控": "noise prevention",
    "空气监测": "air monitoring",
    "气体检测": "gas detection",
    "水质检测": "water quality testing",
    "温湿度监控": "temperature humidity monitoring",
    "应急预案": "emergency plan",
    "火灾防控": "fire prevention",
    "消防安全": "fire safety",
    "安全措施": "safety measures",
    "防护设备": "protective equipment",
    "个人防护": "personal protection",
    "环保措施": "environmental measures",
    "废物处理": "waste treatment",
    "节能减排": "energy saving emission reduction",
    "碳中和": "carbon neutral",
    "可持续发展": "sustainable development",
    "光伏发电": "photovoltaic power generation",
    "风电运维": "wind power operation",
    "储能系统": "energy storage system",
    "微电网": "microgrid",
    "智能电网": "smart grid",
    "电力运维": "power operation",
    "电力监控": "power monitoring",
    "配电管理": "distribution management",
    "变压器监控": "transformer monitoring",
    "电表管理": "meter management",
    "用电分析": "electricity usage analysis",
    "能效优化": "energy efficiency optimization",
    "可再生能源": "renewable energy",
    "新能源": "new energy",

    # Environmental and energy terms
    "生态修复": "ecological restoration",
    "矿区": "mining area",
    "矿区生态修复": "mining area ecological restoration",
    "湿地": "wetland",
    "湿地恢复": "wetland recovery",
    "恢复": "recovery",
    "修复效果评估": "restoration effect assessment",
    "土壤污染": "soil pollution",
    "土壤": "soil",
    "土壤监测": "soil monitoring",
    "土壤采样": "soil sampling",
    "重金属": "heavy metal",
    "重金属检测": "heavy metal detection",
    "检测设备": "detection equipment",
    "场地污染": "site pollution",
    "场地": "site",
    "调查": "investigation",
    "节 water": "water saving",
    "节水": "water saving",
    "节水管理": "water saving management",
    "用水热点识别": "water usage hotspot identification",
    "用水": "water usage",
    "热点": "hotspot",
    "节水措施建议": "water saving measure recommendation",
    "节水收益核算": "water saving revenue accounting",
    "收益": "revenue",
    "核算": "accounting",
    "污染监测": "pollution monitoring",
    "污染": "pollution",
    "废气监测": "waste gas monitoring",
    "废气": "waste gas",
    "固体废物": "solid waste",
    "固体": "solid",
    "固废管理": "solid waste management",
    "温室气体": "greenhouse gas",
    "温室": "greenhouse",
    "气体": "gas",
    "排放清单": "emission inventory",
    "清单": "inventory",
    "排放源识别": "emission source identification",
    "源": "source",
    "排放因子": "emission factor",
    "因子": "factor",
    "碳期货": "carbon futures",
    "期货": "futures",
    "用": "use",
    "商用": "commercial",
    "商用厨房": "commercial kitchen",
    "面包店": "bread store",
    "面包": "bread",
    "层烤炉": "layer oven",
    "烤炉": "oven",
    "配方": "formula",
    "配方指导服务": "formula guide service",
    "不合格": "non-compliant",
    "不合格产品管理": "non-compliant product management",
    "不合格品": "non-compliant product",
    "续租率": "renewal rate",
    "续租": "renewal rental",
    "帐篷客户": "tent customer",
    "客户": "customer",
    "遮阳设备": "sunshade equipment",
    "遮阳": "sunshade",
    "设备": "equipment",
    "合同管理": "contract management",
    "合同": "contract",
    "烧烤设备安全培训": "barbecue equipment safety training",
    "烧烤": "barbecue",
    "设备安全培训": "equipment safety training",
    "安全培训": "safety training",
    "培训": "training",

    # Comprehensive remaining translations
    "并离网切换": "grid off-grid switching",
    "风光储一体": "wind solar storage integration",
    "光储充一体": "solar storage charging integration",
    "光储柴": "solar storage diesel",
    "志愿者招募": "volunteer recruitment",
    "志愿者": "volunteer",
    "保障缺口": "coverage gap",
    "临时安保": "temporary security",
    "安保": "security",
    "间隔重复": "spaced repetition",
    "记忆卡片": "memory card",
    "疫苗接种": "vaccine injection",
    "接种": "injection",
    "赛事报名": "competition registration",
    "报名": "registration",
    "噪音消除": "noise cancellation",
    "噪音屏蔽": "noise shielding",
    "地板打磨": "floor polishing",
    "打磨": "polishing",
    "打磨使用": "polishing usage",
    "通话录音": "call recording",
    "保险代理": "insurance agency",
    "车位周转": "parking turnover",
    "自驾旅行": "self-driving travel",
    "旅行": "travel",
    "无接触退": "contactless return",
    "无接触": "contactless",
    "霍尼韦尔": "Honeywell",
    "施耐德": "Schneider",
    "呼叫中心": "call center",
    "电压暂降": "voltage sag",
    "造价一体": "cost integration",
    "阶梯电价": "tiered electricity price",
    "阶梯": "tiered",
    "峰谷电价": "peak valley electricity price",
    "达人合作": "influencer collaboration",
    "珠宝移动": "jewelry mobile",
    "金价联动": "gold price linkage",
    "道德黄金": "ethical gold",
    "贵金属": "precious metal",
    "宝石产地": "gemstone origin",
    "宝石估价": "gemstone appraisal",
    "估价": "appraisal",
    "钻石溯源": "diamond traceability",
    "工匠工坊": "artisan workshop",
    "奢侈手表": "luxury watch",
    "振动压路": "vibratory roller",
    "压路机": "roller",
    "压路": "roller",
    "静碾压路": "static roller",
    "压实": "compaction",
    "专属球杆": "exclusive club",
    "条码扫描": "barcode scanning",
    "扫描": "scanning",
    "养生行业": "wellness industry",
    "敏感部位": "sensitive area",
    "规律发现": "pattern discovery",
    "发现": "discovery",
    "资料提交": "document submission",
    "提交": "submission",
    "生态效益": "ecological benefit",
    "效益": "benefit",
    "三维解剖": "3D anatomy",
    "动态几何": "dynamic geometry",
    "几何绘图": "geometry drawing",
    "几何证明": "geometry proof",
    "图形几何": "graphics geometry",
    "掌握程度": "mastery level",
    "方程求解": "equation solving",
    "求解": "solving",
    "符号运算": "symbolic operation",
    "代数解法": "algebraic solution",
    "代数": "algebra",
    "词汇扩充": "vocabulary expansion",
    "词汇练习": "vocabulary practice",
    "发音练习": "pronunciation practice",
    "口语发音": "oral pronunciation",
    "发音纠错": "pronunciation correction",
    "发音": "pronunciation",
    "文本朗读": "text reading",
    "朗读": "reading aloud",
    "屏幕阅读": "screen reading",
    "口语练习": "oral practice",
    "练习": "practice",
    "逻辑思维": "logical thinking",
    "思维": "thinking",
    "防晒涂抹": "sunscreen application",
    "防晒": "sunscreen",
    "颜色形状": "color shape",
    "家庭维系": "family bonding",
    "急救演练": "emergency drill",
    "急救": "first aid",
    "名额释放": "slot release",
    "名额": "slot",
    "穿衣换衣": "dressing changing",
    "换尿布": "diaper changing",
    "尿布": "diaper",
    "牙齿发育": "teeth development",
    "家园共育": "family school co-education",
    "疏散演练": "evacuation drill",
    "疏散": "evacuation",
    "身高体重": "height weight",
    "身高": "height",
    "体重": "weight",
    "卫生习惯": "hygiene habit",
    "卫生": "hygiene",
    "图书阅读": "book reading",
    "图书借阅": "book borrowing",
    "图书": "book",
    "借阅": "borrowing",
    "康复诊所": "rehabilitation clinic",
    "诊所": "clinic",
    "身体成分": "body composition",
    "成分": "composition",
    "穿搭选择": "outfit selection",
    "穿搭": "outfit",
    "稳定跑鞋": "stable running shoes",
    "跑鞋": "running shoes",
    "乳清蛋白": "whey protein",
    "蛋白粉": "protein powder",
    "蛋白": "protein",
    "短时高频": "short duration high frequency",
    "快递收发": "express delivery collection",
    "快递分发": "express distribution",
    "快递": "express",
    "收发": "collection distribution",
    "分发": "distribution",
    "网球租赁": "tennis rental",
    "误差校正": "error correction",
    "校正": "correction",
    "暖通空调": "HVAC",
    "食谱整理": "recipe organization",
    "食谱": "recipe",
    "成就徽章": "achievement badge",
    "徽章": "badge",
    "讲故事": "storytelling",
    "故事": "story",
    "关键词": "keyword",
    "预抵达": "pre-arrival",
    "抵达": "arrival",
    "延迟退": "delayed check-out",
    "延迟": "delay",
    "退": "check-out",
    "一致性": "consistency",
    "小红书": "RedNote",
    "转文字": "convert to text",
    "文字": "text",
    "话练习": "speech practice",
    "候补名": "waitlist",
    "候补": "waitlist",
    "首次合": "first synthesis",
    "合": "synthesis",
    "天然气": "natural gas",
    "充放电": "charge discharge",
    "绝缘老化": "insulation aging",
    "老化": "aging",
    "绝缘": "insulation",
    "预付费": "prepaid",
    "所得税": "income tax",
    "税": "tax",
    "跨地区": "cross-region",
    "车编号": "vehicle numbering",
    "编号": "numbering",
    "团体课": "group class",
    "团体": "group",
    "绳磨损": "rope wear",
    "磨损": "wear",
    "知名度": "brand awareness",
    "活跃度": "activity level",
    "禁忌症": "contraindication",
    "中间件": "middleware",
    "防泄露": "leak prevention",
    "泄露": "leak",
    "文索引": "document indexing",
    "词记忆": "word memory",
    "点记忆": "point memory",
    "构尿布": "structured diaper",
    "生长曲": "growth curve",
    "生长": "growth",
    "太阳镜": "sunglasses",
    "性价比": "cost performance ratio",
    "筋膜枪": "massage gun",
    "体重秤": "weight scale",
    "体脂秤": "body fat scale",
    "秤": "scale",
    "垫防滑": "mat anti-slip",
    "防滑": "anti-slip",
    "自托管": "self-hosted",
    "托管": "hosted",
    "一次合": "one-time synthesis",
    "许可证": "license",
    "原标识": "original identifier",
    "标识": "identifier",
    "排行榜": "ranking",
    "天赋": "talent",
    "收费": "fee",
    "娱乐": "entertainment",
    "统一": "unified",
    "意识": "awareness",
    "因素": "factor",
    "耗材": "consumable",
    "辅导": "tutoring",
    "内控": "internal control",
    "拍照": "photography",
    "路由": "routing",
    "提取": "extraction",
    "理算": "adjustment",
    "车队": "fleet",
    "生物": "biology",
    "讨论": "discussion",
    "排课": "course scheduling",
    "金融": "finance",
    "午睡": "nap",
    "如厕": "toilet",
    "自理": "self-care",
    "膳食": "diet",
    "外出": "outing",
    "操场": "playground",
    "康复": "rehabilitation",
    "划船": "rowing",
    "跳绳": "jump rope",
    "总部": "headquarters",
    "施工": "construction",
    "五金": "hardware",
    "泵车": "pump truck",
    "签约": "signing",
    "核保": "underwriting",
    "业绩": "performance",
    "传播": "spread",
    "暂定": "tentative",
    "特殊": "special",
    "娱乐活动": "entertainment activity",
    "收费标准": "fee standard",
    "收费模式": "fee model",
    "统一管理": "unified management",
    "安全意识": "safety awareness",
    "影响因素": "influencing factor",
    "耗材管理": "consumable management",
    "辅导课程": "tutoring course",
    "文本提取": "text extraction",
    "拍照识别": "photo identification",
    "路由管理": "routing management",
    "理算服务": "adjustment service",
    "车队管理": "fleet management",
    "园林施工": "landscaping construction",
    "生物识别": "biometric identification",
    "讨论区": "discussion area",
    "排课系统": "course scheduling system",
    "金融服务": "financial service",
    "午睡管理": "nap management",
    "如厕训练": "toilet training",
    "自理能力": "self-care ability",
    "膳食管理": "diet management",
    "外出管理": "outing management",
    "操场管理": "playground management",
    "康复治疗": "rehabilitation treatment",
    "划船机": "rowing machine",
    "跳绳训练": "jump rope training",
    "总部管理": "headquarters management",
    "施工管理": "construction management",
    "五金工具": "hardware tools",
    "泵车租赁": "pump truck rental",
    "签约管理": "signing management",
    "核保系统": "underwriting system",
    "业绩考核": "performance assessment",
    "传播策略": "spread strategy",
    "暂定预约": "tentative booking",
    "特殊需求": "special needs",
    "天赋识别": "talent identification",
    "天赋评估": "talent assessment",

    # More single-character and phrase translations
    "现货": "spot goods",
    "现货交易系统": "spot goods transaction system",
    "交易": "transaction",
    "凝聚力": "cohesion",
    "凝聚": "cohesion",
    "话术": "script",
    "上传": "upload",
    "传": "transmission",
    "溯源": "traceability",
    "阻力": "resistance",
    "阻力级别": "resistance level",
    "级别": "level",
    "自有": "own",
    "自有分销": "own distribution",
    "分销": "distribution",
    "字母": "letter",
    "字母记录": "letter record",
    "资本配置": "capital configuration",
    "资本": "capital",
    "配置": "configuration",
    "专属服务": "exclusive service",
    "重型设备": "heavy equipment",
    "重型": "heavy",
    "中长期": "medium-long term",
    "中长": "medium-long",
    "中型": "medium-sized",
    "中型矿山机械": "medium-sized mining machine",
    "矿山机械": "mining machine",
    "矿山": "mining",
    "智慧水务": "smart water service",
    "智慧": "smart",
    "水务": "water service",
    "职场技能": "workplace skill",
    "职场": "workplace",
    "直销预订": "direct sales booking",
    "直销": "direct sales",
    "暂态仿真": "transient simulation",
    "暂态": "transient",
    "仿真": "simulation",
    "在用": "in-use",
    "在用产品": "in-use product",
    "灾难恢复": "disaster recovery",
    "灾难": "disaster",
    "圆锯租赁": "circular saw rental",
    "圆锯": "circular saw",
    "锯": "saw",
    "语义搜索": "semantic search",
    "语义": "semantic",
    "逾期预警": "overdue alert",
    "逾期": "overdue",
    "有源滤波": "active source filtering",
    "有源": "active source",
    "源": "source",
    "滤波": "filtering",
    "婴幼儿护理": "infant nursing",
    "婴幼儿": "infant",
    "幼儿": "infant",
    "护理": "nursing",
    "饮食追踪": "diet tracking",
    "饮食": "diet",
    "饮料行业": "beverage industry",
    "饮料": "beverage",
    "溢出运营": "overflow operation",
    "溢出": "overflow",
    "一体化教育": "integrated education",
    "一体化": "integrated",
    "演练规划": "drill planning",
    "演练": "drill",
    "演讲培训": "speech training",
    "演讲技巧": "speech technique",
    "演讲": "speech",
    "雪季高峰": "snow season peak",
    "雪季": "snow season",
    "削峰调度": "peak shaving scheduling",
    "削峰": "peak shaving",
    "削峰效果评估": "peak shaving effect assessment",
    "许可追踪": "license tracking",
    "许可": "license",
    "修剪机": "pruning machine",
    "修剪": "pruning",
    "心率监测": "heart rate monitoring",
    "心率": "heart rate",
    "泄漏检测": "leak detection",
    "谐波分析": "harmonic analysis",
    "谐波": "harmonic",
    "校园网络": "campus network",
    "校园": "campus",
    "小型矿山机械": "small mining machine",
    "小型": "small",
    "小米手环": "Xiaomi wristband",
    "小米": "Xiaomi",
    "手环": "wristband",
    "环境": "environment",
    "消耗追踪": "consumption tracking",
    "消耗": "consumption",
    "消耗统计分析": "consumption statistical analysis",
    "洗手记录": "hand washing record",
    "洗手": "hand washing",
    "污水处理": "waste water processing",
    "污水": "waste water",
    "水处理": "water processing",
    "处理": "processing",
    "监测": "monitoring",
    "精度": "precision",
    "监测精度": "monitoring precision",
    "平台": "platform",
    "检测平台": "detection platform",
    "分析": "analysis",
    "分析平台": "analysis platform",
    "追踪系统": "tracking system",
    "追踪": "tracking",
    "统计分析": "statistical analysis",
    "统计": "statistics",
    "记录追踪": "record tracking",
    "记录": "record",
    "预订系统": "booking system",
    "预订": "booking",
    "租赁平台": "rental platform",
    "租赁": "rental",
    "租赁价格": "rental price",
    "价格": "price",
    "培训平台": "training platform",
    "培训工具": "training tools",
    "技巧工具": "technique tools",
    "技巧": "technique",
    "效果评估": "effect assessment",
    "效果": "effect",
    "调度平台": "scheduling platform",
    "调度": "scheduling",
    "管理": "management",
    "追踪管理": "tracking management",
    "管理平台": "management platform",
    "网络安全": "network safety",
    "网络": "network",
    "安全": "safety",
    "安全培训": "safety training",
    "矿山机械租赁": "mining machine rental",
    "矿山机械租赁系统": "mining machine rental system",
    "矿山机械租赁平台": "mining machine rental platform",
    "GPS追踪": "GPS tracking",
    "设备GPS追踪": "equipment GPS tracking",
    "中型矿山机械租赁平台": "medium-sized mining machine rental platform",
    "小型矿山机械租赁系统": "small mining machine rental system",

    # Comprehensive single-word and short phrase translations
    "钻石": "diamond",
    "钻石溯源": "diamond traceability",
    "钻石库存": "diamond inventory",
    "钻石证书": "diamond certificate",
    "证书": "certificate",
    "回头客": "return customer",
    "等离子": "plasma",
    "冲击钻": "impact drill",
    "冲击": "impact",
    "录音": "recording",
    "架构": "architecture",
    "律师": "lawyer",
    "冲突": "conflict",
    "加速": "acceleration",
    "华为": "Huawei",
    "诉讼": "litigation",
    "触达": "reach",
    "逆向": "reverse",
    "复盘": "review",
    "抢修": "emergency repair",
    "交付": "delivery",
    "供需": "supply demand",
    "电焊": "electric welding",
    "焊": "welding",
    "焊接": "welding",
    "钥匙": "key",
    "付款": "payment",
    "钉枪": "nail gun",
    "钉": "nail",
    "分割": "segmentation",
    "瓷砖": "tile",
    "造价": "cost",
    "高等": "higher",
    "粉尘": "dust",
    "友好": "friendly",
    "工作": "work",
    "渲染": "rendering",
    "屏幕": "screen",
    "款项": "payment",
    "扣款": "deduction",
    "累积": "accumulation",
    "清算": "clearing",
    "交互": "interaction",
    "保存": "save",
    "律所": "law firm",
    "欢迎": "welcome",
    "负面": "negative",
    "真伪": "authenticity",
    "伤害": "injury",
    "比较": "comparison",
    "短路": "short circuit",
    "位置": "position",
    "结构": "structure",
    "积压": " backlog",
    "联动": "linkage",
    "互助": "mutual aid",
    "吹叶": "leaf blowing",
    "吹叶机": "leaf blower",
    "礼物": "gift",
    "钳子": "pliers",
    "钳": "pliers",
    "砂光": "sanding",
    "砂光机": "sander",
    "抖音": "TikTok",
    "唤醒": "awakening",
    "沉淀": "settling",
    "人事": "HR",
    "携带": "carrying",
    "调节": "adjustment",
    "尺码": "size",
    "拼图": "puzzle",
    "活跃": "active",
    "交流": "communication",
    "外卖": "delivery",
    "体能": "physical fitness",
    "经纬": "longitude latitude",
    "一体": "integrated",
    "遗失": "lost",
    "筹划": "planning",
    "沉浸": "immersive",
    "回顾": "review",
    "调频": "frequency modulation",
    "排队": "queue",
    "集团": "group",
    "国际": "international",
    "担保": "guarantee",
    "开门": "opening",
    "特征": "feature",
    "供气": "gas supply",
    "信任": "trust",
    "达索": "Dassault",
    "挥杆": "swing",
    "恶劣": "harsh",
    "漏损": "leakage loss",
    "油温": "oil temperature",
    "油位": "oil level",
    "货物": "goods",
    "三维": "3D",
    "售后": "after-sales",
    "临时": "temporary",
    "背包": "backpack",
    "周转": "turnover",
    "冥想": "meditation",
    "中央": "central",
    "旅游": "tourism",
    "匿名": "anonymous",
    "调拨": "allocation",
    "时效": "timeliness",
    "获取": "acquisition",
    "垫材": "padding material",
    "垫": "pad",
    "球场": "court",
    "外送": "delivery",
    "消纳": "consumption",
    "序列": "sequence",
    "地理": "geography",
    "班车": "shuttle bus",
    "图谱": "graph",
    "词汇": "vocabulary",
    "金属": "metal",
    "专家": "expert",
    "图纸": "drawing",
    "说明": "description",
    "经销": "distribution",
    "跨境": "cross-border",
    "声音": "sound",
    "咨询": "consulting",
    "风控": "risk control",
    "证照": "certificate license",
    "成果": "achievement",
    "验收": "acceptance",
    "策划": "planning",
    "判决": "judgment",
    "忠诚": "loyalty",
    "接案": "case acceptance",
    "日程": "schedule",
    "弹性": "flexibility",
    "研判": "judgment",
    "导游": "tour guide",
    "分摊": "sharing",
    "角磨": "angle grinding",
    "角磨机": "angle grinder",
    "工厂": "factory",
    "关键": "critical",
    "摩托": "motorcycle",
    "资料": "material",
    "工序": "process",
    "损耗": "loss",
    "履带": "track",
    "总结": "summary",
    "钢琴": "piano",
    "后勤": "logistics",
    "资讯": "information",
    "吉他": "guitar",
    "客流": "customer flow",
    "地图": "map",
    "灵活": "flexible",
    "选择": "selection",
    "播客": "podcast",
    "整理": "organization",
    "保洁": "cleaning",
    "高管": "executive",
    "外语": "foreign language",
    "串联": "series connection",
    "防范": "prevention",
    "滑移": "sliding",
    "节约": "saving",
    "队列": "queue",
    "免费": "free",
    "疏通": "clearing",
    "关联": "association",
    "种类": "category",
    "动态": "dynamic",
    "二次": "secondary",
    "日志": "log",
    "竞价": "bidding",
    "竞猜": "prediction",
    "削减": "reduction",
    "缺货": "stockout",
    "清除": "clearing",
    "点位": "position",
    "多元": "multi-dimensional",
    "安防": "security",
    "桨板": "paddle board",
    "道德": "moral",
    "弯管": "pipe bending",
    "弯": "bend",
    "几何": "geometry",
    "电压": "voltage",
    "维度": "dimension",
    "状况": "status",
    "变革": "transformation",
    "聊天": "chat",
    "释放": "release",
    "收取": "collection",
    "标注": "labeling",
    "审查": "review",
    "疾病": "disease",
    "服饰": "clothing",
    "标牌": "sign",
    "零件": "part",
    "驾考": "driving test",
    "设定": "setting",
    "中心": "center",
    "官方": "official",
    "签批": "signing approval",
    "薪酬": "salary",
    "治疗": "treatment",
    "粘性": "stickiness",
    "哈佛": "Harvard",
    "缓震": "shock absorption",
    "催收": "collection",
    "高级": "advanced",
    "隔离": "isolation",
    "配气": "gas distribution",
    "灾害": "disaster",
    "母带": "master tape",
    "动作": "action",
    "查找": "search",
    "喷涂": "spraying",
    "过滤": "filtering",
    "奢侈": "luxury",
    "营收": "revenue",
    "核验": "verification",
    "个人": "personal",
    "报修": "repair request",
    "课件": "courseware",
    "原因": "reason",
    "网购": "online shopping",
    "庆祝": "celebration",
    "社群": "community",
    "清仓": "clearance",
    "服装": "clothing",
    "网关": "gateway",
    "营运": "operation",
    "难度": "difficulty",
    "纳米": "nano",
    "流通": "circulation",
    "分流": "distribution",
    "续费": "renewal",
    "持有": "holding",
    "余额": "balance",
    "车位": "parking space",
    "球车": "ball cart",
    "起草": "drafting",
    "发行": "issuance",
    "遵循": "compliance",
    "法庭": "court",
    "供应": "supply",
    "开关": "switch",
    "融资": "financing",
    "输出": "output",
    "日常": "daily",
    "调峰": "peak regulation",
    "深度": "depth",
    "内燃": "internal combustion",
    "刷牙": "brushing teeth",
    "物资": "supplies",
    "割草": "mowing",
    "四级": "level 4",
    "门锁": "door lock",
    "驾照": "driver license",
    "增强": "enhancement",
    "培育": "cultivation",
    "护膝": "knee pad",
    "备考": "exam preparation",
    "口腔": "oral",
    "交换": "exchange",
    "成人": "adult",
    "挖坑": "digging",
    "托儿": "childcare",
    "复检": "re-inspection",
    "生态": "ecological",
    "保证": "guarantee",
    "保温": "insulation",
    "引导": "guidance",
    "披露": "disclosure",
    "框架": "framework",
    "投篮": "shooting",
    "眼镜": "glasses",
    "抛光": "polishing",
    "货架": "shelf",
    "实施": "implementation",
    "保值": "value preservation",
    "稳定": "stable",
    "讲座": "lecture",
    "输电": "power transmission",
    "成长": "growth",
    "驱动": "drive",
    "防盗": "anti-theft",
    "燃料": "fuel",
    "一站": "one-stop",
    "比价": "price comparison",
    "差距": "gap",
    "超充": "super charging",
    "经济": "economic",
    "护具": "protective gear",
    "启蒙": "enlightenment",
    "穿戴": "wearable",
    "社保": "social security",
    "考证": "certification exam",
    "购买": "purchase",
    "前瞻性": "forward-looking",
    "瞻性": "forward-looking",
    "前瞻": "forward-looking",
    "家庭": "family",
    "未来": "future",
    "电锤": "electric hammer",
    "抽奖": "lottery",
    "流转": "circulation",
    "方法": "method",
    "钓鱼": "fishing",
    "振动": "vibration",
    "评级": "rating",
    "扩张": "expansion",
    "牙齿": "teeth",
    "电价": "electricity price",
    "往复": "reciprocating",
    "团建": "team building",
    "讲解": "explanation",
    "潮流": "trend",
    "裂变": "fission",
    "锻炼": "exercise",
    "核销": "verification write-off",
    "透明": "transparent",
    "折旧": "depreciation",
    "工坊": "workshop",
    "沉睡": "sleeping",
    "齐": "complete",
    "聚": "gathering",
    "开": "open",
    "者": "person",
    "补": "supplement",
    "长": "long",
    "师": "master",
    "材": "material",
    "馈": "feedback",
    "人": "person",
    "扳": "wrench",
    "所": "office",
    "初": "initial",
    "口": "mouth",
    "簿": "book",
    "书": "book",
    "厂": "factory",
    "应": "response",
    "原": "original",
    "竞": "competition",
    "总": "total",
    "桩": "pile",
    "绿": "green",
    "潜": "potential",
    "版": "version",
    "轮": "wheel",
    "卡": "card",
    "瞻": "forward",
    "度": "degree",
    "途": "purpose",
    "下": "down",
    "转": "turn",
    "最": "most",
    "板": "board",
    "约": "agreement",
    "过": "pass",
    "链": "chain",
    "容": "capacity",
    "方": "method",
    "鞋": "shoe",
    "镜": "mirror",
    "监": "monitor",
    "算": "calculation",
    "场": "field",
    "法": "method",
    "预": "pre",
    "提": "提",
    "站": "station",
    "到": "to",
    "后": "after",
    "抄": "copy",
    "闻": "news",
    "点": "point",
    "老": "old",
    "距": "distance",
    "录": "record",
    "侵": "intrusion",
    "塔": "tower",
    "不": "not",
    "温": "temperature",
    "家": "home",
    "验": "verify",
    "跨": "cross",
    "业": "industry",
    "短": "short",
    "话": "speech",
    "芯": "core",
    "乐": "music",
    "壶": "pot",
    "名": "name",
    "关": "relation",
    "签": "sign",
    "耳": "ear",
    "桌": "table",
    "污": "pollution",
    "动": "movement",
    "子": "child",
    "球": "ball",
    "日": "day",
    "分": "division",
    "篷": "canopy",
    "货": "goods",
    "数": "number",
    "孵": "incubate",
    "型": "type",
    "队": "team",
    "网": "network",
    "本": "base",
    "拍": "photograph",
    "礼": "gift",
    "洗": "wash",
    "作": "work",
    "使": "use",
    "性": "nature",
    "固": "solid",
    "时": "time",
    "撮": "撮",
    "溯": "trace",
    "投": "invest",
    "词": "word",
    "心": "heart",
    "反": "reverse",
    "曲": "curve",
    "流": "flow",
    "假": "false",
    "沿": "along",
    "阻": "resistance",
    "会": "meeting",
    "裤": "pants",
    "费": "fee",
    "绩": "performance",
    "位": "position",
    "锁": "lock",
    "婴": "infant",
    "奢": "luxury",
    "风": "wind",
    "多": "many",
    "回": "return",

    # Final remaining translations
    "成": "function",
    "成功": "success",
    "小程序": "mini program",
    "程序": "program",
    "文库": "text library",
    "库": "library",
    "索引系统": "index system",
    "索引": "index",
    "气体泄漏": "gas leak",
    "气泄漏检测": "gas leak detection",
    "气压力调整": "gas pressure adjustment",
    "压力": "pressure",
    "手工工具": "hand tools",
    "手工": "hand work",
    "手工工具库存": "hand tools inventory",
    "手工工具租赁": "hand tools rental",
    "电气可视化": "electrical visualization",
    "电气": "electrical",
    "可视化": "visualization",
    "电气可视化管理": "electrical visualization management",
    "电气可视化系统": "electrical visualization system",
    "机构管理": "institution management",
    "机构": "institution",
    "文档索引": "document index",
    "文档索引系统": "document index system",
    "车辆": "vehicle",
    "直播课程": "live streaming course",
    "课程": "course",
    "会员专属": "member exclusive",
    "瑜伽垫": "yoga mat",
    "瑜伽": "yoga",
    "垫": "mat",
    "搅拌车租赁": "mixing vehicle rental",
    "搅拌车": "mixing vehicle",
    "搅拌车租赁软件": "mixing vehicle rental software",
    "目的地": "destination",
    "目的": "purpose",
    "目的地行程规划": "destination itinerary planning",
    "目的地管理公司": "destination management company",
    "目的地服务": "destination service",
    "行程规划": "itinerary planning",
    "行程": "itinerary",
    "智能重合设备": "smart overlap device",
    "重合": "overlap",
    "重合设备": "overlap device",
    "SPA心理压力": "SPA psychological pressure",
    "心理": "psychology",
    "心理压力": "psychological pressure",
    "使用合规管理": "usage compliance management",
    "使用": "usage",
    "合规": "compliance",
    "合规管理": "compliance management",
    "高精度定位": "high precision positioning",
    "高精度": "high precision",
    "精度定位技术": "precision positioning technology",
    "定位": "positioning",
    "定位技术": "positioning technology",
    "供水可靠性": "water supply reliability",
    "供水": "water supply",
    "可靠性平台": "reliability platform",
    "供水可靠性平台": "water supply reliability platform",
    "Brinkerhoff成功案例": "Brinkerhoff success case",
    "案例": "case",
    "理赔微信小程序": "claim settlement WeChat mini program",
    "理赔": "claim settlement",
    "理赔AI文库": "claim settlement AI text library",
    "AI文库": "AI text library",
    "理赔文库分析": "claim settlement text library analysis",
    "理赔文库处理": "claim settlement text library processing",
    "文库分析": "text library analysis",
    "文库处理": "text library processing",
    "Data修复Tool": "data repair tool",
    "修复工具": "repair tool",
    "数字管理客户机构管理工具": "digital management customer institution management tools",
    "数字管理": "digital management",
    "客户机构": "customer institution",
    "机构管理工具": "institution management tools",
    "保险客户机构管理工具": "insurance customer institution management tools",
    "法律文档索引": "legal document index",
    "法律文档": "legal document",
    "法律": "legal",
    "管理系统客户机构管理工具": "management system customer institution management tools",
    "管理工具客户机构管理工具": "management tools customer institution management tools",
    "智能健身车辆": "smart fitness vehicle",
    "健身": "fitness",
    "智能健身": "smart fitness",
    "订单车": "order vehicle",
    "订单": "order",
    "SPA心理压力释放": "SPA psychological pressure release",
    "压力释放": "pressure release",
    "释放": "release",
    "使用合规管理工具": "usage compliance management tool",
    "供气压力调整": "gas supply pressure adjustment",
    "供气": "gas supply",
    "高压调整": "high pressure adjustment",
    "高压": "high pressure",
    "高压电源": "high pressure power supply",
    "电源": "power supply",
}

# Compound word patterns for dynamic translation
COMPOUND_PATTERNS = [
    # Handle mixed English-Chinese like "故障Forecast"
    (r'故障Forecast', 'fault prediction'),
    (r'维修Management', 'repair management'),
    (r'备件Management', 'spare parts management'),
    (r'车辆保养', 'vehicle maintenance'),
    # Handle patterns like "XXX系统", "XXX管理", etc.
    (r'(.+)管理系统', lambda m: f"{translate_word(m.group(1))} management system"),
    (r'(.+)管理软件', lambda m: f"{translate_word(m.group(1))} management software"),
    (r'(.+)管理平台', lambda m: f"{translate_word(m.group(1))} management platform"),
    (r'(.+)租赁系统', lambda m: f"{translate_word(m.group(1))} rental system"),
    (r'(.+)租赁软件', lambda m: f"{translate_word(m.group(1))} rental software"),
    (r'(.+)租赁平台', lambda m: f"{translate_word(m.group(1))} rental platform"),
    (r'(.+)租赁工具', lambda m: f"{translate_word(m.group(1))} rental tools"),
    (r'(.+)管理系统评测', lambda m: f"{translate_word(m.group(1))} management system review"),
    (r'(.+)系统评测', lambda m: f"{translate_word(m.group(1))} system review"),
    (r'(.+)软件评测', lambda m: f"{translate_word(m.group(1))} software review"),
    (r'(.+)平台评测', lambda m: f"{translate_word(m.group(1))} platform review"),
    (r'(.+)工具评测', lambda m: f"{translate_word(m.group(1))} tools review"),
    (r'(.+)对比', lambda m: f"{translate_word(m.group(1))} comparison"),
]

def translate_word(word):
    """Translate a single word or compound word."""
    # First check direct dictionary
    if word in TRANSLATION_DICT:
        return TRANSLATION_DICT[word]

    # Try compound patterns
    for pattern, replacement in COMPOUND_PATTERNS:
        if isinstance(replacement, str):
            match = re.match(pattern, word)
            if match:
                return replacement
        else:
            match = re.match(pattern, word)
            if match:
                return replacement(match)

    # Split compound words and translate each part
    # Common compound patterns
    parts = []
    remaining = word

    # Try to find known words
    for known_word in sorted(TRANSLATION_DICT.keys(), key=len, reverse=True):
        if known_word in remaining:
            idx = remaining.find(known_word)
            if idx > 0:
                # There's text before this known word
                prefix = remaining[:idx]
                if prefix in TRANSLATION_DICT:
                    parts.append(TRANSLATION_DICT[prefix])
                else:
                    parts.append(prefix)  # Keep as-is if unknown
            parts.append(TRANSLATION_DICT[known_word])
            remaining = remaining[idx + len(known_word):]

    if remaining and remaining in TRANSLATION_DICT:
        parts.append(TRANSLATION_DICT[remaining])
        remaining = ""

    if parts:
        if remaining:
            parts.append(remaining)
        return " ".join(parts)

    # Return original if no translation found
    return word

def contains_chinese(text):
    """Check if text contains Chinese characters."""
    return bool(re.search(r'[一-龥]', text))

def translate_keyword(keyword):
    """Translate a single keyword."""
    # If no Chinese, return as-is
    if not contains_chinese(keyword):
        return keyword

    # First try direct dictionary lookup
    if keyword in TRANSLATION_DICT:
        return TRANSLATION_DICT[keyword]

    # Try patterns with lambda
    for pattern, replacement in COMPOUND_PATTERNS:
        match = re.match(pattern, keyword)
        if match:
            if callable(replacement):
                return replacement(match)
            return replacement

    # Translate compound words
    return translate_word(keyword)

def process_file(file_path):
    """Process a single JSON file."""
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            data = json.load(f)

        # Check if seo_keywords exists and has Chinese
        if 'seo_keywords' not in data:
            return False

        keywords = data['seo_keywords']
        if not isinstance(keywords, list):
            return False

        # Check if any keyword has Chinese
        has_chinese = any(contains_chinese(k) for k in keywords)
        if not has_chinese:
            return False

        # Translate keywords
        new_keywords = [translate_keyword(k) for k in keywords]

        # Only update if there's a change
        if new_keywords != keywords:
            data['seo_keywords'] = new_keywords

            with open(file_path, 'w', encoding='utf-8') as f:
                json.dump(data, f, ensure_ascii=False, indent=2)

            return True

        return False
    except Exception as e:
        print(f"Error processing {file_path}: {e}")
        return False

def find_files_with_chinese_keywords(data_dir):
    """Find all JSON files with Chinese seo_keywords."""
    files = []
    for root, dirs, filenames in os.walk(data_dir):
        # Skip zh directory
        dirs_to_remove = [d for d in dirs if d == 'zh']
        for d in dirs_to_remove:
            dirs.remove(d)

        for filename in filenames:
            if filename.endswith('.json'):
                file_path = os.path.join(root, filename)
                try:
                    with open(file_path, 'r', encoding='utf-8') as f:
                        data = json.load(f)

                    if 'seo_keywords' in data and isinstance(data['seo_keywords'], list):
                        keywords = data['seo_keywords']
                        if any(contains_chinese(k) for k in keywords):
                            files.append(file_path)
                except Exception as e:
                    pass

    return files

def main():
    """Main function to process all files."""
    data_dir = '/Users/gejiayu/owner/seo/data'

    print("Finding files with Chinese seo_keywords...")
    files = find_files_with_chinese_keywords(data_dir)
    print(f"Found {len(files)} files to process")

    # Process in batches
    batch_size = 100
    total_processed = 0
    total_updated = 0

    for i in range(0, len(files), batch_size):
        batch = files[i:i + batch_size]
        batch_updated = 0

        for file_path in batch:
            if process_file(file_path):
                batch_updated += 1

        total_processed += len(batch)
        total_updated += batch_updated

        print(f"Processed batch {i//batch_size + 1}: {len(batch)} files, {batch_updated} updated")
        print(f"Total progress: {total_processed}/{len(files)} files, {total_updated} updated")

    print(f"\nCompleted! Total files processed: {total_processed}")
    print(f"Total files updated: {total_updated}")

if __name__ == '__main__':
    main()