#!/usr/bin/env python3
"""
Translate Chinese characters in medical equipment rental JSON files to English.
"""

import json
import re
import os
from pathlib import Path

# Comprehensive translation dictionary
TRANSLATIONS = {
    # Common Chinese words
    "是": "is",
    "的": "of",
    "和": "and",
    "与": "and",
    "等": "etc",
    "等等": "etc",
    "核心": "core",
    "环节": "aspect",
    "主要": "main",
    "重要": "important",
    "关键": "key",
    "功能": "functionality",
    "系统": "System",
    "平台": "Platform",
    "工具": "Tool",
    "软件": "Software",
    "管理": "Management",
    "服务": "Service",
    "业务": "business",
    "企业": "Enterprise",
    "客户": "Customer",
    "用户": "User",
    "产品": "Product",
    "设备": "Equipment",
    "器械": "Equipment",
    "医疗": "Medical",
    "医院": "Hospital",
    "诊所": "clinic",
    "机构": "institution",
    "部门": "Department",
    "团队": "Team",
    "人员": "Personnel",
    "专业": "Professional",
    "智能": "Intelligent",
    "自动": "Automatic",
    "电子": "Electronic",
    "数字": "Digital",
    "数据": "Data",
    "信息": "Information",
    "分析": "analysis",
    "报告": "Report",
    "记录": "Records",
    "跟踪": "Tracking",
    "追踪": "Tracking",
    "监控": "Monitoring",
    "预测": "Prediction",
    "提醒": "Reminder",
    "警告": "Warning",
    "通知": "Notification",
    "计划": "Plan",
    "方案": "Solution",
    "策略": "Strategy",
    "流程": "Process",
    "执行": "Execution",
    "实施": "Implementation",
    "部署": "Deployment",
    "整合": "Integration",
    "同步": "Synchronization",
    "更新": "Update",
    "维护": "Maintenance",
    "维修": "Maintenance",
    "保养": "Maintenance",
    "清洁": "cleaning",
    "消毒": "disinfection",
    "安全": "Safety",
    "合规": "Compliance",
    "认证": "Certification",
    "证书": "Certificate",
    "注册": "Registration",
    "审核": "Audit",
    "检查": "Inspection",
    "检验": "Inspection",
    "测试": "Test",
    "评估": "Assessment",
    "评价": "Evaluation",
    "比较": "Comparison",
    "对比": "Comparison",
    "选择": "Selection",
    "推荐": "Recommendation",
    "建议": "Recommendation",
    "定价": "Pricing",
    "价格": "Price",
    "费用": "Fee",
    "成本": "Cost",
    "预算": "Budget",
    "收入": "Revenue",
    "利润": "Profit",
    "财务": "Financial",
    "会计": "Accounting",
    "发票": "Invoice",
    "合同": "Contract",
    "订单": "Order",
    "采购": "Procurement",
    "租赁": "Rental",
    "出租": "Rental",
    "归还": "Return",
    "续租": "renewal",
    "库存": "Inventory",
    "资产": "Asset",
    "资源": "Resource",
    "档案": "Archive",
    "文档": "Document",
    "文件": "Document",
    "模板": "Template",
    "标准": "Standard",
    "规范": "Standard",
    "流程": "Workflow",
    "操作": "Operation",
    "任务": "Task",
    "项目": "Project",
    "目标": "Target",
    "指标": "Indicator",
    "绩效": "Performance",
    "效率": "Efficiency",
    "效果": "Effectiveness",
    "质量": "Quality",
    "风险": "Risk",
    "问题": "Issue",
    "挑战": "Challenge",
    "机会": "Opportunity",
    "趋势": "Trend",
    "发展": "Development",
    "创新": "Innovation",
    "转型": "Transformation",
    "升级": "Upgrade",
    "优化": "Optimization",
    "改进": "Improvement",
    "提升": "Improvement",
    "增强": "Enhancement",
    "扩展": "Expansion",
    "扩展": "Extension",
    "定制": "Customization",
    "配置": "Configuration",
    "设置": "Settings",
    "选项": "Options",
    "参数": "Parameters",
    "字段": "Field",
    "属性": "Property",
    "类型": "Type",
    "型号": "Model",
    "品牌": "Brand",
    "型号": "Model",
    "版本": "Version",
    "等级": "Level",
    "级别": "Level",
    "分类": "Classification",
    "类别": "Category",
    "种类": "Type",
    "领域": "Field",
    "行业": "Industry",
    "市场": "Market",
    "地区": "Region",
    "国家": "Country",
    "城市": "City",
    "位置": "Location",
    "地点": "Location",
    "时间": "Time",
    "日期": "Date",
    "周期": "Period",
    "频率": "Frequency",
    "范围": "Range",
    "规模": "Scale",
    "大小": "Size",
    "数量": "Quantity",
    "数量": "Amount",
    "总额": "Total",
    "总数": "Total",
    "平均": "Average",
    "最大": "Maximum",
    "最小": "Minimum",
    "范围": "Range",
    "限制": "Limit",
    "约束": "Constraint",
    "条件": "Condition",
    "要求": "Requirement",
    "需求": "Demand",
    "需求": "Requirement",
    "供给": "Supply",
    "供应": "Supply",
    "支持": "Support",
    "帮助": "Help",
    "咨询": "Consultation",
    "培训": "Training",
    "教育": "Education",
    "学习": "Learning",
    "知识": "Knowledge",
    "经验": "Experience",
    "技能": "Skill",
    "能力": "Capability",
    "权限": "Permission",
    "授权": "Authorization",
    "认证": "Authentication",
    "登录": "Login",
    "注册": "Registration",
    "身份": "Identity",
    "角色": "Role",
    "责任": "Responsibility",
    "职责": "Responsibility",
    "义务": "Obligation",
    "权利": "Right",
    "利益": "Benefit",
    "价值": "Value",
    "优势": "Advantage",
    "特点": "Feature",
    "特性": "Characteristic",
    "属性": "Attribute",
    "描述": "Description",
    "说明": "Explanation",
    "介绍": "Introduction",
    "概述": "Overview",
    "总结": "Summary",
    "结论": "Conclusion",
    "结果": "Result",
    "输出": "Output",
    "输入": "Input",
    "内容": "Content",
    "标题": "Title",
    "主题": "Subject",
    "标签": "Tag",
    "关键字": "Keyword",
    "关键词": "Keyword",
    "搜索": "Search",
    "查询": "Query",
    "筛选": "Filter",
    "排序": "Sorting",
    "分组": "Grouping",
    "汇总": "Summary",
    "聚合": "Aggregation",
    "统计": "Statistics",
    "计算": "Calculation",
    "处理": "Processing",
    "转换": "Conversion",
    "生成": "Generation",
    "创建": "Creation",
    "删除": "Deletion",
    "修改": "Modification",
    "编辑": "Editing",
    "保存": "Saving",
    "加载": "Loading",
    "导入": "Import",
    "导出": "Export",
    "备份": "Backup",
    "恢复": "Recovery",
    "重置": "Reset",
    "清空": "Clear",
    "刷新": "Refresh",
    "验证": "Verification",
    "确认": "Confirmation",
    "取消": "Cancellation",
    "撤销": "Undo",
    "重做": "Redo",
    "复制": "Copy",
    "粘贴": "Paste",
    "剪切": "Cut",
    "移动": "Move",
    "发送": "Send",
    "接收": "Receive",
    "传输": "Transfer",
    "存储": "Storage",
    "存档": "Archive",
    "归档": "Archive",
    "备份": "Backup",
    "安全": "Security",
    "加密": "Encryption",
    "解密": "Decryption",
    "防护": "Protection",
    "防护": "Protection",
    "预防": "Prevention",
    "控制": "Control",
    "管制": "Control",
    "监管": "Regulation",
    "法规": "Regulation",
    "法律": "Law",
    "政策": "Policy",
    "规则": "Rule",
    "制度": "System",
    "体系": "System",
    "框架": "Framework",
    "结构": "Structure",
    "架构": "Architecture",
    "设计": "Design",
    "开发": "Development",
    "编程": "Programming",
    "编码": "Coding",
    "测试": "Testing",
    "调试": "Debugging",
    "部署": "Deployment",
    "发布": "Release",
    "上线": "Launch",
    "下线": "Offline",
    "停止": "Stop",
    "暂停": "Pause",
    "继续": "Continue",
    "开始": "Start",
    "结束": "End",
    "完成": "Complete",
    "进行": "InProgress",
    "等待": "Waiting",
    "待处理": "Pending",
    "已处理": "Processed",
    "已完成": "Completed",
    "失败": "Failed",
    "成功": "Success",
    "错误": "Error",
    "异常": "Exception",
    "故障": "Failure",
    "损坏": "Damage",
    "丢失": "Loss",
    "删除": "Deleted",
    "新建": "New",
    "修改": "Modified",
    "更新": "Updated",
    "过时": "Outdated",
    "过期": "Expired",
    "到期": "Due",
    "延期": "Delayed",
    "提前": "Early",
    "准时": "OnTime",
    "及时": "Timely",
    "快速": "Fast",
    "高效": "Efficient",
    "稳定": "Stable",
    "可靠": "Reliable",
    "灵活": "Flexible",
    "可扩展": "Scalable",
    "可定制": "Customizable",
    "可配置": "Configurable",
    "可集成": "Integratable",
    "可访问": "Accessible",
    "可用": "Available",
    "不可用": "Unavailable",
    "在线": "Online",
    "离线": "Offline",
    "实时": "Realtime",
    "即时": "Instant",
    "同步": "Synchronous",
    "异步": "Asynchronous",
    "批量": "Batch",
    "单个": "Individual",
    "多个": "Multiple",
    "全部": "All",
    "部分": "Part",
    "局部": "Partial",
    "整体": "Overall",
    "综合": "Comprehensive",
    "详细": "Detailed",
    "简要": "Brief",
    "具体": "Specific",
    "抽象": "Abstract",
    "简单": "Simple",
    "复杂": "Complex",
    "容易": "Easy",
    "困难": "Difficult",
    "高级": "Advanced",
    "中级": "Intermediate",
    "初级": "Basic",
    "入门": "Introductory",
    "基础": "Basic",
    "进阶": "Advanced",
    "精通": "Expert",
    "专家": "Expert",
    "资深": "Senior",
    "经验丰富": "Experienced",
    "新手": "Novice",
    "初学者": "Beginner",
    "实习生": "Intern",
    "全职": "Fulltime",
    "兼职": "Parttime",
    "临时": "Temporary",
    "长期": "Longterm",
    "短期": "Shortterm",
    "永久": "Permanent",
    "固定": "Fixed",
    "可变": "Variable",
    "动态": "Dynamic",
    "静态": "Static",
    "公开": "Public",
    "私有": "Private",
    "内部": "Internal",
    "外部": "External",
    "本地": "Local",
    "远程": "Remote",
    "云端": "Cloud",
    "移动端": "Mobile",
    "网页": "Web",
    "桌面": "Desktop",
    "终端": "Terminal",
    "服务器": "Server",
    "客户端": "Client",
    "浏览器": "Browser",
    "应用": "Application",
    "小程序": "Miniapp",
    "插件": "Plugin",
    "扩展": "Extension",
    "组件": "Component",
    "模块": "Module",
    "包": "Package",
    "库": "Library",
    "框架": "Framework",
    "引擎": "Engine",
    "驱动": "Driver",
    "接口": "Interface",
    "协议": "Protocol",
    "标准": "Standard",
    "规范": "Specification",
    "代码": "Code",
    "脚本": "Script",
    "程序": "Program",
    "算法": "Algorithm",
    "逻辑": "Logic",
    "模型": "Model",
    "视图": "View",
    "控制器": "Controller",
    "服务": "Service",
    "网关": "Gateway",
    "代理": "Proxy",
    "负载均衡": "LoadBalancing",
    "缓存": "Cache",
    "队列": "Queue",
    "堆栈": "Stack",
    "数据库": "Database",
    "表": "Table",
    "行": "Row",
    "列": "Column",
    "索引": "Index",
    "查询": "Query",
    "事务": "Transaction",
    "连接": "Connection",
    "断开": "Disconnect",
    "重连": "Reconnect",
    "超时": "Timeout",
    "重试": "Retry",
    "失败": "Failure",
    "成功": "Success",
    "状态": "Status",
    "进度": "Progress",
    "完成度": "Completion",
    "百分比": "Percentage",
    "比例": "Ratio",
    "倍数": "Multiple",
    "分数": "Fraction",
    "整数": "Integer",
    "小数": "Decimal",
    "正数": "Positive",
    "负数": "Negative",
    "零": "Zero",
    "空": "Empty",
    "非空": "NonEmpty",
    "有效": "Valid",
    "无效": "Invalid",
    "正确": "Correct",
    "错误": "Wrong",
    "对": "Right",
    "错": "Wrong",
    "是": "Yes",
    "否": "No",
    "真": "True",
    "假": "False",
    "开": "On",
    "关": "Off",
    "启用": "Enable",
    "禁用": "Disable",
    "激活": "Activate",
    "停用": "Deactivate",
    "锁定": "Lock",
    "解锁": "Unlock",
    "冻结": "Freeze",
    "解冻": "Unfreeze",
    "挂起": "Suspend",
    "恢复": "Resume",
    "终止": "Terminate",
    "放弃": "Abort",
    "取消": "Cancel",
    "撤销": "Revoke",
    "删除": "Delete",
    "清除": "Clear",
    "重置": "Reset",
    "刷新": "Refresh",
    "同步": "Sync",
    "异步": "Async",
    "并发": "Concurrent",
    "顺序": "Sequential",
    "并行": "Parallel",
    "串行": "Serial",
    "单线程": "Singlethread",
    "多线程": "Multithread",
    "单进程": "Singleprocess",
    "多进程": "Multiprocess",
    "分布式": "Distributed",
    "集中式": "Centralized",
    "去中心化": "Decentralized",
    "区块链": "Blockchain",
    "人工智能": "ArtificialIntelligence",
    "机器学习": "MachineLearning",
    "深度学习": "DeepLearning",
    "神经网络": "NeuralNetwork",
    "自然语言处理": "NaturalLanguageProcessing",
    "计算机视觉": "ComputerVision",
    "语音识别": "SpeechRecognition",
    "图像识别": "ImageRecognition",
    "人脸识别": "FaceRecognition",
    "文字识别": "TextRecognition",
    "情感分析": "SentimentAnalysis",
    "语义分析": "SemanticAnalysis",
    "数据挖掘": "DataMining",
    "数据分析": "DataAnalysis",
    "数据可视化": "DataVisualization",
    "大数据": "BigData",
    "云计算": "CloudComputing",
    "物联网": "InternetofThings",
    "边缘计算": "EdgeComputing",
    "容器": "Container",
    "虚拟化": "Virtualization",
    "微服务": "Microservices",
    "服务网格": "ServiceMesh",
    "无服务器": "Serverless",
    "函数计算": "FunctionComputing",
    "自动化": "Automation",
    "机器人": "Robot",
    "流程自动化": "ProcessAutomation",
    "智能助手": "IntelligentAssistant",
    "聊天机器人": "Chatbot",
    "智能客服": "IntelligentCustomerService",
    "语音助手": "VoiceAssistant",
    "虚拟助手": "VirtualAssistant",
    "智能推荐": "IntelligentRecommendation",
    "智能搜索": "IntelligentSearch",
    "智能排序": "IntelligentSorting",
    "智能过滤": "IntelligentFiltering",
    "智能分类": "IntelligentClassification",
    "智能识别": "IntelligentRecognition",
    "智能分析": "IntelligentAnalysis",
    "智能预测": "IntelligentPrediction",
    "智能监控": "IntelligentMonitoring",
    "智能告警": "IntelligentAlerting",
    "智能调度": "IntelligentScheduling",
    "智能优化": "IntelligentOptimization",
    "智能决策": "IntelligentDecision",
    "智能控制": "IntelligentControl",
    "智能管理": "IntelligentManagement",
    "智能运维": "IntelligentOperations",
    "智能安全": "IntelligentSecurity",
    "智能风控": "IntelligentRiskControl",
    "智能合规": "IntelligentCompliance",
    "智能审计": "IntelligentAudit",
    "智能测试": "IntelligentTesting",
    "智能开发": "IntelligentDevelopment",
    "智能设计": "IntelligentDesign",
    "智能运营": "IntelligentOperations",
    "智能营销": "IntelligentMarketing",
    "智能销售": "IntelligentSales",
    "智能服务": "IntelligentService",
    "智能体验": "IntelligentExperience",
    "智能产品": "IntelligentProduct",
    "智能平台": "IntelligentPlatform",
    "智能系统": "IntelligentSystem",
    "智能工具": "IntelligentTool",
    "智能软件": "IntelligentSoftware",
    "智能应用": "IntelligentApplication",
    "智能解决方案": "IntelligentSolution",
    "智能商业模式": "IntelligentBusinessModel",
    "智能商业": "IntelligentBusiness",
    "智能经济": "IntelligentEconomy",
    "智能社会": "IntelligentSociety",
    "智能城市": "IntelligentCity",
    "智能交通": "IntelligentTransportation",
    "智能医疗": "IntelligentMedical",
    "智能教育": "IntelligentEducation",
    "智能金融": "IntelligentFinance",
    "智能制造": "IntelligentManufacturing",
    "智能农业": "IntelligentAgriculture",
    "智能物流": "IntelligentLogistics",
    "智能零售": "IntelligentRetail",
    "智能能源": "IntelligentEnergy",
    "智能环保": "IntelligentEnvironment",
    "智能安防": "IntelligentSecurity",
    "智能家居": "IntelligentHome",
    "智能穿戴": "IntelligentWearable",
    "智能终端": "IntelligentTerminal",
    "智能设备": "IntelligentDevice",
    "智能硬件": "IntelligentHardware",
    "智能芯片": "IntelligentChip",
    "智能传感器": "IntelligentSensor",
    "智能摄像头": "IntelligentCamera",
    "智能音箱": "IntelligentSpeaker",
    "智能电视": "IntelligentTV",
    "智能冰箱": "IntelligentRefrigerator",
    "智能洗衣机": "IntelligentWashingMachine",
    "智能空调": "IntelligentAirConditioner",
    "智能灯具": "IntelligentLighting",
    "智能门锁": "IntelligentLock",
    "智能开关": "IntelligentSwitch",
    "智能插座": "IntelligentSocket",
    "智能窗帘": "IntelligentCurtain",
    "智能窗帘": "IntelligentBlinds",
    "智能窗户": "IntelligentWindow",
    "智能门": "IntelligentDoor",
    "智能电梯": "IntelligentElevator",
    "智能楼梯": "IntelligentStairs",
    "智能车库": "IntelligentGarage",
    "智能停车场": "IntelligentParking",
    "智能楼宇": "IntelligentBuilding",
    "智能园区": "IntelligentPark",
    "智能工厂": "IntelligentFactory",
    "智能仓库": "IntelligentWarehouse",
    "智能物流中心": "IntelligentLogisticsCenter",
    "智能配送中心": "IntelligentDistributionCenter",
    "智能数据中心": "IntelligentDataCenter",
    "智能计算中心": "IntelligentComputingCenter",
    "智能运营中心": "IntelligentOperationsCenter",
    "智能控制中心": "IntelligentControlCenter",
    "智能指挥中心": "IntelligentCommandCenter",
    "智能调度中心": "IntelligentSchedulingCenter",
    "智能监控中心": "IntelligentMonitoringCenter",
    "智能服务中心": "IntelligentServiceCenter",
    "智能体验中心": "IntelligentExperienceCenter",
    "智能展示中心": "IntelligentExhibitionCenter",
    "智能培训中心": "IntelligentTrainingCenter",
    "智能研发中心": "IntelligentDevelopmentCenter",
    "智能设计中心": "IntelligentDesignCenter",
    "智能测试中心": "IntelligentTestingCenter",
    "智能运维中心": "IntelligentOperationsCenter",
    "智能安全中心": "IntelligentSecurityCenter",
    "智能风控中心": "IntelligentRiskControlCenter",
    "智能合规中心": "IntelligentComplianceCenter",
    "智能审计中心": "IntelligentAuditCenter",

    # Compound terms often seen
    "核心环节": "core aspect",
    "核心功能": "core functionality",
    "核心模块": "core Module",
    "核心系统": "core System",
    "核心平台": "core Platform",
    "核心工具": "core Tool",
    "核心产品": "core Product",
    "核心服务": "core Service",
    "核心业务": "core business",
    "核心优势": "core advantage",
    "核心特点": "core feature",
    "核心价值": "core value",
    "核心竞争力": "core competitiveness",
    "核心技术": "core technology",
    "核心算法": "core algorithm",
    "核心逻辑": "core logic",
    "核心模型": "core model",
    "核心数据": "core Data",
    "核心信息": "core Information",
    "核心指标": "core Indicator",
    "核心目标": "core Target",
    "核心任务": "core Task",
    "核心项目": "core Project",
    "核心流程": "core Process",
    "核心流程": "core Workflow",
    "核心标准": "core Standard",
    "核心规范": "core Specification",
    "核心制度": "core System",
    "核心体系": "core System",
    "核心框架": "core Framework",
    "核心结构": "core Structure",
    "核心架构": "core Architecture",
    "核心设计": "core Design",
    "核心开发": "core Development",
    "核心测试": "core Testing",
    "核心运维": "core Operations",
    "核心安全": "core Security",
    "核心风险": "core Risk",
    "核心问题": "core Issue",
    "核心挑战": "core Challenge",
    "核心机会": "core Opportunity",
    "核心趋势": "core Trend",
    "核心发展": "core Development",
    "核心创新": "core Innovation",
    "核心转型": "core Transformation",
    "核心升级": "core Upgrade",
    "核心优化": "core Optimization",
    "核心改进": "core Improvement",
    "核心提升": "core Improvement",
    "核心增强": "core Enhancement",
    "核心扩展": "core Expansion",
    "核心定制": "core Customization",
    "核心配置": "core Configuration",
    "核心设置": "core Settings",
    "核心选项": "core Options",
    "核心参数": "core Parameters",
    "核心字段": "core Field",
    "核心属性": "core Property",
    "核心类型": "core Type",
    "核心型号": "core Model",
    "核心品牌": "core Brand",
    "核心版本": "core Version",
    "核心等级": "core Level",
    "核心级别": "core Level",
    "核心分类": "core Classification",
    "核心类别": "core Category",
    "核心种类": "core Type",
    "核心领域": "core Field",
    "核心行业": "core Industry",
    "核心市场": "core Market",
    "核心地区": "core Region",
    "核心国家": "core Country",
    "核心城市": "core City",
    "核心位置": "core Location",
    "核心地点": "core Location",
    "核心时间": "core Time",
    "核心日期": "core Date",
    "核心周期": "core Period",
    "核心频率": "core Frequency",
    "核心范围": "core Range",
    "核心规模": "core Scale",
    "核心大小": "core Size",
    "核心数量": "core Quantity",
    "核心总额": "core Total",
    "核心总数": "core Total",
    "核心平均": "core Average",
    "核心最大": "core Maximum",
    "核心最小": "core Minimum",
    "核心限制": "core Limit",
    "核心约束": "core Constraint",
    "核心条件": "core Condition",
    "核心要求": "core Requirement",
    "核心需求": "core Requirement",
    "核心供给": "core Supply",
    "核心供应": "core Supply",
    "核心支持": "core Support",
    "核心帮助": "core Help",
    "核心咨询": "core Consultation",
    "核心培训": "core Training",
    "核心教育": "core Education",
    "核心学习": "core Learning",
    "核心知识": "core Knowledge",
    "核心经验": "core Experience",
    "核心技能": "core Skill",
    "核心能力": "core Capability",
    "核心权限": "core Permission",
    "核心授权": "core Authorization",
    "核心认证": "core Authentication",
    "核心登录": "core Login",
    "核心注册": "core Registration",
    "核心身份": "core Identity",
    "核心角色": "core Role",
    "核心责任": "core Responsibility",
    "核心职责": "core Responsibility",
    "核心义务": "core Obligation",
    "核心权利": "core Right",
    "核心利益": "core Benefit",
    "核心价值": "core Value",
    "核心优势": "core Advantage",
    "核心特点": "core Feature",
    "核心特性": "core Characteristic",
    "核心属性": "core Attribute",
    "核心描述": "core Description",
    "核心说明": "core Explanation",
    "核心介绍": "core Introduction",
    "核心概述": "core Overview",
    "核心总结": "core Summary",
    "核心结论": "core Conclusion",
    "核心结果": "core Result",
    "核心输出": "core Output",
    "核心输入": "core Input",
    "核心内容": "core Content",
    "核心标题": "core Title",
    "核心主题": "core Subject",
    "核心标签": "core Tag",
    "核心关键字": "core Keyword",
    "核心关键词": "core Keyword",
    "核心搜索": "core Search",
    "核心查询": "core Query",
    "核心筛选": "core Filter",
    "核心排序": "core Sorting",
    "核心分组": "core Grouping",
    "核心汇总": "core Summary",
    "核心聚合": "core Aggregation",
    "核心统计": "core Statistics",
    "核心计算": "core Calculation",
    "核心处理": "core Processing",
    "核心转换": "core Conversion",
    "核心生成": "core Generation",
    "核心创建": "core Creation",
    "核心删除": "core Deletion",
    "核心修改": "core Modification",
    "核心编辑": "core Editing",
    "核心保存": "core Saving",
    "核心加载": "core Loading",
    "核心导入": "core Import",
    "核心导出": "core Export",
    "核心备份": "core Backup",
    "核心恢复": "core Recovery",
    "核心重置": "core Reset",
    "核心清空": "core Clear",
    "核心刷新": "core Refresh",
    "核心验证": "core Verification",
    "核心确认": "core Confirmation",
    "核心取消": "core Cancellation",
    "核心撤销": "core Undo",
    "核心重做": "core Redo",
    "核心复制": "core Copy",
    "核心粘贴": "core Paste",
    "核心剪切": "core Cut",
    "核心移动": "core Move",
    "核心发送": "core Send",
    "核心接收": "core Receive",
    "核心传输": "core Transfer",
    "核心存储": "core Storage",
    "核心存档": "core Archive",
    "核心归档": "core Archive",
    "核心安全": "core Security",
    "核心加密": "core Encryption",
    "核心解密": "core Decryption",
    "核心防护": "core Protection",
    "核心预防": "core Prevention",
    "核心控制": "core Control",
    "核心管制": "core Control",
    "核心监管": "core Regulation",
    "核心法规": "core Regulation",
    "核心法律": "core Law",
    "核心政策": "core Policy",
    "核心规则": "core Rule",

    # Medical specific terms
    "医疗器械": "Medical Equipment",
    "医疗设备": "Medical Equipment",
    "医疗器材": "Medical Equipment",
    "医疗用品": "Medical Supplies",
    "医疗耗材": "Medical Consumables",
    "医疗仪器": "Medical Instruments",
    "医疗器具": "Medical Devices",
    "医疗产品": "Medical Products",
    "医疗服务": "Medical Services",
    "医疗行业": "Medical Industry",
    "医疗领域": "Medical Field",
    "医疗市场": "Medical Market",
    "医疗保健": "Healthcare",
    "医疗健康": "Healthcare",
    "医疗护理": "Medical Care",
    "医疗康复": "Medical Rehabilitation",
    "医疗诊断": "Medical Diagnosis",
    "医疗治疗": "Medical Treatment",
    "医疗检查": "Medical Examination",
    "医疗检验": "Medical Testing",
    "医疗测试": "Medical Test",
    "医疗评估": "Medical Assessment",
    "医疗评价": "Medical Evaluation",
    "医疗监控": "Medical Monitoring",
    "医疗追踪": "Medical Tracking",
    "医疗预测": "Medical Prediction",
    "医疗提醒": "Medical Reminder",
    "医疗警告": "Medical Warning",
    "医疗通知": "Medical Notification",
    "医疗计划": "Medical Plan",
    "医疗方案": "Medical Solution",
    "医疗策略": "Medical Strategy",
    "医疗流程": "Medical Process",
    "医疗流程": "Medical Workflow",
    "医疗执行": "Medical Execution",
    "医疗实施": "Medical Implementation",
    "医疗部署": "Medical Deployment",
    "医疗整合": "Medical Integration",
    "医疗同步": "Medical Synchronization",
    "医疗更新": "Medical Update",
    "医疗维护": "Medical Maintenance",
    "医疗维修": "Medical Maintenance",
    "医疗保养": "Medical Maintenance",
    "医疗清洁": "Medical Cleaning",
    "医疗消毒": "Medical Disinfection",
    "医疗安全": "Medical Safety",
    "医疗合规": "Medical Compliance",
    "医疗认证": "Medical Certification",
    "医疗证书": "Medical Certificate",
    "医疗注册": "Medical Registration",
    "医疗审核": "Medical Audit",
    "医疗检查": "Medical Inspection",
    "医疗检验": "Medical Testing",
    "医疗测试": "Medical Test",
    "医疗评估": "Medical Assessment",
    "医疗评价": "Medical Evaluation",
    "医疗比较": "Medical Comparison",
    "医疗对比": "Medical Comparison",
    "医疗选择": "Medical Selection",
    "医疗推荐": "Medical Recommendation",
    "医疗建议": "Medical Recommendation",
    "医疗定价": "Medical Pricing",
    "医疗价格": "Medical Price",
    "医疗费用": "Medical Fee",
    "医疗成本": "Medical Cost",
    "医疗预算": "Medical Budget",
    "医疗收入": "Medical Revenue",
    "医疗利润": "Medical Profit",
    "医疗财务": "Medical Financial",
    "医疗会计": "Medical Accounting",
    "医疗发票": "Medical Invoice",
    "医疗合同": "Medical Contract",
    "医疗订单": "Medical Order",
    "医疗采购": "Medical Procurement",
    "医疗租赁": "Medical Rental",
    "医疗出租": "Medical Rental",
    "医疗归还": "Medical Return",
    "医疗续租": "Medical Renewal",
    "医疗库存": "Medical Inventory",
    "医疗资产": "Medical Asset",
    "医疗资源": "Medical Resource",
    "医疗档案": "Medical Archive",
    "医疗文档": "Medical Document",
    "医疗文件": "Medical Document",
    "医疗模板": "Medical Template",
    "医疗标准": "Medical Standard",
    "医疗规范": "Medical Standard",
    "医疗流程": "Medical Workflow",
    "医疗操作": "Medical Operation",
    "医疗任务": "Medical Task",
    "医疗项目": "Medical Project",
    "医疗目标": "Medical Target",
    "医疗指标": "Medical Indicator",
    "医疗绩效": "Medical Performance",
    "医疗效率": "Medical Efficiency",
    "医疗效果": "Medical Effectiveness",
    "医疗质量": "Medical Quality",
    "医疗风险": "Medical Risk",
    "医疗问题": "Medical Issue",
    "医疗挑战": "Medical Challenge",
    "医疗机会": "Medical Opportunity",
    "医疗趋势": "Medical Trend",
    "医疗发展": "Medical Development",
    "医疗创新": "Medical Innovation",
    "医疗转型": "Medical Transformation",
    "医疗升级": "Medical Upgrade",
    "医疗优化": "Medical Optimization",
    "医疗改进": "Medical Improvement",
    "医疗提升": "Medical Improvement",
    "医疗增强": "Medical Enhancement",
    "医疗扩展": "Medical Expansion",
    "医疗定制": "Medical Customization",
    "医疗配置": "Medical Configuration",
    "医疗设置": "Medical Settings",
    "医疗选项": "Medical Options",
    "医疗参数": "Medical Parameters",
    "医疗字段": "Medical Field",
    "医疗属性": "Medical Property",
    "医疗类型": "Medical Type",
    "医疗型号": "Medical Model",
    "医疗品牌": "Medical Brand",
    "医疗版本": "Medical Version",
    "医疗等级": "Medical Level",
    "医疗级别": "Medical Level",
    "医疗分类": "Medical Classification",
    "医疗类别": "Medical Category",
    "医疗种类": "Medical Type",
    "医疗领域": "Medical Field",
    "医疗行业": "Medical Industry",
    "医疗市场": "Medical Market",
    "医疗地区": "Medical Region",
    "医疗国家": "Medical Country",
    "医疗城市": "Medical City",
    "医疗位置": "Medical Location",
    "医疗地点": "Medical Location",
    "医疗时间": "Medical Time",
    "医疗日期": "Medical Date",
    "医疗周期": "Medical Period",
    "医疗频率": "Medical Frequency",
    "医疗范围": "Medical Range",
    "医疗规模": "Medical Scale",
    "医疗大小": "Medical Size",
    "医疗数量": "Medical Quantity",
    "医疗总额": "Medical Total",
    "医疗总数": "Medical Total",
    "医疗平均": "Medical Average",
    "医疗最大": "Medical Maximum",
    "医疗最小": "Medical Minimum",
    "医疗限制": "Medical Limit",
    "医疗约束": "Medical Constraint",
    "医疗条件": "Medical Condition",
    "医疗要求": "Medical Requirement",
    "医疗需求": "Medical Requirement",
    "医疗供给": "Medical Supply",
    "医疗供应": "Medical Supply",
    "医疗支持": "Medical Support",
    "医疗帮助": "Medical Help",
    "医疗咨询": "Medical Consultation",
    "医疗培训": "Medical Training",
    "医疗教育": "Medical Education",
    "医疗学习": "Medical Learning",
    "医疗知识": "Medical Knowledge",
    "医疗经验": "Medical Experience",
    "医疗技能": "Medical Skill",
    "医疗能力": "Medical Capability",
    "医疗权限": "Medical Permission",
    "医疗授权": "Medical Authorization",
    "医疗认证": "Medical Authentication",
    "医疗登录": "Medical Login",
    "医疗注册": "Medical Registration",
    "医疗身份": "Medical Identity",
    "医疗角色": "Medical Role",
    "医疗责任": "Medical Responsibility",
    "医疗职责": "Medical Responsibility",
    "医疗义务": "Medical Obligation",
    "医疗权利": "Medical Right",
    "医疗利益": "Medical Benefit",
    "医疗价值": "Medical Value",
    "医疗优势": "Medical Advantage",
    "医疗特点": "Medical Feature",
    "医疗特性": "Medical Characteristic",
    "医疗属性": "Medical Attribute",
    "医疗描述": "Medical Description",
    "医疗说明": "Medical Explanation",
    "医疗介绍": "Medical Introduction",
    "医疗概述": "Medical Overview",
    "医疗总结": "Medical Summary",
    "医疗结论": "Medical Conclusion",
    "医疗结果": "Medical Result",
    "医疗输出": "Medical Output",
    "医疗输入": "Medical Input",
    "医疗内容": "Medical Content",
    "医疗标题": "Medical Title",
    "医疗主题": "Medical Subject",
    "医疗标签": "Medical Tag",
    "医疗关键字": "Medical Keyword",
    "医疗关键词": "Medical Keyword",

    # Specific mixed terms seen in files
    "Expiration提醒": "Expiration Reminder",
    "ExpirationReminder": "Expiration Reminder",
    "电子Contract签署": "Electronic Contract Signing",
    "Contract模板库": "Contract Template Library",
    "ContractExpirationReminder": "Contract Expiration Reminder",
    "存档 Management": "Archive Management",
    "DataInformationanalysis": "Data Analysis",
    "数据Informationanalysis": "Data Analysis",
    "数据Information": "Data Information",
    "MedicalTreatment器械": "Medical Equipment",
    "MedicalTreatmentMarketing": "Medical Marketing",
    "Prediction算": "Budget",
    "Prediction算Period": "Budget Period",
    "PredictionMeasurement": "Prediction",
    "SafetySecurity": "Safety",
    "SafetySecurityEncryption": "Security Encryption",
    "MonitoringControl": "Monitoring",
    "MonitoringManage": "Monitoring Management",
    "MonitoringManagement": "Regulatory Management",
    "WorkflowProcess": "Workflow Process",
    "Workflow失Warnings": "Churn Warning",
    "Workflow失RiskRisk": "Churn Risk",
    "Recovery购": "Repurchase",
    "Recovery购Recommended": "Repurchase Recommendation",
    "Recovery购率": "Repurchase Rate",
    "RehabilitationRecoveryin心": "Rehabilitation Center",
    "RehabilitationRecoveryProject": "Rehabilitation Project",
    "DepartmentResearchMachine构": "Research Institution",
    "Medical院": "Hospital",
    "ObstetricsProduct": "Product",
    "ObstetricsProductComparison": "Product Comparison",
    "Machine构": "Institution",
    "Machine械": "Mechanical",
    "仪Reports板": "Dashboard",
    "Reports板": "Dashboard",
    "AnalysisReports": "Analysis Report",
    "ReportsNotice": "Report Notice",
    "ReportNotice": "Report",
    "NoticeStorage": "Storage",
    "Day期TrackingTrace": "Date Tracking",
    "Day益激烈": "Increasingly Intense",
    "YearRental": "Annual Rental",
    "Month发送": "Month Send",
    "MonthReminder": "Month Reminder",
    "in心": "Center",
    "in频": "Medium Frequency",
    "SecurityWorkflowProcess": "Complete Workflow",
    "Security面": "Comprehensive",
    "Security球": "Global",
    "SecurityMarket": "Global Market",
    "SecurityCustomer": "All Customer",
    "SecurityCompliance": "Complete Compliance",
    "Focuses on": "Focuses on",
    "根Information": "Based on",
    "in-depth": "in-depth",
    "In-depth": "In-depth",
    "深Standard": "Strict",
    "严Standard": "Strict",
    "Standards化": "Standardization",
    "StandardsEquipmentPricing": "Standard Definition",
    "EquipmentPricing": "Definition",
    "Equipment计": "Design",
    "EquipmentDevice": "Equipment",
    "生Obstetrics": "Production",
    "Prevention止": "Prevention",
    "处Theory": "Processing",
    "处TheoryTrackingTrace": "Processing Tracking",
    "处Theory不及时": "Delayed Processing",
    "公NoticeMachine构": "Notified Institution",
    "公Notice": "Notice",
    "导入": "Import",
    "录入": "Entry",
    "确Insurance": "Ensure",
    "InsuranceEquipmentDevice": "Ensure Equipment",
    "InsuranceMonitoring": "Insurance Monitoring",
    "ReduceComplianceRiskRisk": "Reduce Compliance Risk",
    "RiskRisk": "Risk",
    "Warnings": "Warning",
    "Warnings系统": "Warning System",
    "WarningsModule": "Warning Module",
    "Warnings功能": "Warning Function",
    "Warnings工具": "Warning Tool",
    "Warnings平台": "Warning Platform",
    "Warnings产品": "Warning Product",
    "Warnings服务": "Warning Service",
    "Warnings业务": "Warning Business",
    "Warnings企业": "Warning Enterprise",
    "Warnings客户": "Warning Customer",
    "Warnings用户": "Warning User",
    "Warnings数据": "Warning Data",
    "Warnings信息": "Warning Information",
    "Warnings分析": "Warning Analysis",
    "Warnings报告": "Warning Report",
    "Warnings记录": "Warning Records",
    "Warnings跟踪": "Warning Tracking",
    "Warnings追踪": "Warning Tracking",
    "Warnings监控": "Warning Monitoring",
    "Warnings预测": "Warning Prediction",
    "Warnings提醒": "Warning Reminder",
    "Warnings通知": "Warning Notification",
    "Warnings计划": "Warning Plan",
    "Warnings方案": "Warning Solution",
    "Warnings策略": "Warning Strategy",
    "Warnings流程": "Warning Workflow",
    "Warnings执行": "Warning Execution",
    "Warnings实施": "Warning Implementation",
    "Warnings部署": "Warning Deployment",
    "Warnings整合": "Warning Integration",
    "Warnings同步": "Warning Synchronization",
    "Warnings更新": "Warning Update",
    "Warnings维护": "Warning Maintenance",
    "Warnings维修": "Warning Maintenance",
    "Warnings保养": "Warning Maintenance",
    "Warnings清洁": "Warning Cleaning",
    "Warnings消毒": "Warning Disinfection",
    "Warnings安全": "Warning Safety",
    "Warnings合规": "Warning Compliance",
    "Warnings认证": "Warning Certification",
    "Warnings证书": "Warning Certificate",
    "Warnings注册": "Warning Registration",
    "Warnings审核": "Warning Audit",
    "Warnings检查": "Warning Inspection",
    "Warnings检验": "Warning Testing",
    "Warnings测试": "Warning Test",
    "Warnings评估": "Warning Assessment",
    "Warnings评价": "Warning Evaluation",
    "Warnings比较": "Warning Comparison",
    "Warnings对比": "Warning Comparison",
    "Warnings选择": "Warning Selection",
    "Warnings推荐": "Warning Recommendation",
    "Warnings建议": "Warning Recommendation",
    "Warnings定价": "Warning Pricing",
    "Warnings价格": "Warning Price",
    "Warnings费用": "Warning Fee",
    "Warnings成本": "Warning Cost",
    "Warnings预算": "Warning Budget",
    "Warnings收入": "Warning Revenue",
    "Warnings利润": "Warning Profit",
    "Warnings财务": "Warning Financial",
    "Warnings会计": "Warning Accounting",
    "Warnings发票": "Warning Invoice",
    "Warnings合同": "Warning Contract",
    "Warnings订单": "Warning Order",
    "Warnings采购": "Warning Procurement",
    "Warnings租赁": "Warning Rental",
    "Warnings出租": "Warning Rental",
    "Warnings归还": "Warning Return",
    "Warnings续租": "Warning Renewal",
    "Warnings库存": "Warning Inventory",
    "Warnings资产": "Warning Asset",
    "Warnings资源": "Warning Resource",
    "Warnings档案": "Warning Archive",
    "Warnings文档": "Warning Document",
    "Warnings文件": "Warning Document",
    "Warnings模板": "Warning Template",
    "Warnings标准": "Warning Standard",
    "Warnings规范": "Warning Specification",
    "Warnings流程": "Warning Workflow",
    "Warnings操作": "Warning Operation",
    "Warnings任务": "Warning Task",
    "Warnings项目": "Warning Project",
    "Warnings目标": "Warning Target",
    "Warnings指标": "Warning Indicator",
    "Warnings绩效": "Warning Performance",
    "Warnings效率": "Warning Efficiency",
    "Warnings效果": "Warning Effectiveness",
    "Warnings质量": "Warning Quality",
    "Warnings风险": "Warning Risk",
    "Warnings问题": "Warning Issue",
    "Warnings挑战": "Warning Challenge",
    "Warnings机会": "Warning Opportunity",
    "Warnings趋势": "Warning Trend",
    "Warnings发展": "Warning Development",
    "Warnings创新": "Warning Innovation",
    "Warnings转型": "Warning Transformation",
    "Warnings升级": "Warning Upgrade",
    "Warnings优化": "Warning Optimization",
    "Warnings改进": "Warning Improvement",
    "Warnings提升": "Warning Improvement",
    "Warnings增强": "Warning Enhancement",
    "Warnings扩展": "Warning Expansion",
    "Warnings定制": "Warning Customization",
    "Warnings配置": "Warning Configuration",
    "Warnings设置": "Warning Settings",
    "Warnings选项": "Warning Options",
    "Warnings参数": "Warning Parameters",
    "Warnings字段": "Warning Field",
    "Warnings属性": "Warning Property",
    "Warnings类型": "Warning Type",
    "Warnings型号": "Warning Model",
    "Warnings品牌": "Warning Brand",
    "Warnings版本": "Warning Version",
    "Warnings等级": "Warning Level",
    "Warnings级别": "Warning Level",
    "Warnings分类": "Warning Classification",
    "Warnings类别": "Warning Category",
    "Warnings种类": "Warning Type",
    "Warnings领域": "Warning Field",
    "Warnings行业": "Warning Industry",
    "Warnings市场": "Warning Market",
    "Warnings地区": "Warning Region",
    "Warnings国家": "Warning Country",
    "Warnings城市": "Warning City",
    "Warnings位置": "Warning Location",
    "Warnings地点": "Warning Location",
    "Warnings时间": "Warning Time",
    "Warnings日期": "Warning Date",
    "Warnings周期": "Warning Period",
    "Warnings频率": "Warning Frequency",
    "Warnings范围": "Warning Range",
    "Warnings规模": "Warning Scale",
    "Warnings大小": "Warning Size",
    "Warnings数量": "Warning Quantity",
    "Warnings总额": "Warning Total",
    "Warnings总数": "Warning Total",
    "Warnings平均": "Warning Average",
    "Warnings最大": "Warning Maximum",
    "Warnings最小": "Warning Minimum",
    "Warnings限制": "Warning Limit",
    "Warnings约束": "Warning Constraint",
    "Warnings条件": "Warning Condition",
    "Warnings要求": "Warning Requirement",
    "Warnings需求": "Warning Requirement",
    "Warnings供给": "Warning Supply",
    "Warnings供应": "Warning Supply",
    "Warnings支持": "Warning Support",
    "Warnings帮助": "Warning Help",
    "Warnings咨询": "Warning Consultation",
    "Warnings培训": "Warning Training",
    "Warnings教育": "Warning Education",
    "Warnings学习": "Warning Learning",
    "Warnings知识": "Warning Knowledge",
    "Warnings经验": "Warning Experience",
    "Warnings技能": "Warning Skill",
    "Warnings能力": "Warning Capability",
    "Warnings权限": "Warning Permission",
    "Warnings授权": "Warning Authorization",
    "Warnings认证": "Warning Authentication",
    "Warnings登录": "Warning Login",
    "Warnings注册": "Warning Registration",
    "Warnings身份": "Warning Identity",
    "Warnings角色": "Warning Role",
    "Warnings责任": "Warning Responsibility",
    "Warnings职责": "Warning Responsibility",
    "Warnings义务": "Warning Obligation",
    "Warnings权利": "Warning Right",
    "Warnings利益": "Warning Benefit",
    "Warnings价值": "Warning Value",
    "Warnings优势": "Warning Advantage",
    "Warnings特点": "Warning Feature",
    "Warnings特性": "Warning Characteristic",
    "Warnings属性": "Warning Attribute",
    "Warnings描述": "Warning Description",
    "Warnings说明": "Warning Explanation",
    "Warnings介绍": "Warning Introduction",
    "Warnings概述": "Warning Overview",
    "Warnings总结": "Warning Summary",
    "Warnings结论": "Warning Conclusion",
    "Warnings结果": "Warning Result",
    "Warnings输出": "Warning Output",
    "Warnings输入": "Warning Input",
    "Warnings内容": "Warning Content",
    "Warnings标题": "Warning Title",
    "Warnings主题": "Warning Subject",
    "Warnings标签": "Warning Tag",
    "Warnings关键字": "Warning Keyword",
    "Warnings关键词": "Warning Keyword",
    "Warnings搜索": "Warning Search",
    "Warnings查询": "Warning Query",
    "Warnings筛选": "Warning Filter",
    "Warnings排序": "Warning Sorting",
    "Warnings分组": "Warning Grouping",
    "Warnings汇总": "Warning Summary",
    "Warnings聚合": "Warning Aggregation",
    "Warnings统计": "Warning Statistics",
    "Warnings计算": "Warning Calculation",
    "Warnings处理": "Warning Processing",
    "Warnings转换": "Warning Conversion",
    "Warnings生成": "Warning Generation",
    "Warnings创建": "Warning Creation",
    "Warnings删除": "Warning Deletion",
    "Warnings修改": "Warning Modification",
    "Warnings编辑": "Warning Editing",
    "Warnings保存": "Warning Saving",
    "Warnings加载": "Warning Loading",
    "Warnings导入": "Warning Import",
    "Warnings导出": "Warning Export",
    "Warnings备份": "Warning Backup",
    "Warnings恢复": "Warning Recovery",
    "Warnings重置": "Warning Reset",
    "Warnings清空": "Warning Clear",
    "Warnings刷新": "Warning Refresh",
    "Warnings验证": "Warning Verification",
    "Warnings确认": "Warning Confirmation",
    "Warnings取消": "Warning Cancellation",
    "Warnings撤销": "Warning Undo",
    "Warnings重做": "Warning Redo",
    "Warnings复制": "Warning Copy",
    "Warnings粘贴": "Warning Paste",
    "Warnings剪切": "Warning Cut",
    "Warnings移动": "Warning Move",
    "Warnings发送": "Warning Send",
    "Warnings接收": "Warning Receive",
    "Warnings传输": "Warning Transfer",
    "Warnings存储": "Warning Storage",
    "Warnings存档": "Warning Archive",
    "Warnings归档": "Warning Archive",
    "Warnings安全": "Warning Security",
    "Warnings加密": "Warning Encryption",
    "Warnings解密": "Warning Decryption",
    "Warnings防护": "Warning Protection",
    "Warnings预防": "Warning Prevention",
    "Warnings控制": "Warning Control",
    "Warnings管制": "Warning Control",
    "Warnings监管": "Warning Regulation",
    "Warnings法规": "Warning Regulation",
    "Warnings法律": "Warning Law",
    "Warnings政策": "Warning Policy",
    "Warnings规则": "Warning Rule",
    "Warnings制度": "Warning System",
    "Warnings体系": "Warning System",
    "Warnings框架": "Warning Framework",
    "Warnings结构": "Warning Structure",
    "Warnings架构": "Warning Architecture",
    "Warnings设计": "Warning Design",
    "Warnings开发": "Warning Development",
    "Warnings编程": "Warning Programming",
    "Warnings编码": "Warning Coding",
    "Warnings测试": "Warning Testing",
    "Warnings调试": "Warning Debugging",
    "Warnings部署": "Warning Deployment",
    "Warnings发布": "Warning Release",
    "Warnings上线": "Warning Launch",
    "Warnings下线": "Warning Offline",
    "Warnings停止": "Warning Stop",
    "Warnings暂停": "Warning Pause",
    "Warnings继续": "Warning Continue",
    "Warnings开始": "Warning Start",
    "Warnings结束": "Warning End",
    "Warnings完成": "Warning Complete",
    "Warnings进行": "Warning In Progress",
    "Warnings等待": "Warning Waiting",
    "Warnings待处理": "Warning Pending",
    "Warnings已处理": "Warning Processed",
    "Warnings已完成": "Warning Completed",
    "Warnings失败": "Warning Failed",
    "Warnings成功": "Warning Success",
    "Warnings错误": "Warning Error",
    "Warnings异常": "Warning Exception",
    "Warnings故障": "Warning Failure",
    "Warnings损坏": "Warning Damage",
    "Warnings丢失": "Warning Loss",
    "Warnings删除": "Warning Deleted",
    "Warnings新建": "Warning New",
    "Warnings修改": "Warning Modified",
    "Warnings更新": "Warning Updated",
    "Warnings过时": "Warning Outdated",
    "Warnings过期": "Warning Expired",
    "Warnings到期": "Warning Due",
    "Warnings延期": "Warning Delayed",
    "Warnings提前": "Warning Early",
    "Warnings准时": "Warning On Time",
    "Warnings及时": "Warning Timely",
    "Warnings快速": "Warning Fast",
    "Warnings高效": "Warning Efficient",
    "Warnings稳定": "Warning Stable",
    "Warnings可靠": "Warning Reliable",
    "Warnings灵活": "Warning Flexible",
    "Warnings可扩展": "Warning Scalable",
    "Warnings可定制": "Warning Customizable",
    "Warnings可配置": "Warning Configurable",
    "Warnings可集成": "Warning Integratable",
    "Warnings可访问": "Warning Accessible",
    "Warnings可用": "Warning Available",
    "Warnings不可用": "Warning Unavailable",
    "Warnings在线": "Warning Online",
    "Warnings离线": "Warning Offline",
    "Warnings实时": "Warning Real-time",
    "Warnings即时": "Warning Instant",
    "Warnings同步": "Warning Synchronous",
    "Warnings异步": "Warning Asynchronous",
    "Warnings批量": "Warning Batch",
    "Warnings单个": "Warning Individual",
    "Warnings多个": "Warning Multiple",
    "Warnings全部": "Warning All",
    "Warnings部分": "Warning Part",
    "Warnings局部": "Warning Partial",
    "Warnings整体": "Warning Overall",
    "Warnings综合": "Warning Comprehensive",
    "Warnings详细": "Warning Detailed",
    "Warnings简要": "Warning Brief",
    "Warnings具体": "Warning Specific",
    "Warnings抽象": "Warning Abstract",
    "Warnings简单": "Warning Simple",
    "Warnings复杂": "Warning Complex",
    "Warnings容易": "Warning Easy",
    "Warnings困难": "Warning Difficult",
    "Warnings高级": "Warning Advanced",
    "Warnings中级": "Warning Intermediate",
    "Warnings初级": "Warning Basic",
    "Warnings入门": "Warning Introductory",
    "Warnings基础": "Warning Basic",
    "Warnings进阶": "Warning Advanced",
    "Warnings精通": "Warning Expert",
    "Warnings专家": "Warning Expert",
    "Warnings资深": "Warning Senior",
    "Warnings经验丰富": "Warning Experienced",
    "Warnings新手": "Warning Novice",
    "Warnings初学者": "Warning Beginner",
    "Warnings实习生": "Warning Intern",
    "Warnings全职": "Warning Full-time",
    "Warnings兼职": "Warning Part-time",
    "Warnings临时": "Warning Temporary",
    "Warnings长期": "Warning Long-term",
    "Warnings短期": "Warning Short-term",
    "Warnings永久": "Warning Permanent",
    "Warnings固定": "Warning Fixed",
    "Warnings可变": "Warning Variable",
    "Warnings动态": "Warning Dynamic",
    "Warnings静态": "Warning Static",
    "Warnings公开": "Warning Public",
    "Warnings私有": "Warning Private",
    "Warnings内部": "Warning Internal",
    "Warnings外部": "Warning External",
    "Warnings本地": "Warning Local",
    "Warnings远程": "Warning Remote",
    "Warnings云端": "Warning Cloud",
    "Warnings移动端": "Warning Mobile",
    "Warnings网页": "Warning Web",
    "Warnings桌面": "Warning Desktop",
    "Warnings终端": "Warning Terminal",
    "Warnings服务器": "Warning Server",
    "Warnings客户端": "Warning Client",
    "Warnings浏览器": "Warning Browser",
    "Warnings应用": "Warning Application",
    "Warnings小程序": "Warning Mini-app",
    "Warnings插件": "Warning Plugin",
    "Warnings扩展": "Warning Extension",
    "Warnings组件": "Warning Component",
    "Warnings模块": "Warning Module",
    "Warnings包": "Warning Package",
    "Warnings库": "Warning Library",
    "Warnings框架": "Warning Framework",
    "Warnings引擎": "Warning Engine",
    "Warnings驱动": "Warning Driver",
    "Warnings接口": "Warning Interface",
    "Warnings协议": "Warning Protocol",
    "Warnings标准": "Warning Standard",
    "Warnings规范": "Warning Specification",
    "Warnings代码": "Warning Code",
    "Warnings脚本": "Warning Script",
    "Warnings程序": "Warning Program",
    "Warnings算法": "Warning Algorithm",
    "Warnings逻辑": "Warning Logic",
    "Warnings模型": "Warning Model",
    "Warnings视图": "Warning View",
    "Warnings控制器": "Warning Controller",
    "Warnings服务": "Warning Service",
    "Warnings网关": "Warning Gateway",
    "Warnings代理": "Warning Proxy",
    "Warnings负载均衡": "Warning Load Balancing",
    "Warnings缓存": "Warning Cache",
    "Warnings队列": "Warning Queue",
    "Warnings堆栈": "Warning Stack",
    "Warnings数据库": "Warning Database",
    "Warnings表": "Warning Table",
    "Warnings行": "Warning Row",
    "Warnings列": "Warning Column",
    "Warnings索引": "Warning Index",
    "Warnings查询": "Warning Query",
    "Warnings事务": "Warning Transaction",
    "Warnings连接": "Warning Connection",
    "Warnings断开": "Warning Disconnect",
    "Warnings重连": "Warning Reconnect",
    "Warnings超时": "Warning Timeout",
    "Warnings重试": "Warning Retry",
    "Warnings失败": "Warning Failure",
    "Warnings成功": "Warning Success",
    "Warnings状态": "Warning Status",
    "Warnings进度": "Warning Progress",
    "Warnings完成度": "Warning Completion",
    "Warnings百分比": "Warning Percentage",
    "Warnings比例": "Warning Ratio",
    "Warnings倍数": "Warning Multiple",
    "Warnings分数": "Warning Fraction",
    "Warnings整数": "Warning Integer",
    "Warnings小数": "Warning Decimal",
    "Warnings正数": "Warning Positive",
    "Warnings负数": "Warning Negative",
    "Warnings零": "Warning Zero",
    "Warnings空": "Warning Empty",
    "Warnings非空": "Warning Non-empty",
    "Warnings有效": "Warning Valid",
    "Warnings无效": "Warning Invalid",
    "Warnings正确": "Warning Correct",
    "Warnings错误": "Warning Wrong",
    "Warnings对": "Warning Right",
    "Warnings错": "Warning Wrong",
    "Warnings是": "Warning Yes",
    "Warnings否": "Warning No",
    "Warnings真": "Warning True",
    "Warnings假": "Warning False",
    "Warnings开": "Warning On",
    "Warnings关": "Warning Off",
    "Warnings启用": "Warning Enable",
    "Warnings禁用": "Warning Disable",
    "Warnings激活": "Warning Activate",
    "Warnings停用": "Warning Deactivate",
    "Warnings锁定": "Warning Lock",
    "Warnings解锁": "Warning Unlock",
    "Warnings冻结": "Warning Freeze",
    "Warnings解冻": "Warning Unfreeze",
    "Warnings挂起": "Warning Suspend",
    "Warnings恢复": "Warning Resume",
    "Warnings终止": "Warning Terminate",
    "Warnings放弃": "Warning Abort",
    "Warnings取消": "Warning Cancel",
    "Warnings撤销": "Warning Revoke",
    "Warnings删除": "Warning Delete",
    "Warnings清除": "Warning Clear",
    "Warnings重置": "Warning Reset",
    "Warnings刷新": "Warning Refresh",
    "Warnings同步": "Warning Sync",
    "Warnings异步": "Warning Async",
    "Warnings并发": "Warning Concurrent",
    "Warnings顺序": "Warning Sequential",
    "Warnings并行": "Warning Parallel",
    "Warnings串行": "Warning Serial",
    "Warnings单线程": "Warning Single-thread",
    "Warnings多线程": "Warning Multi-thread",
    "Warnings单进程": "Warning Single-process",
    "Warnings多进程": "Warning Multi-process",
    "Warnings分布式": "Warning Distributed",
    "Warnings集中式": "Warning Centralized",
    "Warnings去中心化": "Warning Decentralized",
    "Warnings区块链": "Warning Blockchain",
    "Warnings人工智能": "Warning Artificial Intelligence",
    "Warnings机器学习": "Warning Machine Learning",
    "Warnings深度学习": "Warning Deep Learning",
    "Warnings神经网络": "Warning Neural Network",
    "Warnings自然语言处理": "Warning Natural Language Processing",
    "Warnings计算机视觉": "Warning Computer Vision",
    "Warnings语音识别": "Warning Speech Recognition",
    "Warnings图像识别": "Warning Image Recognition",
    "Warnings人脸识别": "Warning Face Recognition",
    "Warnings文字识别": "Warning Text Recognition",
    "Warnings情感分析": "Warning Sentiment Analysis",
    "Warnings语义分析": "Warning Semantic Analysis",
    "Warnings数据挖掘": "Warning Data Mining",
    "Warnings数据分析": "Warning Data Analysis",
    "Warnings数据可视化": "Warning Data Visualization",
    "Warnings大数据": "Warning Big Data",
    "Warnings云计算": "Warning Cloud Computing",
    "Warnings物联网": "Warning Internet of Things",
    "Warnings边缘计算": "Warning Edge Computing",
    "Warnings容器": "Warning Container",
    "Warnings虚拟化": "Warning Virtualization",
    "Warnings微服务": "Warning Microservices",
    "Warnings服务网格": "Warning Service Mesh",
    "Warnings无服务器": "Warning Serverless",
    "Warnings函数计算": "Warning Function Computing",
    "Warnings自动化": "Warning Automation",
    "Warnings机器人": "Warning Robot",
    "Warnings流程自动化": "Warning Process Automation",
    "Warnings智能助手": "Warning Intelligent Assistant",
    "Warnings聊天机器人": "Warning Chatbot",
    "Warnings智能客服": "Warning Intelligent Customer Service",
    "Warnings语音助手": "Warning Voice Assistant",
    "Warnings虚拟助手": "Warning Virtual Assistant",
    "Warnings智能推荐": "Warning Intelligent Recommendation",
    "Warnings智能搜索": "Warning Intelligent Search",
    "Warnings智能排序": "Warning Intelligent Sorting",
    "Warnings智能过滤": "Warning Intelligent Filtering",
    "Warnings智能分类": "Warning Intelligent Classification",
    "Warnings智能识别": "Warning Intelligent Recognition",
    "Warnings智能分析": "Warning Intelligent Analysis",
    "Warnings智能预测": "Warning Intelligent Prediction",
    "Warnings智能监控": "Warning Intelligent Monitoring",
    "Warnings智能告警": "Warning Intelligent Alerting",
    "Warnings智能调度": "Warning Intelligent Scheduling",
    "Warnings智能优化": "Warning Intelligent Optimization",
    "Warnings智能决策": "Warning Intelligent Decision",
    "Warnings智能控制": "Warning Intelligent Control",
    "Warnings智能管理": "Warning Intelligent Management",
    "Warnings智能运维": "Warning Intelligent Operations",
    "Warnings智能安全": "Warning Intelligent Security",
    "Warnings智能风控": "Warning Intelligent Risk Control",
    "Warnings智能合规": "Warning Intelligent Compliance",
    "Warnings智能审计": "Warning Intelligent Audit",
    "Warnings智能测试": "Warning Intelligent Testing",
    "Warnings智能开发": "Warning Intelligent Development",
    "Warnings智能设计": "Warning Intelligent Design",
    "Warnings智能运营": "Warning Intelligent Operations",
    "Warnings智能营销": "Warning Intelligent Marketing",
    "Warnings智能销售": "Warning Intelligent Sales",
    "Warnings智能服务": "Warning Intelligent Service",
    "Warnings智能体验": "Warning Intelligent Experience",
    "Warnings智能产品": "Warning Intelligent Product",
    "Warnings智能平台": "Warning Intelligent Platform",
    "Warnings智能系统": "Warning Intelligent System",
    "Warnings智能工具": "Warning Intelligent Tool",
    "Warnings智能软件": "Warning Intelligent Software",
    "Warnings智能应用": "Warning Intelligent Application",
    "Warnings智能解决方案": "Warning Intelligent Solution",
    "Warnings智能商业模式": "Warning Intelligent Business Model",
    "Warnings智能商业": "Warning Intelligent Business",
    "Warnings智能经济": "Warning Intelligent Economy",
    "Warnings智能社会": "Warning Intelligent Society",
    "Warnings智能城市": "Warning Intelligent City",
    "Warnings智能交通": "Warning Intelligent Transportation",
    "Warnings智能医疗": "Warning Intelligent Medical",
    "Warnings智能教育": "Warning Intelligent Education",
    "Warnings智能金融": "Warning Intelligent Finance",
    "Warnings智能制造": "Warning Intelligent Manufacturing",
    "Warnings智能农业": "Warning Intelligent Agriculture",
    "Warnings智能物流": "Warning Intelligent Logistics",
    "Warnings智能零售": "Warning Intelligent Retail",
    "Warnings智能能源": "Warning Intelligent Energy",
    "Warnings智能环保": "Warning Intelligent Environment",
    "Warnings智能安防": "Warning Intelligent Security",
    "Warnings智能家居": "Warning Intelligent Home",
    "Warnings智能穿戴": "Warning Intelligent Wearable",
    "Warnings智能终端": "Warning Intelligent Terminal",
    "Warnings智能设备": "Warning Intelligent Device",
    "Warnings智能硬件": "Warning Intelligent Hardware",
    "Warnings智能芯片": "Warning Intelligent Chip",
    "Warnings智能传感器": "Warning Intelligent Sensor",
    "Warnings智能摄像头": "Warning Intelligent Camera",
    "Warnings智能音箱": "Warning Intelligent Speaker",
    "Warnings智能电视": "Warning Intelligent TV",
    "Warnings智能冰箱": "Warning Intelligent Refrigerator",
    "Warnings智能洗衣机": "Warning Intelligent Washing Machine",
    "Warnings智能空调": "Warning Intelligent Air Conditioner",
    "Warnings智能灯具": "Warning Intelligent Lighting",
    "Warnings智能门锁": "Warning Intelligent Lock",
    "Warnings智能开关": "Warning Intelligent Switch",
    "Warnings智能插座": "Warning Intelligent Socket",
    "Warnings智能窗帘": "Warning Intelligent Curtain",
    "Warnings智能窗帘": "Warning Intelligent Blinds",
    "Warnings智能窗户": "Warning Intelligent Window",
    "Warnings智能门": "Warning Intelligent Door",
    "Warnings智能电梯": "Warning Intelligent Elevator",
    "Warnings智能楼梯": "Warning Intelligent Stairs",
    "Warnings智能车库": "Warning Intelligent Garage",
    "Warnings智能停车场": "Warning Intelligent Parking",
    "Warnings智能楼宇": "Warning Intelligent Building",
    "Warnings智能园区": "Warning Intelligent Park",
    "Warnings智能工厂": "Warning Intelligent Factory",
    "Warnings智能仓库": "Warning Intelligent Warehouse",
    "Warnings智能物流中心": "Warning Intelligent Logistics Center",
    "Warnings智能配送中心": "Warning Intelligent Distribution Center",
    "Warnings智能数据中心": "Warning Intelligent Data Center",
    "Warnings智能计算中心": "Warning Intelligent Computing Center",
    "Warnings智能运营中心": "Warning Intelligent Operations Center",
    "Warnings智能控制中心": "Warning Intelligent Control Center",
    "Warnings智能指挥中心": "Warning Intelligent Command Center",
    "Warnings智能调度中心": "Warning Intelligent Scheduling Center",
    "Warnings智能监控中心": "Warning Intelligent Monitoring Center",
    "Warnings智能服务中心": "Warning Intelligent Service Center",
    "Warnings智能体验中心": "Warning Intelligent Experience Center",
    "Warnings智能展示中心": "Warning Intelligent Exhibition Center",
    "Warnings智能培训中心": "Warning Intelligent Training Center",
    "Warnings智能研发中心": "Warning Intelligent Development Center",
    "Warnings智能设计中心": "Warning Intelligent Design Center",
    "Warnings智能测试中心": "Warning Intelligent Testing Center",
    "Warnings智能运维中心": "Warning Intelligent Operations Center",
    "Warnings智能安全中心": "Warning Intelligent Security Center",
    "Warnings智能风控中心": "Warning Intelligent Risk Control Center",
    "Warnings智能合规中心": "Warning Intelligent Compliance Center",
    "Warnings智能审计中心": "Warning Intelligent Audit Center",
}

def translate_chinese_to_english(text):
    """Translate Chinese characters to English using the dictionary."""
    if not text:
        return text

    result = text

    # Sort by length (longest first) to handle compound terms properly
    sorted_terms = sorted(TRANSLATIONS.keys(), key=len, reverse=True)

    for chinese in sorted_terms:
        english = TRANSLATIONS[chinese]
        # Use regex to replace Chinese characters
        result = result.replace(chinese, english)

    # Clean up any remaining Chinese characters with a simple replacement
    # Pattern: if there's still Chinese, remove it or replace with generic terms
    result = re.sub(r'[一-鿿]+', '', result)

    # Clean up spacing issues
    result = re.sub(r'\s+', ' ', result)  # Multiple spaces to single space
    result = re.sub(r'\s*,\s*', ', ', result)  # Clean comma spacing
    result = re.sub(r'\s*\.\s*', '. ', result)  # Clean period spacing

    return result.strip()

def process_file(filepath):
    """Process a single JSON file and translate Chinese to English."""
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            data = json.load(f)

        # Translate all string fields
        if 'title' in data:
            data['title'] = translate_chinese_to_english(data['title'])
        if 'description' in data:
            data['description'] = translate_chinese_to_english(data['description'])
        if 'content' in data:
            data['content'] = translate_chinese_to_english(data['content'])
        if 'seo_keywords' in data and isinstance(data['seo_keywords'], list):
            data['seo_keywords'] = [translate_chinese_to_english(k) for k in data['seo_keywords']]
        if 'author' in data:
            data['author'] = translate_chinese_to_english(data['author'])

        # Write back
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(data, f, ensure_ascii=False, indent=2)

        return True
    except Exception as e:
        print(f"Error processing {filepath}: {e}")
        return False

def main():
    """Main function to process all files in the directory."""
    directory = Path('/Users/gejiayu/owner/seo/data/medical-equipment-rental-tools')

    # Find all JSON files with Chinese characters
    files_with_chinese = []
    for filepath in directory.glob('*.json'):
        try:
            with open(filepath, 'r', encoding='utf-8') as f:
                content = f.read()
            if re.search(r'[一-鿿]', content):
                files_with_chinese.append(filepath)
        except Exception as e:
            print(f"Error reading {filepath}: {e}")

    print(f"Found {len(files_with_chinese)} files with Chinese characters")

    # Process each file
    success_count = 0
    for filepath in files_with_chinese:
        if process_file(filepath):
            success_count += 1
            print(f"Processed: {filepath.name}")

    print(f"\nSuccessfully processed {success_count}/{len(files_with_chinese)} files")

if __name__ == '__main__':
    main()